### ISSUE TITLE
Bug: Long emails overflow in account menu dropdown

### ISSUE THREAD

**Issue by oliviergoulet5** [maybe-finance/maybe#1025]
**Describe the bug**

Long emails overflow from the account menu dropdown.

**To Reproduce**
1. Go to any page that shows the sidebar
2. Click on avatar
3. See the email. It overflows when the email is too long.

**Expected behavior**

The email should either fit in the dropdown, or have ellipses to indicate that the email has been cut-off.

**Screenshots / Recordings**

![Pasted Graphic](https://github.com/user-attachments/assets/aa55e3fd-5991-4079-a510-a5fe8d5f0d1f)

**Additional context**

I think it should be as simple as adding the `text-ellipsis` and `overflow-hidden` Tailwind classes.

I am willing to contribute a PR for this!

**Comment by zachgoll** [comment]
@oliviergoulet5 @MikhailWahib definitely open to accepting a PR for this!  Should be a pretty quick one so whoever has a solution ready, feel free to submit.
