### ISSUE TITLE
Bug: Unique Constraint Violation Error When Creating Transaction in Different Currency

### ISSUE THREAD

**Issue by realsama** [maybe-finance/maybe#1037]
I encountered an error when creating a transaction in a different currency than the account. The error message is as follows:

```sh
PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_exchange_rates_on_base_converted_date_unique"
DETAIL: Key (from_currency, to_currency, date)=(NGN, USD, 2024-07-31) already exists.
```

Steps to reproduce:

Create a transaction in a currency different from the account currency.
- Observe the error mentioned above.
- It seems like there might be an issue with handling exchange rates or currency conversion. Could you please look into this?

Thank you for your help!

<img width="1321" alt="Screenshot 2024-07-31 at 20 46 02" src="https://github.com/user-attachments/assets/49711777-7ba4-4f5e-8d68-a7e63a37f23e">

**Comment by osaroadade** [comment]
To add more context to this:

If you add a new transaction, this error would leave and currency syncing would continue.

**Comment by zachgoll** [comment]
Done via #1069
