### ISSUE TITLE
Bug: Mobile view sidebar menu will not hide.

### ISSUE THREAD

**Issue by deanfourie1** [maybe-finance/maybe#1038]
**Describe the bug**
On the mobile view, the side menu will not hide making the entire right panel unusable.

**To Reproduce**
1. Go to the app on mobile device.
2. Click on anything or nothing, its always there.
3. See screenshots

**Expected behavior**
An auto collapsible or even manually collapsible left menu.

**Screenshots / Recordings**
If applicable, add screenshots or short video recordings to help show the bug in more detail.
![image](https://github.com/user-attachments/assets/fda0e30d-501a-4721-836e-33d7dfd0e0a3)

**Additional context**
So, I appologise if this is my stupidity, but it seems that I cannot access any items on the right side of the page.
By the way, loving this app, looks like it has a lot of potential.

**Comment by osaroadade** [comment]
The team is currently on prioritising the desktop web version of the app at the moment.

Learn more: https://github.com/maybe-finance/maybe/discussions/953#discussioncomment-9987915

**Comment by deanfourie1** [comment]
Ok no worries, I look forward to the mobile version!

**Comment by zachgoll** [comment]
Yep, @osaroadade is spot on here.  We'll eventually reach a point where we can allocate some time and resources to the mobile version of this, but at this moment, it's lower priority than building additional features.

**Comment by deanfourie1** [comment]
Thanks! Great work!

You can close this now.

**Comment by deanfourie1** [comment]
I mean, even if you don’t give mobile dev priority,

Even if you just made it usable it would be so much better, as the majority of use for me anyway is on the go, adding transactions etc would make testing much easier

**Comment by zachgoll** [comment]
@deanfourie1 others have suggested a "[companion app](https://github.com/maybe-finance/maybe/discussions/671)", which sounds like it might fit your use case better.

Could you please describe the specific use-case and workflow that you go through that would require mobile usage of the app so we can incorporate this thinking into our roadmap?

**Comment by deanfourie1** [comment]
Personally, I think an app is more of a waste of time.

For me I just use a ton of self hosted web based services as they have good responsive support for mobile devices, this works just fine. Just my 2 cents.

Use case for me would be say I'm out, and I buy something, I would immediately open the maybe web app and add that transaction to maybe, 

This could happen anywhere between 2 and 10 times a day.

This way at the end of the day, I can login to maybe on my desktop and go through and track all my spendings and transactions and see where I'm overspending etc.

Instead of having to add it all manually at the end of the day.

Unless there is bank account linking that pulls this data but even then having the ability to add manually on the go is a big one for me.

Thanks

**Comment by marco-studer-srf** [comment]
+1 on this. I would also like for Maybe finance to be usable on mobile for the exact same reasons as @deanfourie1. It is the only thing missing for me before I will switch from Firefly to Maybe.

**Comment by DRFR0ST** [comment]
A PWA with UI support for small viewports would do for me. It's all I need at this point. The current app is already quite usable on a phablet in landscape mode.

**Comment by zachgoll** [comment]
@dz3n phew, disaster averted! (#2092)
