### ISSUE TITLE
Make bulk request for exchange rates to Synth API 

### ISSUE THREAD

**Issue by mathix420** [maybe-finance/maybe#1047]
**Describe the bug**
See title.

**To Reproduce**
1. Set up project without synth API key first
2. Try to convert a currency on the App and get the expected error message
3. Then adding API key + restart server
4. Open the web app
5. Noticed the 700+ API calls

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/30dc1266-7095-491b-987d-8a38d6aee0a5)

**Comment by mathix420** [comment]
Update ... Restarting the server did stop the issue temporarily, seems to have happened again.

![image](https://github.com/user-attachments/assets/f6c4d39c-11a9-46fd-9ddd-bc600c9f371b)

**Comment by Shpigford** [comment]
@mathix420 Could you possibly take a screenshot or copy/paste a sample of the API calls you're seeing?

**Comment by mathix420** [comment]
Is it logged by the app?

**Comment by zachgoll** [comment]
@mathix420 the current implementation uses 1 Synth credit per exchange rate that is fetched.  So if you add a foreign currency account that is 2 years old, I would expect `2 * 365 = 730` Synth credits to be used to sync the daily historical balances for this account.

Can you confirm the following?

1. How many accounts do you have connected that have a different currency than your family currency?
2. Of these accounts, what is the oldest transaction or valuation date for each?

Eventually, we'll probably want to update this code to fetch rates in bulk from Synth:

https://github.com/maybe-finance/maybe/blob/edda5cb35b9d27990eaaa32c815251a8e224f2cf/app/models/exchange_rate/provided.rb#L9-L15

**Comment by zachgoll** [comment]
With the addition of the new "bulk" exchange rates endpoint, this issue is ready to incorporate more efficient API calls:

https://docs.synthfinance.com/reference/historical-range-rates

Up for grabs for anyone who wants to take it!  Comment below if you start working on it.

If nobody grabs by end of week, I'll get it done prior to the next release.
