### ISSUE TITLE
Build Stimulus Tooltip Controller + Populate Holdings/Cash Value on Investment Account

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1051]
## Feature Overview

The goal of this issue is to create a reusable tooltip Stimulus controller.  Our first use case for this will be to show the detailed breakdown of an investment account value as shown below:

![CleanShot 2024-08-04 at 20 16 48@2x](https://github.com/user-attachments/assets/b7a3e667-b9cc-4e7f-87c5-070ebd84c99e)

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] Build stimulus tooltip controller
- [ ] Populate tooltip on investment account pages to show the `Cash` and `Holdings` value of the account (so user can see total value breakdown)
- [ ] i18n english translations provided

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

Pretty straightforward here, no suggestions.

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/design/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?node-id=4374-87&t=X45nUNU3enzd5RrF-0

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
    - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
    - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

**Comment by zachgoll** [comment]
This issue is up for grabs!  Be sure to comment if you're working on it so others know as we don't assign issues.

**Comment by tonyvince** [comment]
I am taking this
