### ISSUE TITLE
Invalid data state: accountable records missing for some accounts in self hosted instances

### ISSUE THREAD

**Issue by jakubkottnauer** [maybe-finance/maybe#1068]
**Describe the bug**
I'm getting  a 500 error page right after opening Maybe. My Maybe instances auto-updates every night, I believe it started crashing ~2 days ago.

**Screenshots / Recordings**
Here's a log with that should provide enough info to get to the bottom of this.
![Screenshot 2024-08-07 at 15 23 19](https://github.com/user-attachments/assets/ae20c394-1f2c-414e-82e4-31ec11c57a24)

**Comment by zachgoll** [comment]
@jakubkottnauer would you mind running this against your DB to see if this is a stale data issue?

```sql
select accountable_id, accountable_type from accounts;
```

**Comment by zachgoll** [comment]
@jermorin thanks for providing that.  Appears to be a bug since all of the references seem to be intact.

I'll take a closer look at this shortly.

**Comment by zachgoll** [comment]
@jakubkottnauer @jermorin just to confirm, you're both on the latest version of Maybe and have migrated the database to the latest schema correct? (DB migrations should happen on container startup)

**Comment by zachgoll** [comment]
@jermorin awesome, very helpful thank you!

**Comment by zachgoll** [comment]
@jermorin would you mind running this updated query so we can see if any of your "accountables" records have accidentally been deleted?

I'm able to reproduce this error by manually deleting the "accountable" record for an account, but struggling to see how that could have happened in the first place:

```sql
SELECT 
    a.accountable_type,
    CASE a.accountable_type
        WHEN 'Crypto' THEN cryptos.id
        WHEN 'Depository' THEN depositories.id
        WHEN 'OtherAsset' THEN other_assets.id
        WHEN 'OtherLiability' THEN other_liabilities.id
        WHEN 'Investment' THEN investments.id
        WHEN 'Property' THEN properties.id
        WHEN 'Vehicle' THEN vehicles.id
        WHEN 'CreditCard' THEN credit_cards.id
        WHEN 'Loan' THEN loans.id
    END AS accountable_id
FROM accounts a 
LEFT JOIN cryptos ON cryptos.id = a.accountable_id AND a.accountable_type = 'Crypto'
LEFT JOIN depositories ON depositories.id = a.accountable_id AND a.accountable_type = 'Depository'
LEFT JOIN other_assets ON other_assets.id = a.accountable_id AND a.accountable_type = 'OtherAsset'
LEFT JOIN other_liabilities ON other_liabilities.id = a.accountable_id AND a.accountable_type = 'OtherLiability'
LEFT JOIN investments ON investments.id = a.accountable_id AND a.accountable_type = 'Investment'
LEFT JOIN properties ON properties.id = a.accountable_id AND a.accountable_type = 'Property'
LEFT JOIN vehicles ON vehicles.id = a.accountable_id AND a.accountable_type = 'Vehicle'
LEFT JOIN credit_cards ON credit_cards.id = a.accountable_id AND a.accountable_type = 'CreditCard'
LEFT JOIN loans ON loans.id = a.accountable_id AND a.accountable_type = 'Loan';
```

We're looking for any NULL values in the accountable_id column:

![CleanShot 2024-08-09 at 12 09 29@2x](https://github.com/user-attachments/assets/4dc43b6b-1da7-431f-a0f0-4899dc80d7a2)

**Comment by zachgoll** [comment]
I'll merge #1071 to avoid the app crash, but leaving this issue open until we identify the root cause.

**Comment by jakubkottnauer** [comment]
Thanks @zachgoll, can confirm the latest Maybe version works again 👍

**Comment by zachgoll** [comment]
@jakubkottnauer @jermorin thanks for confirming!

Based on @jermorin's screenshot, it appears that this is a _referential integrity_ issue, which I believe must have happened in a prior state of the app (this shouldn't happen moving forward).

What do you both think of the following solution moving forward?

1. Write a migration that creates an empty "accountable" record for each account where one is missing
2. Revert my temporary changes (I don't think we want to suppress this sort of error in the long term since it is so integral to the app's domain)

**Comment by zachgoll** [comment]
@jermorin yep we're starting to reach a bit of stability now so hopefully the experience continues to improve for self hosting :)
