### ISSUE TITLE
Add global support to real estate addition

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#109]
![CleanShot 2024-01-16 at 09 41 22@2x](https://github.com/maybe-finance/maybe/assets/35243/b23b75a9-6815-40e8-8494-b57db09f69c0)

Currently the "Add real estate" modal is locked to the US, but there's no functional reason to keep it this way.

We should allow any country via a dropdown listing of all countries.

**Comment by Danm72** [comment]
Agreed, secondly some way to link mortgages & real estate.

**Comment by Shpigford** [comment]
> Agreed, secondly some way to link mortgages & real estate.

Definitely want a way to link in the future, but just want to clarify that will be outside the scope of this specific Issue.

**Comment by Shpigford** [comment]
Implemented with #116
