### ISSUE TITLE
Bug: The response (500) did not contain the expected <turbo-frame id="drawer">

### ISSUE THREAD

**Issue by mkremnev** [maybe-finance/maybe#1097]
**Describe the bug**
I added "Holdings transactions" in the investment account and when I click on this transaction to edit it, I get an error in the console devtools and the drawer for editing this transaction does not open.

**To Reproduce**
1. add a purchase transaction of AAPL stock in the investment account
2. click on the added transaction
3. See error in console devtools

**Expected behavior**
A window for editing the transaction opens.

**Screenshots / Recordings**
<img width="728" alt="image" src="https://github.com/user-attachments/assets/13c2c23d-8019-417b-95e1-7e5137edd553">

**Additional context**
Investment -> any new investment -> new holding transactions -> click transaction -> error devtools

**Comment by zachgoll** [comment]
@mkremnev I'm not sure what you mean by add "Holdings transactions".  Would you mind taking a look at the video I recorded below and telling me what part of this fails for you?

https://github.com/user-attachments/assets/b44195e6-88a3-4d2f-8475-728d64c5b119

Each of the "drawers" should be relatively empty, but there shouldn't be an error.

**Comment by mkremnev** [comment]
https://github.com/user-attachments/assets/cb0a4b3b-51bb-4f90-8008-0d9a9304c409

**Comment by zachgoll** [comment]
@mkremnev got it, very helpful thank you.  Will dig into this.

**Comment by mkremnev** [comment]
I get this error in the log:

```
E, [2024-08-16T20:45:33.047212 #1] ERROR -- : [ac619310-0600-4c73-9a7a-98958cfd72ab]   
[ac619310-0600-4c73-9a7a-98958cfd72ab] ActionView::Template::Error (undefined method `[]' for nil):
[ac619310-0600-4c73-9a7a-98958cfd72ab] 
Causes:
[ac619310-0600-4c73-9a7a-98958cfd72ab] NoMethodError (undefined method `[]' for nil)
[ac619310-0600-4c73-9a7a-98958cfd72ab]      9: 
[ac619310-0600-4c73-9a7a-98958cfd72ab]     10: <%= tag.div style: mixed_hex_styles(hex),
[ac619310-0600-4c73-9a7a-98958cfd72ab]     11:             class: [size_classes[size], "flex shrink-0 items-center justify-center rounded-full"] do %>
[ac619310-0600-4c73-9a7a-98958cfd72ab]     12:   <%= tag.span name[0].upcase, class: ["font-medium", size == "sm" ? "text-xs" : "text-sm"] %>
[ac619310-0600-4c73-9a7a-98958cfd72ab]     13: <% end %>
[ac619310-0600-4c73-9a7a-98958cfd72ab]   
[ac619310-0600-4c73-9a7a-98958cfd72ab] app/views/shared/_circle_logo.html.erb:12
[ac619310-0600-4c73-9a7a-98958cfd72ab] app/views/shared/_circle_logo.html.erb:10
[ac619310-0600-4c73-9a7a-98958cfd72ab] app/views/account/holdings/show.html.erb:9
[ac619310-0600-4c73-9a7a-98958cfd72ab] app/helpers/application_helper.rb:56:in `drawer'
[ac619310-0600-4c73-9a7a-98958cfd72ab] app/views/account/holdings/show.html.erb:1
```

**Comment by mkremnev** [comment]
https://github.com/user-attachments/assets/d9c8dd3e-95b3-4931-87a9-7835a53a04b3

I also noticed this error when hovering over a DOM element

**Comment by tonyvince** [comment]
[allow_browser versions: :modern](https://github.com/maybe-finance/maybe/blob/main/app/controllers/application_controller.rb#L6) supports safari versions starting from [only >= 17.2](https://github.com/rails/rails/issues/52534#issuecomment-2274201222). Chrome inspector is giving me the follwoing

```
(ruby) request.user_agent
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15"
(ruby) useragent = UserAgent.parse request.user_agent
[#<UserAgent:0x0000000133b71298 @comment=["Macintosh", "Intel Mac OS X 10_15_7"], @product="Mozilla", @version=#<UserAgent::Version 5.0>>,
 #<UserAgent:0x0000000133b70fa0 @comment=["KHTML, like Gecko"], @product="AppleWebKit", @version=#<UserAgent::Version 605.1.15>>,
 #<UserAgent:0x0000000133b70c80 @comment=nil, @product="Version", @version=#<UserAgent::Version 16.0>>,
 #<UserAgent:0x0000000133b709d8 @comment=nil, @product="Safari", @version=#<UserAgent::Version 605.1.15>>]
(ruby) useragent.browser
"Safari"
(ruby) useragent.version
#<UserAgent::Version 16.0>
(rdbg)
```
So I think this is not an issue

**Comment by mkremnev** [comment]
> [allow_browser versions: :modern](https://github.com/maybe-finance/maybe/blob/main/app/controllers/application_controller.rb#L6) supports safari versions starting from [only >= 17.2](https://github.com/rails/rails/issues/52534#issuecomment-2274201222). Chrome inspector is giving me the follwoing
> 
> ```
> (ruby) request.user_agent
> "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15"
> (ruby) useragent = UserAgent.parse request.user_agent
> (ruby) useragent.browser
> "Safari"
> (ruby) useragent.version
> #<UserAgent::Version 16.0>
> (rdbg)
> ```
> 
> So I think this is expected

<img width="1249" alt="image" src="https://github.com/user-attachments/assets/f23c5819-786a-44af-bdc9-47aa739efced">

I have the same error in Safari v17.6. I also tried to place maybe on the "Render" hosting and I also get the same error. The error may be related to the currency I have set: RUB?

**Comment by tonyvince** [comment]
I don't think the Safari version and what webkit uses under the hood are not the same

**Comment by mkremnev** [comment]
@tonyvince I use Chrome (latest version 127.0.6533.120) and Safari (latest version 17.6) with DevTools closed, my drawer does not open as in the video by @zachgoll https://github.com/maybe-finance/maybe/issues/1097#issuecomment-2294149525. I opened devtools to see if there are any errors or not and sent a screenshot of the error.

**Comment by mkremnev** [comment]
@tonyvince 
Uploading Запись экрана 6.mov…
