### ISSUE TITLE
Bug: Exchange Rates Missing for NGN to USD Conversion After App Update

### ISSUE THREAD

**Issue by osaroadade** [maybe-finance/maybe#1137]
**Describe the bug**
The app is unable to retrieve exchange rates for NGN to USD conversions. This issue appeared after a recent app update. The Synth API is currently failing to provide the required exchange rate data.

**To Reproduce**
1. Open the Maybe app
2. Navigate to an account or transaction view that requires NGN to USD conversion (you might want your default currency to be NGN and have an account that uses USD)
3. Observe the banner notification saying "Exchange rates missing"
4. Click on troubleshoot and see error details

**Expected behavior**
It should convert from USD to NGN successfully. 

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/134f7e08-d436-4cb6-8f30-8ddaef554371)
![image](https://github.com/user-attachments/assets/b1a7b30a-64cf-4c5f-b94a-0b65cbc9738d)

**Additional context**
The app was recently updated, which may have introduced this issue.

**Comment by zachgoll** [comment]
@osaroadade I have not been able to reproduce this error and Synth seems to be pulling these dates okay:

![CleanShot 2024-09-06 at 10 39 46@2x](https://github.com/user-attachments/assets/e6fc3bcb-e0b3-475c-ba45-d2b0897f7193)

Is there a chance that you ran out of Synth credits?  Could you try re-syncing once more?

**Comment by osaroadade** [comment]
@zachgoll I no longer have this issue. I am not sure why it started showing up or why it stopped either.

**Comment by zachgoll** [comment]
@osaroadade no worries!  Feel free to comment on this issue if it ever happens again and I'll open it back up.
