### ISSUE TITLE
Bug: Option to disable register link on landing page

### ISSUE THREAD

**Issue by StamenchoBog** [maybe-finance/maybe#1140]
Hello,

**Description**
It would be nice to add an option in settings to disable the register link `...create an account` on the landing page. This will ensure there are no other account on our self-hosted website while it being public and will greatly improve the security of the budget app and make it usable only by ourselves.

**Expected behavior**
To be able to toggle `...create an account` on and off depending on the needs.

**Comment by MDrollette** [comment]
Just to point out - setting the environment variable `REQUIRE_INVITE_CODE=true` will prevent signups. It doesn't remove the link on the login page but it prevents anyone from creating an account without a code.

**Comment by StamenchoBog** [comment]
Thank you for pointing out @MDrollette, will set that up. But still I think that does not solve the issue of switching the register option off.
