### ISSUE TITLE
Bug: Can not select currency in New transaction dialog

### ISSUE THREAD

**Issue by tumapu** [maybe-finance/maybe#1150]
**Describe the bug**
The account is using Vietnamese Dong but I can not select Vietnamese Dong or any other currency than US Dollar.

**To Reproduce**
1. Go to any Vietnamese Dong Account under Investment section
2. Click on New transaction
3. Fill in required fields
4. Can't not select any currency than US Dollar at "Price per share" field 

**Expected behavior**
Default currency should be same as account currency. Vietnamese Dong in this case

**Screenshots / Recordings**
<img width="2045" alt="Screenshot 2024-09-05 at 09 54 00" src="https://github.com/user-attachments/assets/07cfcda0-3cf2-40a6-b15e-000a79f91324">

**Comment by zachgoll** [comment]
Hey @tumapu, this is because multi-currency is not yet supported for investment transactions, which will be implemented in #1087 fairly soon (likely by end of next week).  Going to close this out and use #1087 as the main issue for it.
