### ISSUE TITLE
Add setting to disable new user registration on self-hosted instances

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1152]
### Discussed in https://github.com/maybe-finance/maybe/discussions/785

<div type='discussions-op-text'>

<sup>Originally posted by **justinmayer** May 21, 2024</sup>
### Describe the feature

As an admin user, I would like to use the Maybe settings panel to disable new user registrations. This could be located under:

Settings > General > Self-Hosting > General Settings > Registration

Ideally, the setting would be a radio button with three options:

- Open registration
- Invitation code required
- Registration closed

### Why is this feature important?

Folks who are self-hosting create an account for themselves and perhaps also for family members, after which they may not want random people on the Internet to be able to create accounts on their personal/family instance. Adding a toggle to enable/disable new user registrations would allow for greater control over who can create user accounts on personal/family instances.

### Additional context, screenshots, and relevant links

While I am aware of the `REQUIRE_INVITE_CODE` environment variable, I am not aware of any way to (1) do this via the web interface or (2) disable new user registrations entirely.</div>

**Comment by zachgoll** [comment]
Internally, we will not be working on this issue for a while due to other priorities.

If anyone wants to tackle this, just comment below!

**Comment by tonyvince** [comment]
I can take this issue and  implement for next rlease

**Comment by zachgoll** [comment]
@tonyvince awesome!  We'll get more official designs created for this down the road, but for now, I think we could throw it somewhere in "Self Host Settings" with the rough logic below:

- Have a toggle switch, "Require invite for new signups"
- If toggle switch is checked, there should be a button close to it, "Generate invite token"
- Show a list of "unclaimed" invite tokens (tokens are automatically deleted once a user "claims" them) so that the user can see valid codes to send to friends/family they want to be able to sign up

Let me know if you have any questions or run into any issues with these requirements!
