### ISSUE TITLE
Bug: Incorrect "total value" every day in foreign-currency account

### ISSUE THREAD

**Issue by jakubkottnauer** [maybe-finance/maybe#1204]
**Describe the bug**
Every day when I open Maybe, the "total value" of my foreign-currency accounts is wrong. Triggering a manual account sync fixes the issue.

It seems like that the current total value is being converted to the primary currency but shown with the symbol of the account's currency - in the screenshot below, expected value is 107 EUR but instead I see 1213 EUR. My primary currency is SEK, at the moment `107 EUR = 1213 SEK`.

**To Reproduce**
1. Create a foreign currency account (e.g. EUR if your primary currency is USD) with a valuation of 10 EUR
2. Open Maybe the next day and observe that the "Total Value" of the account isn't 10 EUR (will probably be around 11.1 EUR)

**Screenshots / Recordings**
This is what the account looks like when I open Maybe for the first time (wrong):
<img width="915" alt="Screenshot 2024-09-23 at 17 01 02" src="https://github.com/user-attachments/assets/f2093295-4a09-4907-9880-f51e95c6e5ab">

And this what it looks like after running a sync (correct):
<img width="948" alt="Screenshot 2024-09-23 at 17 11 09" src="https://github.com/user-attachments/assets/17f90348-9e64-433b-a44c-609f7e93925d">

**Comment by zachgoll** [comment]
@jakubkottnauer the headline value that is incorrect is displaying `account.balance_money`, so the only way this could be wrong is if something _outside of_ the sync process (or in the auto-sync) is directly modifying it.

Are you saying that each day, this resets back to the incorrect value?

**Comment by jakubkottnauer** [comment]
> Are you saying that each day, this resets back to the incorrect value?
@zachgoll Exactly. I just opened Maybe for the first time today and was presented with the wrong value again:

<img width="312" alt="Screenshot 2024-09-24 at 17 14 15" src="https://github.com/user-attachments/assets/9938efaa-acf0-45c8-a585-3704fc7eb1a4">

**Comment by zachgoll** [comment]
@jakubkottnauer gotcha, thanks.  I will take a look at this.

**Comment by zachgoll** [comment]
@jakubkottnauer looked into this, and I've reproduced:

```
rake demo_data:empty
```

```rb
family = Family.first
family.update! currency: "SEK"
family.accounts.create! accountable: Depository.new, balance: 5000, currency: "EUR", name: "EUR Test"
account = Account.first
account.entries.account_valuations.create! date: 10.days.ago.to_date, amount: 5000, currency: "EUR", entryable: Account::Valuation.new
account.sync
account.balances.where(date: Date.current).destroy_all
account.sync(start_date: 1.day.ago.to_date)
```

Looks like the "partial sync" is grabbing the incorrect final balance.  Just wanted to share the repro.  Will get this fixed shortly.

**Comment by ttkjakub** [comment]
@zachgoll Sorry for the late reply, but I can confirm it all works as expected now. Thanks for the quick fix!
