### ISSUE TITLE
Bug: "Exchange rate provider missing" error despite account currency and general currency being identical (non USD)

### ISSUE THREAD

**Issue by Will1v** [maybe-finance/maybe#1229]
**Describe the bug**
When creating a non-USD account, even if the main currency is identical, you get a "Exchange rate provider missing" error message with the Troubleshooting button in red.

**To Reproduce**
1. Create a brokerage account and set a balance in GBP
2. Go to Profile|Settings|Preferences and in the General tab, set Currency to GBP

**Expected behavior**
Given the brokerage account's currency and the general settings currency are identical, there shouldn't be any need for exchanges rates to be necessary

**Screenshots / Recordings**

* General settings:
![image](https://github.com/user-attachments/assets/64d63d62-ccc5-4d23-be75-61908030a16e)

* Error message in main dashboard
![image](https://github.com/user-attachments/assets/10d3b8f7-2a4e-492d-b154-5485750c8dad)

**Additional context**
Self-hosted app

**Comment by zachgoll** [comment]
@Will1v just to confirm, does this account have any transactions yet?  If so, are any of those transactions in a currency other than GBP?

**Comment by Will1v** [comment]
It doesn't have any transaction, just a starting balance

**Comment by zachgoll** [comment]
@Will1v got it, I will take a look at this.  Based on what you've provided, I agree that you should not be getting this warning.

**Comment by Will1v** [comment]
@zachgoll I'm more than happy to try and take a look myself once I've got myself setup, if you'd like me to.
