### ISSUE TITLE
Bug: Signage convention reversal

### ISSUE THREAD

**Issue by marc22polo** [maybe-finance/maybe#1234]
**Describe the bug**
When importing a .csv if you choose signage convention "Incomes are positive" it imports negative lines as positive and positive lines as negative.

**To Reproduce**
1. Go to import transactions
2. Paste the .csv data
3. Configure, clean, map & confirm the import
4. Open "Dashboard" and navigate to "Recent transactions"

**Expected behavior**
If "Incomes are positive" is chosen I would expect that the negative lines are treated as expenses and positive as incomes

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/6d5e3c85-7d69-4833-b078-3550ebccb97d)
![image](https://github.com/user-attachments/assets/b24c17a3-8b91-4a3e-814e-0af6b8141fe3)
![image](https://github.com/user-attachments/assets/98e30256-7fe3-43a3-8afd-5e0de869e299)
![image](https://github.com/user-attachments/assets/b7b8cef4-f71b-4018-8918-caacc985ceb2)
![image](https://github.com/user-attachments/assets/e260f0f8-0515-4b69-adf1-7998bd930270)

**Comment by zachgoll** [comment]
@marc22polo thanks for the report!  This should be fixed in ~5 minutes.
