### ISSUE TITLE
Bug: Infinity percentage.

### ISSUE THREAD

**Issue by CarlosLugones** [maybe-finance/maybe#1241]
**Describe the bug**

Income, saving rate, and spending shows a "infinite" percentage, compared to previous month.

I just started using Maybe in the Umbrel OS, and maybe because there is no previous month, that's causing this bug.

**To Reproduce**

1. Start from 0 with a new Maybe instance.
2. Add some account.
3. Add a few transactions.
4. You will see "infinite%" up or down in the dashboard metrics. 

**Expected behavior**

Showing the real percentage, or none.

**Screenshots / Recordings**

![image](https://github.com/user-attachments/assets/1d4f1865-20e3-413f-b942-0dc46e8c3521)

![image](https://github.com/user-attachments/assets/d7d7ad92-9233-4f8c-b985-7e7318255f30)

**Comment by zachgoll** [comment]
@CarlosLugones that metric is comparing against the prior month, which was 0%.

An increase from 0 -> 0.33 would be an infinite increase, so I think this is expected behavior.  Once you have several months of data, you'll see a more meaningful metric here.

**Comment by CarlosLugones** [comment]
Infinity feels weird when speaking about money. I think that is confusing, but if you say that this is the expected behavior, okay. As a user, I found it confusing. @zachgoll

**Comment by zachgoll** [comment]
@CarlosLugones what would you display instead?  I'm happy to change it if we can come up with a more intuitive value to put here.  I just haven't been able to think of anything myself.

**Comment by CarlosLugones** [comment]
My recommendation would be to remove this, until you can showcase something.

If there is no previous month, don't show the "Infinity", neither "vs. last month".

It would be:
+0.33

I just asked a frontend expert and that was his recommendation also.

**Comment by jamie** [comment]
Other option is explicitly call out the missing data - "No data to compare from September" for instance.

**Comment by zachgoll** [comment]
@CarlosLugones makes sense to me, I think that's a reasonable solution.  @justinfar would you agree with showing nothing if infinity?

@jamie I think that option ends up getting a bit messy given our limited space here, but could work in other parts of the app.

**Comment by CarlosLugones** [comment]
Voting for not showing anything. Let the user discover this after 1 month.
