### ISSUE TITLE
Bug: Day transactions inferior to 1 are not subtracted in depository balance

### ISSUE THREAD

**Issue by Norin-Radd** [maybe-finance/maybe#1248]
**Describe the bug**
transactions amount of a specific day are not subtracted from the balance

**To Reproduce**
transaction amount of the day is less than 1 euro, it´s -0,64€, has can be seen on screenshots from day 22 to 23, the balance is the same.

**Expected behavior**
I would expect the amount referred would be subtracted from the current balance

**Screenshots / Recordings**
<img width="540" alt="image" src="https://github.com/user-attachments/assets/a5f674a2-c0c2-455f-b0b5-979a3567e3a9">
![image](https://github.com/user-attachments/assets/c6d8c964-671b-4325-b160-2fd8062db9d4)
![image](https://github.com/user-attachments/assets/6936b5ce-70a2-471a-a97c-fad9fef6e909)

**Additional context**
I am on latest commit, compose file was pulled and built today accordingly to maybe wiki instructions

**Comment by zachgoll** [comment]
@Norin-Radd what is the balance for Sep 24th?  Is is `0.64` less?

**Comment by Norin-Radd** [comment]
No, it was not subtracted, so it's 0.64€ more.

**Comment by zachgoll** [comment]
@Norin-Radd sorry, not sure I follow you here.  The graph you show indicates a _lower_ balance for Sep 24.  Can you confirm that these are the balances that you are seeing?

- Sep 22 is `140,97`
- Sep 23 is `140,97`
- Sep 24 is `140,33`

Our system currently reports _start of day balance_, so in this case, the start of day balance on Sep 23 was `140,97`.  During that day, `-0.64` flowed out of the account, which would make the _next day's start balance_ less at `140,33`.

If those are not the numbers you're seeing let me know.

**Comment by Norin-Radd** [comment]
Hello, 

I believe you might be wrong, the balance shown in the line graph of the present day is the balance of the previous day subtracted or added with the transaction of that present day.

<img width="529" alt="image" src="https://github.com/user-attachments/assets/60061fe8-7041-47f1-9827-f2238a1914bf">
![image](https://github.com/user-attachments/assets/f6d0d790-cbca-4650-842e-ed8bb66f9cee)
![image](https://github.com/user-attachments/assets/c39b5889-2184-467b-90a9-a225cb0b3bda)

I don´t have any transaction on day 22, or if I had I have changed the date to day 21 on the transaction.

<img width="566" alt="image" src="https://github.com/user-attachments/assets/3d5ba82c-3380-4904-8a11-61293fd83745">

<img width="353" alt="image" src="https://github.com/user-attachments/assets/dd6dc6d0-e791-4bdd-9a9f-f21f4ce742f5">

**Comment by zachgoll** [comment]
@Norin-Radd before we dig too far into this, would you mind hitting the "sync" button on this account so we can rule out any out-of-sync data here?

If we still have the error after that there may be a bug here.

**Comment by Norin-Radd** [comment]
I have pressed sync lots of times and I have even deleted and imported back the day 23 transactions.

**Comment by zachgoll** [comment]
@Norin-Radd got it.  This is a bit challenging for me to follow.  Would you mind providing me a table of your balances and transactions for the following dates: `Sep 22`, `Sep 23`, `Sep 24`

| Date | Expected Balance | Actual Balance | 
| --- | --- | --- | 

and 

| Date | Transaction amount |
| --- | --- |

**Comment by Norin-Radd** [comment]
Hello, my explanation was a real mess. I hope this makes it easy for you.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sbarb/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sbarb/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Date | Transaction   amount | Expected Balance | Actual Balance | transaction
-- | -- | -- | -- | --
21/10/2024 | -20 | 140.97 | 140.97 | exist
22/10/2024 | 0 | 140.97 | 140.97 | should not exist   (transaction date from day 22 changed after import to day 21)
23/10/2024 | -0.64 | 140.33 | 140.97 | exist
24/10/2024 | -116.18 | 24.15 | 24.79 | exist



</body>

</html>

**Comment by zachgoll** [comment]
@Norin-Radd thanks for the table!  This helps a lot.  Will take a look into this sync behavior.

**Comment by Norin-Radd** [comment]
> @Norin-Radd thanks for the table! This helps a lot. Will take a look into this sync behavior.

Any news on this?

**Comment by zachgoll** [comment]
@Norin-Radd I was not able to reproduce this when I looked into it.

That said, we've made lots of updates to the sync algorithm lately.  Would you mind upgrading, re-syncing the account, and confirming whether this issue still exists for you?
