### ISSUE TITLE
Bug:  Transfer action always have default currency USD

### ISSUE THREAD

**Issue by tmpt2** [maybe-finance/maybe#1250]
**Describe the bug**
My default currency is euro, and for income and expences, it appears euro by default. But on the transfer option, by default appears dollar. Looks like a visualization issue, because if I leave it as dollar, it creates the transfer as euro

**To Reproduce**
1. Change default currency to euro
2. Create a transaction and go to transfer
3. Check that dollar appear by default

**Expected behavior**
Euro to appear by default also on transfers

**Screenshots / Recordings**
![imagem](https://github.com/user-attachments/assets/ecd0e06c-dbe1-4aad-a242-2269619446fb)

**Additional context**
N/A

**Comment by zachgoll** [comment]
@tmpt2 thanks for raising this.  I agree, I believe this is a presentation issue because these transfers should be defaulting to the account's currency.
