### ISSUE TITLE
DatePicker.spec.tsx 'should be able to open modal and select a date' test failing because of faulty test setup.

### ISSUE THREAD

**Issue by karan0handa** [maybe-finance/maybe#126]
**Describe the bug**
Test failure. Probably something with the test setup because component works perfectly otherwise. This is the only test that fails in the `design-system` project.

**To Reproduce**

Run `yarn jest /libs/design-system/src/lib/DatePicker/DatePicker.spec.tsx`

**Expected behavior**
Test failure.

**Screenshots**
![image](https://github.com/maybe-finance/maybe/assets/79533543/9623fe51-8c59-4c81-a76e-3327da5479e6)

**Desktop (please complete the following information):**

-   OS: Ubuntu 22.04

**Comment by tmyracle** [comment]
This is resolved now with #127 👍, can close @Shpigford
