### ISSUE TITLE
Bug: savings rate percentage is missing % in comparison

### ISSUE THREAD

**Issue by gariasf** [maybe-finance/maybe#1266]
**Describe the bug**
On the savings rate card within the dashboard, I see the rate value without the %. Moreover, there is one account that's missing its name, although it has one. This is on the most recent commit at the time of writing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the dashboard.
3. Look at savings rate (with some data, so not the empty state)
4. See issues

**Expected behaviour**
I see the % symbol on the small, red rate value. 
All the accounts display their names.

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/64f0fae5-e99d-41fc-9fa7-0e080a745477)

**Additional context**

**Comment by zachgoll** [comment]
Hey @gariasf this is a fix that we pushed for #1241 

These accounts have a "negative infinity" percent change, so we omit them.

**Comment by gariasf** [comment]
Okay, I see. Could the design of the account pill be tweaked? I think it doesn't look right the way it is right now.

**Comment by zachgoll** [comment]
Yep! done.
