### ISSUE TITLE
Bug: Fee / Tax for stock transactions

### ISSUE THREAD

**Issue by LingkKang** [maybe-finance/maybe#1285]
**Describe the bug**

I'm not quite sure should this be a bug or a new feature, kinda like design issue.

**To Reproduce**

In some stock market, buying may have some **additional fees**.

Current logic, i.e., for buying, is simply that:

> the money spent = `quantity` * `price_per_share`

**Expected behavior**

The expected logic should be: 

> money spent = `quantity` * `price_per_share` + **`fees`**

This is probably also applicable to selling/withdraw, depending on the country and/or broker.

**Comment by gariasf** [comment]
I'd say this duplicates https://github.com/maybe-finance/maybe/issues/1237

**Comment by LingkKang** [comment]
> Hey @LingkKang, I think this duplicates #1237

Cool! @gariasf 

By the way, I'm not sure if buying & selling for brokerage account are implemented same as transfer. If so, please feel free to close this issue 🚀

**Comment by zachgoll** [comment]
Yep, we'll cover this in #1237 :)
