### ISSUE TITLE
Bug: Investment "deposit" and "withdrawal" transactions cannot be selected and deleted

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1287]
**Describe the bug**

![image](https://github.com/user-attachments/assets/ea76c371-7028-4a32-bd1a-b87bb8cfffe7)

**To Reproduce**
1. Create investment account
2. Add deposit/withdrawal
3. Try to select

**Expected behavior**

Should work the same as trade transactions

**Screenshots / Recordings**
If applicable, add screenshots or short video recordings to help show the bug in more detail.

https://github.com/user-attachments/assets/3761cd6e-ab61-422a-ba61-a0a02b59709f

**Comment by zachgoll** [comment]
Reopening—it appears that this is _only_ happening in production :/

**Comment by gariasf** [comment]
Could this be related to https://github.com/maybe-finance/maybe/issues/1295?

**Comment by zachgoll** [comment]
This has been fixed.  Was a Stimulus controller issue.
