### ISSUE TITLE
Bug: Category duplication on CSV imports

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1293]
Have had a few reports of CSV imports where the user selects an already-existent category, yet the import process still duplicates that category.

This is currently an unconfirmed bug, so we'll need to add some repro steps

**Comment by nicogaldamez** [comment]
I wasn't able to reproduce this. Any idea when this happens? @zachgoll

**Comment by zachgoll** [comment]
@nicogaldamez yeah I have not been successful at reproducing either.

**Comment by zachgoll** [comment]
Closing this out as I'm not able to repro under any scenario that I've tried locally.
