### ISSUE TITLE
General Yarn Install Failures and `yarn.lock` Issues on First Attempt on Ubuntu 22.04

### ISSUE THREAD

**Issue by SamuelFanawopo** [maybe-finance/maybe#130]
### Describe the bug
Running `yarn install` for the first time after cloning the repository results in installation failures. The errors range from generic "failed with errors" messages to specific issues like `@babel/runtime@npm:^7.20.13: No candidates found`. The resolution involved actions with the `yarn.lock` file, suggesting potential issues with outdated packages or dependencies that may no longer be available or compatible. This was specifically observed on Ubuntu 22.04 but could also affect other systems.

### To Reproduce
1. Clone the repository to a system running Ubuntu 22.04.
2. Run `yarn install` in the project directory.
3. Encounter an installation failure with errors, which may not explicitly mention `yarn.lock`.
4. The specific error for `@babel/runtime` suggests an issue with resolving the correct package version.
5. Delete the existing `yarn.lock` file.
6. Create a new, empty `yarn.lock` file.
7. Run `yarn install` again, which completes successfully after these steps.

### Expected behavior
`yarn install` should run without issues on the first attempt after cloning the repository, without needing to manipulate the `yarn.lock` file.

### Screenshots

![Screenshot from 2024-01-17 17-10-40](https://github.com/maybe-finance/maybe/assets/92785438/87add594-64c2-4ed5-9bd4-ba75c6811b87)

![Screenshot from 2024-01-17 17-10-53](https://github.com/maybe-finance/maybe/assets/92785438/4fd3fe54-75d9-421e-8ab3-9322f7476efc)

![Screenshot from 2024-01-17 17-11-01](https://github.com/maybe-finance/maybe/assets/92785438/c33dd4eb-4185-4ac0-bc77-141aedb103e8)

![Screenshot from 2024-01-17 17-11-19](https://github.com/maybe-finance/maybe/assets/92785438/7201041c-4f3b-44db-8745-841ae2291e11)

![Screenshot from 2024-01-17 17-11-29](https://github.com/maybe-finance/maybe/assets/92785438/5a6907ac-ed58-4276-adde-1473597f4803)

### Desktop:
- **OS:** Ubuntu
- **Version:** 22.04

### Additional context
This issue might not be isolated to Ubuntu 22.04 and could potentially affect other operating systems and development environments. The problem was encountered using Yarn version 4.0.2. To provide immediate assistance to other contributors who might encounter similar problems, I am willing to create a pull request to update the README with a set of temporary instructions. These instructions will guide developers on how to handle the `yarn.lock` file if they face similar errors, ensuring a smoother initial setup process until a more permanent solution is implemented.

**Comment by Greek** [comment]
Try using Yarn 1.22.21, I wouldn't rely on the latest version of Yarn yet for installs

**Comment by SamuelFanawopo** [comment]
Solved with [#87](https://github.com/maybe-finance/maybe/issues/87). Using Yarn 1.22.21 resolves these issues.
