### ISSUE TITLE
Bug: visible scrollbar on the alert component when there is no overflow

### ISSUE THREAD

**Issue by gariasf** [maybe-finance/maybe#1320]
**Describe the bug**
Visible scrollbar on alert component should not have a scrollbar.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have any holding with missing information
2. Go to the trading account view
4. See yellow alert with visible and disabled scrollbar.

**Expected behaviour**
The scrollbar is only visible when the content overflows.

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/abf53d8d-228c-4465-9ed6-38b8356af110)

**Comment by Shpigford** [comment]
Device and browser?

**Comment by gariasf** [comment]
> Device, OS and browser?

Google Chrome 129.0.6668.101
Windows 11

It does not happen on Firefox.

**Comment by gariasf** [comment]
![image](https://github.com/user-attachments/assets/8c6045bf-d8ab-4b01-838a-b63104703c42)
Moving the overflow prop to auto should fix this.

**Comment by Shpigford** [comment]
@gariasf Just pushed a potential fix.
