### ISSUE TITLE
Bug: can't edit existing trade transaction

### ISSUE THREAD

**Issue by gariasf** [maybe-finance/maybe#1321]
**Describe the bug**
After having created a trade and waited for it to sync, I click on the transaction name, and it doesn't open the edit drawer.

**To Reproduce**
1. Go to any investment account overview
2. Click on "Transactions"
3. Click on a transaction name to start editing it
4. See issue

**Expected behavior**
I click on the transaction and I see the edit drawer

**What version of Maybe are you using?**
Hosted.

**Screenshots / Recordings**
Console output:
<img width="366" alt="image" src="https://github.com/user-attachments/assets/537eec95-8d79-42e0-9fb0-88ba9c062fc7">
What I see:
<img width="1061" alt="image2" src="https://github.com/user-attachments/assets/8bb2d276-76f3-4b2c-a9bc-6fda03d39bba">

**Comment by gariasf** [comment]
I also have to say that my account is configured as EUR. I am not sure if that affects this case.

**Comment by Shpigford** [comment]
To clarify, if you go to the "Holdings" tab and click on the holding (presumably XAU), does THAT side drawer open?

**Comment by gariasf** [comment]
Yes, that works 👍🏻 It's only the transaction drawer that is not working.

**Comment by Shpigford** [comment]
@gariasf Perfect. Just pushed a fix. Let me know if that does the trick.

**Comment by gariasf** [comment]
Seems to work now. Thank you!
