### ISSUE TITLE
Bug: Net worth not calculated correctly after (CSV) accounts import

### ISSUE THREAD

**Issue by gboudreau** [maybe-finance/maybe#1329]
**Describe the bug**
I imported accounts with balances yesterday (from CSV). I didn't import transactions yet.  
I went back to Maybe today, and it reports that my net worth changed vs yesterday, but it didn't.

**To Reproduce**
1. Import accounts from CSV
2. Do NOT go into Settings > Accounts, to edit the accounts and set a `value tracking mode`, eg. Balance
3. Wait for the next day
4. Re-open Maybe

**Expected behavior**
Net work should not change, because balances didn't change.

**What version of Maybe are you using?**
Self-hosted. v0.1.0

**What operating system and browser are you using?**
Docker

**Screenshots / Recordings**
<img width="1102" alt="image" src="https://github.com/user-attachments/assets/34244a8e-3169-4f71-9ffc-d9278c50c7af">

**Additional context**
Looking into `account_balances` table, if I order by `account_id`, I see that not all accounts have rows for yesterday, but they all have rows for today, with a timestamp of when I reopened Maybe, which I guess triggered an account sync?

I found 12 accounts that are in `account_balances` for today, but have no rows for yesterday. Those are all the accounts for which I did NOT select a `value tracking mode` manually, in the Settings > Accounts page yesterday. I only did so for some, but not all accounts, which I guess is what caused this issue.  
I would think that importing would guide me through all the necessary steps, so if choosing a `value tracking mode` is required, it should ask me to do it (or do it for me).

**Comment by zachgoll** [comment]
@gboudreau thanks for the detailed report.

I agree this is confusing.  I'll take a look and see what's going on here.  I'm guessing we're not properly adding the "start" balance tracking value on those account imports properly, which makes it so there is no "reference" point to sync from (hence why these are missing balances yesterday).

**Comment by zachgoll** [comment]
Should be fixed in #1357

**NOTE** - this will _not_ fix existing accounts.  To fix those:

1. Go to account
2. Hit "edit" in menu
3. Select "balance" mode
4. Save
5. Add at least 1 value in your account so that there is a "reference" point for our system to sync from
6. (optionally) switch back to transactions mode
