### ISSUE TITLE
Can not go to login page

### ISSUE THREAD

**Issue by nguyenvanvy1999** [maybe-finance/maybe#133]
**Describe the bug**
I was setup it step by step. And this app was started successfully. But when I open website, and press button "Admin login", it open an white page with error "Cannot GET /admin/login"

**To Reproduce**
- Install step by step with guideline
- Open website
- Press button "Admin login"
**Expected behavior**

**Screenshots**
![image](https://github.com/maybe-finance/maybe/assets/61955009/da3ed417-5002-4241-9d01-76ea2605fee3)

![image](https://github.com/maybe-finance/maybe/assets/61955009/18bdf6d1-295b-4c23-996a-05e8dcea77d1)

![Screenshot 2024-01-18 at 11 19 07](https://github.com/maybe-finance/maybe/assets/61955009/956d104a-a4a1-44e0-9524-1e23ff9c9c66)

**Desktop (please complete the following information):**

-   OS: MacOS 13.1
-   Browser Microsoft Edge, Safari

**Comment by tmyracle** [comment]
looks like you're hitting the server port/url, try localhost:4200 for the client entry point

**Comment by nguyenvanvy1999** [comment]
@tmyracle Oh. Sorry my bad. I was go to localhost:4200 and I see login page.
But I still have a issue that I can not onboard, with this error:
![image](https://github.com/maybe-finance/maybe/assets/61955009/29384ba3-2146-4fa6-be1c-c8b75409ae9e)

![Screenshot 2024-01-18 at 13 03 00](https://github.com/maybe-finance/maybe/assets/61955009/88723490-e05b-41f7-be65-b8d498a96c2b)

I using NodeJS version 20.9.0
