### ISSUE TITLE
Bug: Currency mismatch when transferring between two different currency accounts

### ISSUE THREAD

**Issue by user268704** [maybe-finance/maybe#1331]
**Describe the bug**
When transferring from a crypto account in a currency (usd) to another currency (rub) on a deposit account, the amount in the creation card is specified in the currency of the crypto account and then in the currency of the deposit account

**To Reproduce**
1. Create a deposit account in the currency of Russian rubles (rub)
2. Replenish it for any amount
3. Create a crypto account in usd
4. Create a transfer from deposit to crypto
5. Fill in all fields in the transfer
6. In the transaction history of the crypto account indicate rub (rubles)

**Expected behavior**
In the history of the crypto account in the transfers should be in dollars, in the deposit account rubles transfer in rubles.

**What version of Maybe are you using?**
Self-hosted version 0.1.0 is used

**What operating system and browser are you using?**
Windows operating system
Browser vivaldi (chromium)

**Comment by zachgoll** [comment]
This is also related to #1237 since I'd assume that multi-currency transfers _could_ potentially involve a fee by the institution that is facilitating the multi-currency transfer
