### ISSUE TITLE
Bug: Category duplication upon multiple clicks

### ISSUE THREAD

**Issue by EricRasputin** [maybe-finance/maybe#1350]
**Describe the bug**
When you create a category and click on the create button multiple times before the page refreshes, it duplicates the category for the amount of times you click it. 

**To Reproduce**
1. Click on create a new category
2. Enter a name and click on the Create button multiple times
3. Wait for the page to refresh to see the duplication

**Expected behavior**
The expected behavior is that maybe should not register the duplicate clicks which allow for the category to be duplicated. 

**What version of Maybe are you using?**
Hosted. 

**What operating system and browser are you using?**
MacOS 15 Version 15.1 Beta (24B5009l)

**Comment by zachgoll** [comment]
@EricRasputin thanks for the report, will get it fixed!

**Comment by zachgoll** [comment]
Fixed via #1357
