### ISSUE TITLE
Bug: Cannot select German-Swiss (Only French-Swiss or Italian-Swiss) as Language

### ISSUE THREAD

**Issue by Gensokian** [maybe-finance/maybe#1361]
**Describe the bug**
When initializing Maybe i was only able to select french-swiss or italian-swiss. But sadly I speak neither of those; only german-swiss

**To Reproduce**
1. Initial Login
2. Create Account
3. Try to select Language German Swiss (de-CH)

**Expected behavior**
Swissgerman is selectable

**What version of Maybe are you using?**
Self-Hosted:latest

**What operating system and browser are you using?**
Arch Linux - Vivaldi Browser

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/60bb3e47-6d50-4b08-95ae-21f2007d7204)
![image](https://github.com/user-attachments/assets/7bcbe54c-54c9-4a63-bfc8-f8d9eb688d74)
![image](https://github.com/user-attachments/assets/6cabb416-c0ee-4cb3-9331-7c246be214b4)
![image](https://github.com/user-attachments/assets/ad6183dd-ac5d-413b-a58f-649bfd06a2a3)

**Additional context**
Funnily enough I can also select german german... in case I want that extra German lol

**Comment by Gensokian** [comment]
That would work technically.
But Swiss (de-CH) has different currency layouts

For example in Germany Ten Thousand is "10.000,00"
Whereas in Swiss-German its "10'000.00"

Also since Switzerland is multilingual; de-CH, fr-CH and it-CH this happens also for French, Italian and obviously the German version

**Comment by zachgoll** [comment]
@Gensokian `de-CH` has been added.
