### ISSUE TITLE
Bug: Sidebar only displays cash balance for investment accounts, not full value

### ISSUE THREAD

**Issue by ahatzz11** [maybe-finance/maybe#1369]
**Describe the bug**
The balance on the sidebar doesn't match the actual balance

**To Reproduce**
1. Go to the dashboard
2. See some accounts that don't show the proper balance on the sidebar

Unfortunately I don't know how it got like this, but happy to help debug if needed.

**Expected behavior**
I expect the sidebar balance to show the actual balance.

**What version of Maybe are you using?**
Hosted

**What operating system and browser are you using?**
MacOS 14, Chrome 130

**Screenshots / Recordings**
<img width="987" alt="image" src="https://github.com/user-attachments/assets/9433da13-5015-4cc9-99dc-91bcf15ed4a1">

**Comment by zachgoll** [comment]
@ahatzz11 what is the cash value for this account showing?  That sidebar may only be showing cash balance, which would definitely be a bug.

**Comment by ahatzz11** [comment]
@zachgoll Yes the cash balance is $0. I tried to prove this out and I think I hit another bug. I've mentioned this on another thread we've had but it seems like almost every time I do a transaction it doesn't quite do what I expect. Let me know if I can troubleshoot any further here!

1. I added a deposit of $5 for today.
2. Cash balance shows $0 still
3. Sidebar shows $0.

<img width="854" alt="image" src="https://github.com/user-attachments/assets/9bb24186-f045-47e0-b40d-9d1810f29302">

<img width="867" alt="image" src="https://github.com/user-attachments/assets/3ad0e9f7-4cad-4a04-a904-8826d3d0f2fa">

**Comment by mannish-kumar** [comment]
Even the Assets and Net Worth Balance doesn't update when a transcation is added. Do I need to log a seperate bug?

**Comment by zachgoll** [comment]
@ahatzz11 thanks, this is definitely a "cash balance" related bug where we're only showing cash balance in the sidebar. 

@mannish-kumar I believe this should be fixed now, but if you find otherwise, please open a separate issue.

**Comment by zachgoll** [comment]
Fixed via #1526
