### ISSUE TITLE
Replace Postmark with a generic SMTP provider

### ISSUE THREAD

**Issue by 6ixfalls** [maybe-finance/maybe#137]
**Is your request related to a problem? Please describe.**
Maybe relies on the Postmark API, a proprietary email sending service. Ideally, Maybe should support all kinds of mail providers, which can be easily done through SMTP, rather than forcing users to lock into Postmark.

**Describe the solution you'd like**
Postmark can either be replaced by an SMTP sender, or an option can be added to either send with Postmark or send through SMTP. Replacing Postmark with an SMTP sender should be the most useful, as Postmark also has SMTP relays/servers that can be used to send mail, removing the need to maintain two separate mail systems.

**Comment by Shpigford** [comment]
Approved on our end. Reducing explicit third-party dependencies is definitely always a goal.

**Comment by tmyracle** [comment]
Closed by #230
