### ISSUE TITLE
Bug: Page refresh while bulk categorization

### ISSUE THREAD

**Issue by EricRasputin** [maybe-finance/maybe#1371]
**Describe the bug**
When I'm on the second page of the transactions list and I bulk categorize some transactions, once the screen refreshes, I am taken back to the first page. 

**Expected behavior**
I am supposed to stay in the same page and not be refreshed to the first page. 

**What version of Maybe are you using?**
Hosted

**What operating system and browser are you using?**
MacOS15 Version 15.1 Beta (24B5009l)

**Comment by zachgoll** [comment]
This is fixed now
