### ISSUE TITLE
Bug: Edited transactions on the home page get a checkbox

### ISSUE THREAD

**Issue by ahatzz11** [maybe-finance/maybe#1386]
**Describe the bug**
On the home page there is a list of recent transactions. None of these transactions have a checkbox. If a transaction is edited it then gets a checkbox, which doesn't have any options once selected

**To Reproduce**
1. Have a few transactions
2. Go to the home page - https://app.maybe.co/
3. Edit a transaction directly on this page by clicking on it (sidebar edit comes up)
4. See checkbox on that edited transaction

**Expected behavior**
I would expect consistency in one of two ways:
- All transactions have a checkbox (assuming there is an action you can take from this page, which doesn't seem to be the case currently)
- No transactions have a checkbox, even after an edit.

**What version of Maybe are you using?**
Hosted

**What operating system and browser are you using?**
Chrome 130, MacOS 14

**Screenshots / Recordings**
<p>
<img height="200" alt="image" src="https://github.com/user-attachments/assets/73fb2b1a-e006-44b6-ae48-8374b69e2254">
<img height="200" alt="image" src="https://github.com/user-attachments/assets/7f1560ed-2bc6-44be-8b0d-cf6cdff54212">
<img height="200" alt="image" src="https://github.com/user-attachments/assets/e428ac8e-98b5-4a94-a1b2-1bec3b628167">
</p>

**Additional context**

**Comment by zachgoll** [comment]
This is due to the Turbo stream which replaces the row after the update:

https://github.com/maybe-finance/maybe/blob/e5eb69bdc76d8da8399c123c4a4866ee936652b0/app/controllers/account/transactions_controller.rb#L19
