### ISSUE TITLE
[Security] Responsible Disclosure

### ISSUE THREAD

**Issue by RootUp** [maybe-finance/maybe#1400]
Hey there, I reported a security issue through GH "GHSA-fprq-3m4c-vf28" but unable to get any feedback so far. Do any one know a better way to reach out to dev?

Thanks,

**Comment by gariasf** [comment]
Hey @RootUp, have you tried via [Discord](https://link.maybe.co/discord)?

**Comment by RootUp** [comment]
Thanks, yes I tried but let me put the message in some channel.

**Comment by zachgoll** [comment]
@RootUp thanks for the heads up. I see it and we'll take a look.
