### ISSUE TITLE
Bug: Investment transaction in USD only

### ISSUE THREAD

**Issue by Aohzan** [maybe-finance/maybe#1413]
**Describe the bug**
When I want to add a transaction, I can't change the currency, it's forced to USD despite EUR is set in my settings. So when I add a transaction there is a mismatch between the current value from Synth, in the following example I bought à 149.15€ and now it's 165, but

![image](https://github.com/user-attachments/assets/a9bdc0e3-17ed-4416-a42d-c38e67c55191)

**To Reproduce**
1. Set EUR on global currency
2. Add a buy for a european stock (Euronext) and put the price in EUR

**Expected behavior**
Choose the currency of the transaction and/or account must used the global currency

Thank you

**Comment by zachgoll** [comment]
This will be covered in #1087
