### ISSUE TITLE
Bug: Deleting a balance update doesn't remove the balance update

### ISSUE THREAD

**Issue by ahatzz11** [maybe-finance/maybe#1416]
**Describe the bug**
If a balance update is added and then deleted, the account keeps the deleted balance update

**To Reproduce**
1. Make an account with $0 starting balance
2. Update todays balance update to $1
3. Delete todays balance update
4. Notice account stays at $1 balance

**Expected behavior**
If I delete a balance update I would expect the removal of that balance update to be reflected.

**What version of Maybe are you using?**
Hosted

**What operating system and browser are you using?**
MacOS 14, Chrome 140

**Screenshots / Recordings**

![CleanShot-000170 2024-11-04 at 21 48 13](https://github.com/user-attachments/assets/8e2bf194-e145-44e6-a67d-87c80695d1af)

**Comment by zachgoll** [comment]
This happens because we're failing to re-sync the account directly after the deletion.

Hitting sync will fix this in the meantime.
