### ISSUE TITLE
Bug: When balance and transaction exist on same day, balances not correctly calculated

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1418]
**Describe the bug**

There are two things worth fixing here:

1. The balance calculation should result in `$100` 
2. The "balance update" should be based on the trend vs. _previous balance_ ($100), and should be downward.  Currently, it is an "upward" trend because we're comparing it against the previous known balance of $0.

![CleanShot 2024-11-05 at 10 35 26](https://github.com/user-attachments/assets/7fd5bfbb-00d7-4f97-b138-b431af347156)

**Comment by mikr13** [comment]
Also why do we have to do a balance update manually? Shouldn't balance be calculated based on transactions/incomes in a day?

**Comment by mikr13** [comment]
Yeah, that's fair. But what I noticed is that the transactions marked as expenses don't decrease the total balance in that account. Only when balance update is done then the account's balance changes.
