### ISSUE TITLE
Bug: Account chart trend does not recalculate when period selection changes

### ISSUE THREAD

**Issue by SrGato001** [maybe-finance/maybe#1420]
**Describe the bug**
I have added a few transactions, if I click on the three dots and change the view from the default "1M" to "All" it says: "+€232.75 (-100.0%) since account creation" but the balance shows as 0

**To Reproduce**
Just added transactions, my account type is transactional

**Expected behavior**
To show that my balance in that account is 232.75€

**What version of Maybe are you using?**
I am suing hosted version of Maybe

**What operating system and browser are you using?**
Zed based in Firefox

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/71318ec8-7feb-45d8-9c94-990a9699a453)

**Additional context**
No additional contexted needed

**Comment by zachgoll** [comment]
@SrGato001 are you running the latest version of the app?  We just pushed some HUGE changes to this view.

**Comment by zachgoll** [comment]
@SrGato001 could you provide the "Activity View" list?

If you're not comfortable sharing those numbers, please use the Intercom chat widget to privately share so we can help you out.

**Comment by zachgoll** [comment]
@SrGato001 actually, no worries on that.  I was able to reproduce this on my account and know what's going on.

The chart is not respecting the "period" dropdown value.  Will get this fixed.

**Comment by SrGato001** [comment]
Hey I can still provide you with the a screenshot. But my problem isn't the chart / graph. But more the total balance, it says Balance €0.00

**Comment by zachgoll** [comment]
@SrGato001 can you hit "Sync" and then let me know if you still have the issue? 

In order to diagnose this, I will need to see all the transactions and balances you have entered for this account (or at least the most recent ones)

**Comment by SrGato001** [comment]
Hey, I already tried the Sync button, stil didn't work. I would love to send you a screenshot but I got logged off and I can't remember my password. And the password reset service seems down? I tried doing it never got a email to reset it.

**Comment by zachgoll** [comment]
@SrGato001 we have pushed several changes that I believe should fix all of this for you.  Password resets should be working as well.  Happy to re-open if you still experience issues.

**Comment by SrGato001** [comment]
@zachgoll Hey the problem seems to continue, my balance shows as €0.00, Do you need a log of my transactions?

**Comment by SrGato001** [comment]
@zachgoll Now I added a transaction and shows as negative
![image](https://github.com/user-attachments/assets/73641f1a-16fd-47c7-a40c-7dd67b4e9e5e)

**Comment by zachgoll** [comment]
@SrGato001 based on your screenshot, the total balance appears to be working correctly.  You added a "Balance update" of €0 on Nov 4 which would set your balance to €0.  Then, you added an expense transaction of -€9.76 which would subtract from 0, leading to your final -€9.76 balance for today.

That said, the "trend" does appear to be off in the sense that it should have the same signage for both the number and the percentage.

**Comment by zachgoll** [comment]
@SrGato001 are you running the latest version?  I recently pushed an update that fixed an issue where deleting a balance update was not properly re-syncing the account.

Can you re-sync the account and let me know if the issue still persists here?

**Comment by SrGato001** [comment]
I am using the hosted version (not the self-host) and I did click on re-sync

**Comment by SrGato001** [comment]
I am using the hosted version (not the self-host) and I did click on re-sync (Should balance update with the current balance of the transacction time?)
![image](https://github.com/user-attachments/assets/d1dc50e2-3af1-4c34-9d07-72b36bc1f3a8)

**Comment by SrGato001** [comment]
I am using the hosted version (not the self-host) and I did click on re-sync (Should balance update with the current balance of the transacction time?)
![image](https://github.com/user-attachments/assets/d1dc50e2-3af1-4c34-9d07-72b36bc1f3a8)

**Comment by zachgoll** [comment]
@SrGato001 this result still makes sense to me based on the screenshot you've shared.  What value are you expecting?  Can you provide a more complete ledger of balances and transactions?  That is the only way to determine if this is a bug.

**Comment by SrGato001** [comment]
Maybe my way of thinking might be different on the one degsigned. But my balance should show the total ammount of money I have in that bank account. Here are all the transactions:
![image](https://github.com/user-attachments/assets/1e7f321b-a3f9-4ecd-97a1-bbddd770806b)
![image](https://github.com/user-attachments/assets/04fc5190-ff5a-407b-a6b7-51fdc56d3f3a)
![image](https://github.com/user-attachments/assets/ec854eaa-fa5b-4942-a010-54a69afc9add)

**Comment by zachgoll** [comment]
@SrGato001 everything appears to be calculating correctly here.

To fix this, you should add a "Balance update" for today that is exactly equal to your actual bank account balance.  Moving forward, things will reference this value and stay up-to-date.
