### ISSUE TITLE
Bug: Account names are not truncated properly

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#1422]
**Describe the bug**

![CleanShot 2024-11-05 at 12 38 32](https://github.com/user-attachments/assets/75d1890b-6739-4204-acfc-e65f8f3fb3f2)

**Comment by zachgoll** [comment]
@justinfar how should this look?

**Comment by zachgoll** [comment]
Also should be truncated in the transactions view:

![CleanShot 2024-11-05 at 19 23 08](https://github.com/user-attachments/assets/926b78c7-22bd-44d6-86d5-e929b17a221b)

**Comment by justinfar** [comment]
@zachgoll here's how truncation should look in both the sidebar and transactions view

![CleanShot 2024-11-07 at 16 13 03](https://github.com/user-attachments/assets/20d90c0a-87cc-4632-bd81-34032edb3a7d)

![CleanShot 2024-11-07 at 16 13 42](https://github.com/user-attachments/assets/dc4f886c-9b0a-4b93-83aa-01168219cc10)
