### ISSUE TITLE
Bug: Switching to Chinese does not work

### ISSUE THREAD

**Issue by xrcq** [maybe-finance/maybe#1428]
Switching the language on the settings page doesn't work
 
![微信图片_20241107182059](https://github.com/user-attachments/assets/89de0518-297a-4726-b4af-c6ea1df1edad)

**Comment by xrcq** [comment]
My version is v0.2.0-alpha

**Comment by gariasf** [comment]
Hey there @xrcq , internationalisation is still not supported. See https://github.com/maybe-finance/maybe/issues/1225 for reference.

**Comment by Shpigford** [comment]
Hi @xrcq, @gariasf is correct. We don't currently have language translations implemented. It is planned, though.
