### ISSUE TITLE
Bug: Currency identifier doesn't change for Transfer transactions based upon `From` account's currency

### ISSUE THREAD

**Issue by followingell** [maybe-finance/maybe#1429]
**Describe the bug**
The currency identifier for the `Amount` value in the New transfer section is always `$` and doesn't change depending on the `From` account.

**To Reproduce**
1. Go to `New transaction`.
2. Click `Transfer`.
3. Swap the `From` _(or `To` account(s))_ to non-dollar account(s).

**Expected behavior**
I would expect the currency identifier to swap to the currency of the `From` account since you are transferring a set amount of money from this account to the `To` account (regardless of the `To` account's currency).

**What version of Maybe are you using?**
- Self-hosted
- Version: `v0.2.0-alpha.1`

**What operating system and browser are you using?**
- OS: macOS Sonoma `14.6.1`
- Browser: Safari `Version 18.0`

**Screenshots / Recordings**
![Screenshot 2024-11-07 at 11 23 13](https://github.com/user-attachments/assets/4ca65de1-af7e-4997-a752-6c7141d28124)

**Additional context**
N/A.

**Comment by jestinjoshi** [comment]
This is similar to #1426

**Comment by zachgoll** [comment]
#1331 was mistakenly closed, so reposting my reply from that to here, which is my proposed solution to this (there's a bit more involved than just defaulting the initial currency):

https://github.com/maybe-finance/maybe/issues/1331#issuecomment-2430055130
