### ISSUE TITLE
Bug: Onboarding fails if you don’t provide a Household name

### ISSUE THREAD

**Issue by yeskunall** [maybe-finance/maybe#1442]
**Describe the bug**
Maybe front-end crashes with a 500 Internal Server Error if you don’t provide a Household name during onboarding.

**To Reproduce**
1. Start the onboarding process
2. Proceed with onboarding without passing a household name
4. You get the generic RoR 500 Internal Server Error page on the front-end

**Expected behavior**
To _not_ complete the onboarding without a household name if it is mandatory for initial setup, or for the app to _not_ crash if I proceed the onboarding without providing a household name.

**What version of Maybe are you using?**
Self-hosted (v0.2.0-alpha.2)

**What operating system and browser are you using?**
Brave Browser on macOS 13.6.9

**Screenshots / Recordings**

<img width="1439" alt="CleanShot 2024-11-09 at 13 17 17@2x" src="https://github.com/user-attachments/assets/6741b11e-8c81-4a39-ab48-d0b36ae9e25e">

**Additional context**

N/A

---
Thanks for working on Maybe. The RoR rewrite is snappy so far! 💖

**Comment by zachgoll** [comment]
@yeskunall can you share the exact values that you filled out for all these fields?  I'm not able to reproduce what you're seeing so I'm wondering if it's a _different_ field causing this:

https://github.com/user-attachments/assets/ae60433a-1e5d-4689-98d0-5b8f2b3a8d87

**Comment by yeskunall** [comment]
Hey, @zachgoll; I didn’t want to leave you hanging. Just deployed the same version to Fly.io and didn’t run into this issue. The previous installation was on Elest.io and was handled by them. I didn’t record my session as you did so can’t remember 

Thanks for jumping on this so quick!

**Comment by zachgoll** [comment]
@yeskunall great, glad it's working!
