### ISSUE TITLE
Bug: Transactions imported to foreign-currency accounts have incorrect currency

### ISSUE THREAD

**Issue by jakubkottnauer** [maybe-finance/maybe#1446]
**Describe the bug**
Transactions that are imported into a foreign-currency account (= currency different from the family's primary currency) end up having the primary currency instead of the account's currency.

**To Reproduce**
1. Import the CSV below into a foreign-currency account (for example an EUR account if your primary currency is USD)
2. Observe that the imported transaction has USD currency instead of EUR

```
Date,Amount
11/10/2024,100
```

**Expected behavior**
The imported transaction should be in the currency of the account, unless a different currency was specified in the CSV itself.

**What version of Maybe are you using?**
Self-hosted v0.2.0-alpha.2

**Comment by zachgoll** [comment]
@jakubkottnauer we still have a bit of work to do around this, but there is a `Currency` column in the transaction import where you can specify this.  It defaults to `USD` right now, which should instead default to the family currency:

https://github.com/user-attachments/assets/d9530c5f-ccb1-4223-a383-646614edfbd5
