### ISSUE TITLE
Bug: Transaction search becomes a dead end if there are no results, and unable to search for initial balance?

### ISSUE THREAD

**Issue by ahatzz11** [maybe-finance/maybe#1449]
**Describe the bug**
When you search your transactions and search for something that matches nothing, you hit a dead end that requires a page sync because the search bar goes away.

I also noticed that it doesn't seem to search for my "Initial balance" transaction, which is a bit weird.

**To Reproduce**
1. Go to an account with transactions
2. Search for something that returns 0 results
3. Get stuck
4. Refresh page

**Expected behavior**
I would expect the search bar to stay and let me delete my search to get my transaction back. A `clear` button would also be great for a search bar. 

**What version of Maybe are you using?**
Hosted

**What operating system and browser are you using?**
MacOS 14, Chrome 130

**Screenshots / Recordings**

https://github.com/user-attachments/assets/f8e5c687-e082-4463-a655-8e46b9da3902

**Comment by zachgoll** [comment]
@ahatzz11 fixed.

The "Initial balance" search is also fixed in newer versions, but since you created this account before it was fixed it won't work for your account.  You just need to update the "name" of that balance to "Initial Balance" as it is empty in the DB.
