### ISSUE TITLE
Bug: Loan graph shows Red when balance goes down, even though the % decrease vs previous month is green (as expected)

### ISSUE THREAD

**Issue by evanrich** [maybe-finance/maybe#1459]
**Describe the bug**
When you have a loan, say a home loan,the graph shows red when the balance decreases, despite the dollar and percentage staying green:

**To Reproduce**
1. add a loan, with balance, interest rate, and term
2. update the balance
3. the graph shows green but the tooltip shows red

**Expected behavior**
all numbers are green since a decreasing loan balance is a good thing

**What version of Maybe are you using?**
0.2.0-alpha.2

**What operating system and browser are you using?**
Windows 11, Chrome (latest version)

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/1055ce93-5a36-4465-ac57-cf98e5d1f165)
![image](https://github.com/user-attachments/assets/b1df4dcd-6ab9-49b4-8eae-16f3848f9f08)

**Comment by zachgoll** [comment]
This function needs to consider the classification (`asset` / `liability`) of the account:

https://github.com/maybe-finance/maybe/blob/3bc9da4105d9463d8a76020a9e0d916c87b422ee/app/javascript/controllers/time_series_chart_controller.js#L405-L411

Our server-side code already does this, but the Stimulus controller does not.

Ideally we'd only have to handle this in one spot (server-side), but it may be more pragmatic to just duplicate the logic in this case.  I haven't really dug in too much yet to tell.

**Comment by zachgoll** [comment]
Fixed via 743e291
