### ISSUE TITLE
CSV not importable

### ISSUE THREAD

**Issue by RMStyle** [maybe-finance/maybe#1462]
**Describe the bug**
I have csv from my bank. I modified it to fit to the requirements of import. When I try to import it fails,

**To Reproduce**
1. Go 'Import'
2. Click on 'Import Transactions'
3. Click on 'Upload csv'
4. Choose attached file
5. Choose 'Semicolon' at Dropdown
6. Click on 'Upload csv'
7. See error

**Expected behavior**
Data should correctly be importetd

**What version of Maybe are you using?**
Selfhosted Version: v0.2.0-alpha.2

**What operating system and browser are you using?**
Fedora 41;  Firefox;

[testdata_maybe.csv](https://github.com/user-attachments/files/17758761/testdata_maybe.csv)

**Comment by acflint** [comment]
I've opened a PR to fix this: https://github.com/maybe-finance/maybe/pull/1468
