### ISSUE TITLE
Abstract data provider away from Transactions table

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#150]
We're undertaking a large project to abstract data providers away from tables as we're working towards support for dozens/hundreds of data providers globally.

Relevant columns:
* `teller_category`
* `teller_transaction_id`
* `teller_type`

**Comment by mattgillooly** [comment]
I see several issues that look similar to this: #147, #148, #149.  Is the idea that these would initially all be refactored to use the same `TellerDataProvider`, or would `Account`, `AccountConnection`, `Transaction` and `User` each have a type-specific data provider that spoke to Teller?  e.g. `Teller::TransactionDataProvider`, etc.
