### ISSUE TITLE
Bug: Action Cable does not work with custom self hosted domains via reverse proxy

### ISSUE THREAD

**Issue by EsdrubalMagano** [maybe-finance/maybe#1505]
**Describe the bug**
When adding a new account I get the following error:
![image](https://github.com/user-attachments/assets/8d7a3d54-c40d-4c00-bd94-7682a334b74a)
In console I see the following error:
![image](https://github.com/user-attachments/assets/4456c311-0010-4a5f-9c4f-b335a1c52116)

**To Reproduce**
1. Go to 'https://maybe.example.com/accounts/new
2. Click on 'add new investment/bank/etc'
3. See error

**Expected behavior**

**What version of Maybe are you using?**
Self-hosted Version: v0.2.0-alpha.2 using docker

**What operating system and browser are you using?**
Windows 11 and Brave

**Screenshots / Recordings**

**Additional context**
I already tried to rebuild the docker container, no luck, also tried to disable Brave Adblocker.

**Comment by zachgoll** [comment]
@EsdrubalMagano looking into this a bit further, this may actually be something we could set via ENV vars so that custom domains work properly:

```rb
config.action_cable.allowed_request_origins = ["https://maybe.example.com"]
```

Reopening and renaming the issue so we can get some more eyes on it.

**Comment by hibate** [comment]
It works for me:

```
upstream maybe {
    server 172.17.0.1:3000 max_fails=2;
}

server {
    listen       80;
    server_name  maybe.example.com;

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

    location / {
        proxy_pass http://maybe;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

        proxy_connect_timeout 60s;
        proxy_read_timeout    90s;
        proxy_send_timeout    60s;
    }

    location /cable {
        proxy_pass http://maybe/cable;
        proxy_set_header   Host             $host;
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header   Upgrade          $http_upgrade;
        proxy_set_header   Connection       'Upgrade';

        proxy_connect_timeout 60s;
        proxy_read_timeout    90s;
        proxy_send_timeout    60s;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }

}
```

**Comment by zachgoll** [comment]
@hibate awesome!  Thanks for sharing this!  

Going to close out as I think this config solves the issue.
