### ISSUE TITLE
Bug: undefined method `>=' for nil

### ISSUE THREAD

**Issue by nikhilbadyal** [maybe-finance/maybe#1507]
**Describe the bug**
`>=` check on a nil object.

**To Reproduce**
1. Go to [Self Hosting](http://localhost:3000/settings/hosting)
2. Enter Invalid Key
3. Go to Dashboard

**Expected behavior**
Application should not crash.

**What version of Maybe are you using?**
"Self-hosted". Latest Commit

**Screenshots / Recordings**
<img width="1015" alt="image" src="https://github.com/user-attachments/assets/72bdbd7e-6eb8-47cd-9a01-c11f3109af3e">

**Additional context**
Currently the API Synth Settings screen doesn't force user to enter valid key or prevent itself from saving invalid key into DB.

<img width="515" alt="image" src="https://github.com/user-attachments/assets/967a716b-d61d-4ae4-b0ba-1695f1fd2b6b">

If someone miss types a invalid API key or If somehow key becomes invalid like the key was revoked.

The [usage](https://github.com/maybe-finance/maybe/blob/c3248cd796b3052e72502e7b18ee75d9467770c1/app/models/provider/synth.rb#L13) method will return a [UsageResponse](https://github.com/maybe-finance/maybe/blob/c3248cd796b3052e72502e7b18ee75d9467770c1/app/models/provider/synth.rb#L17) object on 401. 

The [synth_overage](https://github.com/maybe-finance/maybe/blob/c3248cd796b3052e72502e7b18ee75d9467770c1/app/models/family.rb#L158) tries to do `.utilization >= 100` on usage. Since usage can of of type `UsageResponse` which doesn't have utilization. It throws an Exception. 

Possible Fix -
```
def synth_overage?
    self.class.synth_provider&.usage&.utilization.to_i >= 100
end
```

and displaying a flash that key is invalid or similar.

**Comment by zachgoll** [comment]
@nikhilbadyal thanks for the report.  I think your proposed solution makes sense!

In the [Synth settings view](https://github.com/maybe-finance/maybe/blob/main/app/views/settings/hostings/_synth_settings.html.erb), we can also leverage `synth_provider.healthy?` to check whether the provider has a valid API key.  This will return `true` regardless of whether the provider has an overage, so is a good use case for this.
