### ISSUE TITLE
Bug: Transactions Filter button does not show other options when total transactions are 0 for selected category

### ISSUE THREAD

**Issue by developerdsk** [maybe-finance/maybe#1514]
**Describe the bug**
When i select a category example Home Improvements in transactions . if there are 0 Total transactions, the Filter button does not show options to select other category

**To Reproduce**
1. Go to Transactions
2. Click Filter
3. Click Category 
4. Select any category where the total transactions are 0 
5. expect screen with
 ```
No entries found
    Try adding an entry, editing filters or refining your search
```
6. Now try clicking on Filter button , it doesn't show option to select other categories like step 2 and 3 above 

**Expected behavior**
i should be able to edit the filter

**What version of Maybe are you using?**
This could be "Hosted" (i.e. app.maybe.co) or "Self-hosted". If "Self-hosted", please include the version you're currently on.
Hosting : Self Hosted 
version : v0.2.0-alpha.2

**What operating system and browser are you using?**
Windows , Mozilla Firefox , Google Chrome

**Screenshots / Recordings**
![image](https://github.com/user-attachments/assets/e88eb061-1268-457c-9449-3d7576c29e9b)

**Comment by zachgoll** [comment]
Fixed via c456950
