### ISSUE TITLE
Update Polygon API calls to work with free plan

### ISSUE THREAD

**Issue by tmyracle** [maybe-finance/maybe#152]
**Describe the bug**
Currently the security sync service fails in the worker with `status":"NOT_AUTHORIZED","request_id":"834a28975ffae6b825b7680097dbc5a8","message":"You are not entitled to this data. Please upgrade your plan at https://polygon.io/pricing"`

**To Reproduce**

1. Add an API key for a free account to env vars
2. Start up the server and worker
3. Observe job fails

**Expected behavior**
It should sync the securities data in a way that works with the free plan

**Screenshots**
![CleanShot 2024-01-18 at 15 16 38](https://github.com/maybe-finance/maybe/assets/1218724/10623f39-3d81-4ab6-84c0-52c9612891b3)

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser: Brave
-   Version: 1.60.188

**Comment by Shpigford** [comment]
I'm wondering if some of the Polygon calls are trying to get some sort of "real time" data. The Polygon free plan only includes end-of-day data, so that's something to start with on debugging this.

**Comment by tmyracle** [comment]
Yep I'd imagine so, I'd like to see if we can get info about privileges based on API key and adjust data requests accordingly. Will dig into later this afternoon.

**Comment by karan0handa** [comment]
#213 solves this.

**Comment by tmyracle** [comment]
Closed by #213
