### ISSUE TITLE
Bug: Update Check Error 

### ISSUE THREAD

**Issue by nikhilbadyal** [maybe-finance/maybe#1525]
**Describe the Bug**

Currently, when the auto-update checker is enabled, it executes every 30 seconds as per the [cron job](https://github.com/maybe-finance/maybe/blob/a9daba16c15a246737b417869cda42ec6de90258/config/initializers/good_job.rb#L7).

However, GitHub imposes a rate limit of [60 requests per hour](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users) for unauthenticated requests. As a result, the application exceeds this limit, leading to 429 "Too Many Requests" errors in the logs.

**Expected Behavior**
The application should not exceed the GitHub API's rate limit. Auto-update checks should be throttled to align with these restrictions, considering they are non-critical.

Steps to Reproduce

1. Enable the auto-update checker.
2. Let the application run for more than an hour.
3. Observe the logs for 429 rate-limit errors.

**Proposed Solution**
Increase the frequency of the auto-update cron job to once every 1 minutes or more. Alternatively, allow the frequency to be configurable through environment variables for flexibility.

**Comment by zachgoll** [comment]
@nikhilbadyal are we sure this is a bug?  Do you have a reproduction that we could test with?

I wouldn't expect this to happen since we've got the cache set to 2 minutes:

https://github.com/maybe-finance/maybe/blob/a59ca5b7c63f1f70f3f612ff620ea66c9a9537e1/app/models/provider/github.rb#L11

**Comment by nikhilbadyal** [comment]
Here are the logs from my render setup. Looking at it i can see 2 min time difference. But weird enough i still got rate limit errors. 

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/43d9cec8-0ee8-4ac3-a198-44d684e8547c">


Even with 2 min caching. Do we really need to spam this much for updates. I think user can wait a little. It's not some mission critical think which we can't afford to be delayed by few minutes.

**Comment by nikhilbadyal** [comment]
Could it be possible that render is sharing hardware among customer and hence multiple customer might have same IP triggering rate limits. Not sure though, just a wild guess.

**Comment by zachgoll** [comment]
@nikhilbadyal looked into this and I think we're hitting the limit because each uncached method execution results in 3 Github requests, resulting in ~90 requests / hour.  If the user visits the "Changelog" page a few times, it could certainly push over the limit.

I agree, this is far from mission critical, so I'd say we could probably increase both:

- Job: Run it once every 2 minutes
- Github cache keys: expire once every 30 minutes

That should give more than enough buffer and still offer a semi-responsive experience for users.

**Comment by nikhilbadyal** [comment]
How about something like this in GitHub provider. 

```
def initialize(config = {})
    @name = config[:name] || ENV.fetch("GITHUB_REPO_NAME", "maybe")
    @owner = config[:owner] || ENV.fetch("GITHUB_REPO_OWNER", "maybe-finance")
    @branch = config[:branch] || ENV.fetch("GITHUB_REPO_BRANCH", "main")

    # Initialize the Octokit client with authentication
    @client = Octokit::Client.new(access_token: config[:token] || ENV["GITHUB_ACCESS_TOKEN"])
  end
```

and using the client for API calls. 

```
def fetch_latest_release_notes
    begin
      Rails.cache.fetch("latest_github_release_notes", expires_in: 2.hours) do
        release = client.releases(repo).first
        if release
          {
            avatar: release.author.avatar_url,
            # this is the username, it would be nice to get the full name
            username: release.author.login,
            name: release.name,
            published_at: release.published_at,
            body: client.markdown(release.body, mode: "gfm", context: repo)
          }
        else
          nil
        end
      end
    rescue => e
      Rails.logger.error "Failed to fetch latest GitHub release notes: #{e.message}"
      nil
    end
  end
```


Do you think it's a overkill for such a minor issue ?

**Comment by zachgoll** [comment]
@nikhilbadyal yeah, I think that would be fine assuming unauthenticated clients still work (which I believe they do if access_token is nil).  Definitely not necessary though as we're not using the GH client widely across the app.
