### ISSUE TITLE
Bug: Initial Setup doesnt continue if you choose DD.MM.YYYY option, and currency is not updated correctly.

### ISSUE THREAD

**Issue by WpfmEYT7Yc** [maybe-finance/maybe#1538]
**Describe the bug**
During initial setup on the Configure your preferences screen, you cannot select the newly added DD.MM.YYYY format (HTTP Status Code: 442 Unprocessable Conent). It will just reload the page and not let you continue the setup.

And when you change the currency it only updates the smaller bottom part of the preview example. (See image below)

**To Reproduce**
1. Install a fresh instance of maybe-finance
2. Signup for the first account
3. During the initial setup on the Configure your preferences screen select: Currency: Euro (EUR), Date format: DD.MM.YYYY
4. Pressing complete reloads the page, not letting you continue, and you can see the HTTP Status Code 442 in your network history.

**Expected behavior**
My chosen settings get applied.

**What version of Maybe are you using?**
Selfhosted

**Screenshots / Recordings**
![Screenshot from 2024-12-14 16-48-43](https://github.com/user-attachments/assets/611b8792-f709-4884-a59e-00dd45a6e5a4)
In the example it shows +€78.90 but $2,323.25. (Also in germany you would put the €-sign after the amount like this: +78,90€)

**Comment by hknoener** [comment]
It's not only during the initial setup. If you try to make this change after the account is created via Settings -> Preferences -> Date Format, the error is the same.
