### ISSUE TITLE
Bug: unable to login , NoMethodError in logs

### ISSUE THREAD

**Issue by developerdsk** [maybe-finance/maybe#1539]
**Describe the bug**
error after login screen
![image](https://github.com/user-attachments/assets/9d28655c-8ae7-4eda-b509-9240d1622943)

**To Reproduce**
1. Go to login page
2. Enter credentials 
3. See error

**Expected behavior**
i should be able to login and view account summary.

initially i was able to browse until i went to transaction screen and selected some filters if that could help  in reproducing the issue. 
tried restarting the docker , did not resolve the issue. 

**What version of Maybe are you using?**
This could be "Hosted" (i.e. app.maybefinance.com) or "Self-hosted". If "Self-hosted", please include the version you're currently on.
Self Hosted
latest version 
docker

**What operating system and browser are you using?**
windows ,Firefox 

**Screenshots / Recordings**
```
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] ActionView::Template::Error (undefined method `[]' for nil):
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]
Causes:
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] NoMethodError (undefined method `[]' for nil)
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]      9:
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]     10: <%= tag.div style: mixed_hex_styles(hex),
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]     11:             class: [size_classes[size], "flex shrink-0 items-center justify-center rounded-full"] do %>
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]     12:   <%= tag.span name[0].upcase, class: ["font-medium", size == "sm" ? "text-xs" : "text-sm"] %>
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]     13: <% end %>
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx]
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/shared/_circle_logo.html.erb:12
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/shared/_circle_logo.html.erb:10
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/account/transactions/_transaction.html.erb:17
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/account/transactions/_transaction.html.erb:13
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/account/entries/_entry.html.erb:4
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/account/entries/_entry.html.erb:3
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/pages/dashboard.html.erb:194
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/helpers/account/entries_helper.rb:18:in `block (2 levels) in entries_by_date'
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/helpers/account/entries_helper.rb:17:in `block in entries_by_date'
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/helpers/account/entries_helper.rb:16:in `each'
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/helpers/account/entries_helper.rb:16:in `map'
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/helpers/account/entries_helper.rb:16:in `entries_by_date'
[xxxx-xxxxx-xxxxxxxx-xxxxx-xxx-xxxx] app/views/pages/dashboard.html.erb:193


```

**Comment by nikhilbadyal** [comment]
Faced same issue. Apparently [this](https://github.com/maybe-finance/maybe/commit/fe199f235784a96d9b25efe846d87e6f5fb010e7#diff-df4a249bb019e9b2a0c69ea71e277d49e26d7a56eca661ea84c0a93fdf49bb4aL20) is the cause. Code code expects all the `name` column to compulsory have a value in `account_entries` table in DB.

For some reason the name column was having null in lot of entries. I'm suspecting import is having causing null to be inserted. Did you also imported data into the account by CSV ?

As a temp fix - 
1. I populated the `name` column in `account_entries` table. 
2. You can also update [this](https://github.com/maybe-finance/maybe/blob/fe199f235784a96d9b25efe846d87e6f5fb010e7/app/views/shared/_circle_logo.html.erb#L12) piece of code to 
```
<%= tag.span(name&.first&.upcase || "N/A", class: ["font-medium", size == "sm" ? "text-xs" : "text-sm"]) %>
``` 
and redeploy.

**Comment by developerdsk** [comment]
no , i did not import any data using CSV.

**Comment by nikhilbadyal** [comment]
It's the new data enrichment feature.

**Comment by rubenRP** [comment]
Yes, same here. I rollback to stable version until fix.

**Comment by zachgoll** [comment]
@nikhilbadyal thanks for tracking this down.  I'll push a fix through that will handle this.

**Comment by zachgoll** [comment]
I mentioned this elsewhere, but reposting here as it is related.

I've opened - https://github.com/maybe-finance/maybe/issues/1549

This should give us more control around that initial enrichment sync so users don't run out of credits so quickly.
