### ISSUE TITLE
Bug: Enrichment feature uses a lot of synth API

### ISSUE THREAD

**Issue by mamarguerat** [maybe-finance/maybe#1548]
**Describe the bug**
My instance updated with the last commit tried to enrich all of my transactions, causing my synth API to run out of available requested. All the transaction from 1st May (I have more than a thousand transactions) uses an API credit.

**To Reproduce**
1. Have a working Maybe instance with a lot of transactions without commit with enrichment feature.
2. Update with enrichment feature
3. See Synth API credits lowering

**Expected behavior**
The enrichment feature should begin from the update date only and not for older transactions, with a manual action to enrich older transactions, or at least be opt-in for self-hosted.

**What version of Maybe are you using?**
Self-hosted at commit fe199f235784a96d9b25efe846d87e6f5fb010e7

**What operating system and browser are you using?**
Windows 11
Firefox

**Screenshots / Recordings**

**Additional context**
I am the only user on my instance, with 3 accounts with foreign currency and the free tier at Synth. The expected synth API usage should be 1 per account per day => 90 which gives 910 credits for the data enrichment, This should be more than enough for the normal transactions I have in a month.

**Comment by zachgoll** [comment]
@mamarguerat we're still working through what the appropriate pricing looks like for Synth, but I think given this is "enrichment" and not 100% required, we can go ahead and flip it off by default in user settings.  Then, users can opt-in rather than opt-out of this feature.

I'll get this updated shortly.

**Comment by zachgoll** [comment]
This is updated as of the latest commit. 

You may need to go into "Self Hosting Settings" and flip this off manually once as the change I've made should only affect new instances that are created.

**Comment by nikhilbadyal** [comment]
@zachgoll 
Just a quick off-topic question:

Is the Synth free tier 1,000 credits per month, or is it a one-time sign-up bonus of 1,000 credits?

Additionally, if it's 1,000 credits per month, is there a way to track when the counter will reset to zero?

**Comment by zachgoll** [comment]
@nikhilbadyal it should be 1,000 new credits each month.

I do not believe we have the ability to show the date which these credits reset at the moment.

@Shpigford are we thinking of keeping enrichment pricing the same for now?  Is there a spot where users can see when credits reset for the month?

**Comment by zachgoll** [comment]
I've opened - https://github.com/maybe-finance/maybe/issues/1549

This should give us more control around that initial enrichment sync.

**Comment by mamarguerat** [comment]
@zachgoll thank for the quick fix !

**Comment by Shpigford** [comment]
@zachgoll @nikhilbadyal Credits reset on the 1st of every month. Have added that to both the Synth UI and the API.

No plans on changing pricing at the moment.
