### ISSUE TITLE
Bug: M1 Finance data/display issues

### ISSUE THREAD

**Issue by smcpeck** [maybe-finance/maybe#1558]
**Describe the bug**
There may be multiple things here that are a byproduct of the same underlying bug.  But there may also be multiple bugs. There may be nothing (see `Additional Context` below).

![image](https://github.com/user-attachments/assets/60a9f5ef-6d68-4276-8a78-ebef1a05e1db)

1. Chart is only showing "current" balance from "brokerage cash" ($14.47 in the screenshot).
2. All holdings are showing $0.00 (0.0 shares).
3. Because of (2); return in the graph is showing -100%.
4. Also worth noting (but not in screenshot), historic "balance" data under "Activity" shows everything "kinda near" my account's real balance.
  - It does not seem to be deducing/reporting the brokerage account's real balance at any historic point in time.
  - This is somewhat captured in the screen shot as you can see the graph is basically flat, which is surely not the case for the market over the last month.

**To Reproduce**
1. Link M1 Account
2. Wait for it to sync
3. Observe

**Expected behavior**
1. Graph should look like this:
![image](https://github.com/user-attachments/assets/5c0fca3e-1dab-4e41-9e5f-14f1d8151d53)
4. Holdings should show proper share counts.

**What version of Maybe are you using?**
Self-hosted. v0.2.0.

**Additional context**
**FULL DISCLOSURE:**
- In this self-hosted instance, I am setup with my own Plaid integration.  Yes, I know this is not supported, but it seems like the data is just not being proper ingested.
- My Synth API limit has been reached, so maybe certain data is not being properly hydrated due to that? However, all of this data should be (I believe) available in the raw transactions that come from Plaid, so Synth should not be an extra need to display these account details.

**Comment by zachgoll** [comment]
@smcpeck Synth is responsible for filling in historical stock prices.  If you credits have expired, we have no way of multiplying `price * qty` to generate the holding for that day or for historicals.

While Plaid does provide a price on the day of transaction, we're not using it to construct these historicals because our assumption is that Synth is available at all times. 

If this is still happening with an active Synth instance, let me know and I'll reopen!

**Comment by alexkreidler** [comment]
@smcpeck Would you be willing to share the code for your Plaid integration? I think many self-hosters would love to get bank sync working.
