### ISSUE TITLE
Get test suites running accurately again

### ISSUE THREAD

**Issue by tmyracle** [maybe-finance/maybe#156]
**Is your request related to a problem? Please describe.**
As more people jump in to contribute I'd like to make sure we don't introduce unintended regressions. The first step would be to get the test suites running again by either fixing tests or removing irrelevant functionality and tests.

**Describe the solution you'd like**
I'd like to put some protections in place to improve the contribution workflow, especially as people start actually running the app and using it.

1. Fix all test suites so they can run and pass if things are working as expected
2. Add back CI workflow to run tests on branches that have open PRs
3. Put protections in place to prevent merging branches that have failing tests

This will take a bit of work, but it'll allow us to move more quickly in the longterm and improve the reliability of the codebase.

**Comment by tmyracle** [comment]
### Log as of 1/18

Failing tests:

- [ ] queue.integration.spec.ts : `Message queue tests › Creates the correct number of queue`
- [ ] accounts.cy.ts : ` 1) "before each" hook for "should sync and edit a plaid connection"`

Warnings / things to improve:
- [ ] Button.spec.tsx :  `Warning: An update to Panel inside a test was not wrapped in act(...). When testing, code that causes React state updates should be wrapped into act(...):`
- [ ] Tab.spec.tsx : `Warning: An update to Panel inside a test was not wrapped in act(...). When testing, code that causes React state updates should be wrapped into act(...):`
- [ ] Input.spec.tsx : Same as above
- [ ] AccordionRow.spec.tsx : Same as above
- [ ] Step.spec.tsx: Same as above

Not as bad as I expected!

**Comment by tmyracle** [comment]
Ok so those warnings from the design library aren't in the tests themselves, they're related to the implemented code. Not going to touch that for now.

**Comment by karan0handa** [comment]
There are some failing server tests as well `yarn dev:server:test`.

**Comment by tmyracle** [comment]
> There are some failing server tests as well `yarn dev:server:test`.

Which ones are you seeing? Getting a clean run on my end

![CleanShot 2024-01-19 at 10 47 50](https://github.com/maybe-finance/maybe/assets/1218724/efb03bba-e5b9-4e8d-a196-09bfca38c5a7)

**Comment by simonbukin** [comment]
I am also getting a clean run here.

**Comment by tmyracle** [comment]
with #159 this should be ready to go, can work on a change to reintroduce a new github workflow for verifying tests when PRs are opened.
