### ISSUE TITLE
Bug: Can't add an investment transaction

### ISSUE THREAD

**Issue by andreimk** [maybe-finance/maybe#1565]
**Describe the bug**

**To Reproduce**
1. Go to 'you investment account'
2. Click on '+ New Transaction'
3. Click on 'Ticker symbol' edit field
4. Type any valid ticker, for example 'INTC' 
5. Click on any other field
6. Notice that ticker field gets automatically cleared and displays greyed out 'AAPL'
7. Not possible to add a transaction

**Expected behavior**
Able to add a new transaction

**What version of Maybe are you using?**
Self hosted version latest docker image - v0.2.0

**What operating system and browser are you using?**
Manjaro linux, Firefox 133.0.3 (64-bit)

**Screenshots / Recordings**
[Screencast_20241221_114611.webm](https://github.com/user-attachments/assets/8bb5d0d3-deb2-4cd2-a1d2-a08386ef089c)

**Additional context**
Transactions can be added by importing, but when importing it erases previously imported transactions.

**Comment by gkonuralp** [comment]
Same problem on fresh install v0.2.0.

**Comment by Imafikus** [comment]
Similar problem with the v0.2.0 as well

**Comment by berkayermis** [comment]
same

**Comment by necrocron** [comment]
same here

**Comment by MrTob** [comment]
It looks like I had the same problem. Self hosted systems need to have https enabled otherwise a third party library will not work properly. A possible workaround would be a reverse proxy.
See #1533

**Comment by zachgoll** [comment]
@MrTob is correct here.  We cannot do anything about this right now other than suggest running your self-hosted instance over https or switching to a browser that supports [crypto.randomUUID](https://caniuse.com/mdn-api_crypto_randomuuid)

**Comment by barbaroony** [comment]
> It looks like I had the same problem. Self hosted systems need to have https enabled otherwise a third party library will not work properly. A possible workaround would be a reverse proxy. See #1533

I'm running self-hosted instance with a reverse proxy  so that I can use https.  Before I was not able to look up equities, then I installed a reverse proxy and can now look up equities. However I am now have the same issue not being able to add transactions as described in the initial bug report.
