### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by y0un3s3a** [maybe-finance/maybe#1579]
**Describe the bug**
Unable to add gold trackers such as XAU/EUR or XAU/USD in the investment account. The ticker field does not recognize or support these symbols, making it impossible to track gold instruments.

**To Reproduce**

1. Go to the 'Investment Account'.
2. Click on '+ New Transaction'.
3. Click on the 'Ticker Symbol' edit field.
4. Type any valid gold-related ticker, for example, XAU/EUR or XAU/USD.
5. Notice that the ticker field fails to validate or recognize the entered symbol.
6. It is not possible to proceed with adding the gold tracker.

**Expected behavior**
The ticker field should support gold-related symbols (e.g., XAU/EUR, XAU/USD) and allow the addition of transactions for gold instruments seamlessly.

**What version of Maybe are you using?**
Self-hosted version, latest Docker image - v0.2.0 stable

**What operating system and browser are you using?**
Windows, Firefox 133.0.3 (64-bit)

**Screenshots / Recordings**
![Screenshot](https://github.com/user-attachments/assets/f99f498e-1986-4056-9d40-09d936849d48)

**Additional context**
- Using SSL
- Other usual tickers work fine
- Using EUR as currency

**Comment by MrTob** [comment]
After a brief investigation of the issue, I suspect the problem may lie with the API that *Maybe* uses in the background. When searching directly through the API for gold prices, no results are returned. Based on the documentation at https://docs.synthfinance.com/reference/search-tickers, it appears that the API might not support gold pricing data at all.
This is just my hypothesis - perhaps one of the developers could provide a more definitive answer on this matter.

**Comment by Shpigford** [comment]
As @MrTob found, we don't support gold pricing at the moment.
