### ISSUE TITLE
Graph not updating | Hosted

### ISSUE THREAD

**Issue by MarcBlattmann** [maybe-finance/maybe#1580]
The graph's end date is consistently stuck on 20 December and does not update to reflect the current date.

Expected Behavior:
The graph's end date should dynamically display today's date.

Steps to Reproduce:

Access the hosted version of the application.
View the graph.
Observe that the end date remains stuck at 20 December regardless of the current date.
Environment:

Browser: Google Chrome
Platform: Hosted version of the application
Additional Information:
No browser extensions or unusual configurations are being used.

![Screenshot 2024-12-28 171651](https://github.com/user-attachments/assets/dfaf3c7f-e10e-487c-ae29-c86f55e8343c)

**Comment by zachgoll** [comment]
This should be resolved.  We had a few background jobs stuck which I've cleared from the queue.
