### ISSUE TITLE
Unintuitive Logout Placement

### ISSUE THREAD

**Issue by karan0handa** [maybe-finance/maybe#162]
**Is your request related to a problem? Please describe.**
Spent atleast 5 minutes searching for the logout button. Expected it to be there when clicking on the user avatar.
Current flow involves maximizes sidebar, clicking on the three dots and then it being there. Not an intuitive flow.

**Describe the solution you'd like**
![image](https://github.com/maybe-finance/maybe/assets/79533543/f0563c0a-77fd-4fd6-a9c4-77327b12e23b)

The three dot menu should appear when I click the user avatar. I think this is much more intuitive.

**Describe alternatives you've considered**
Another alternative is adding a logout button in settings, but that wouldn't be needed if the above solution is implemented.

**Comment by ikraamdaanis** [comment]
I'll like to tackle this: https://github.com/maybe-finance/maybe/pull/167

**Comment by Shpigford** [comment]
Fixed with #167
