### ISSUE TITLE
Login page throwing a runtime error

### ISSUE THREAD

**Issue by harshit148** [maybe-finance/maybe#164]
I built the app for the first time, signed up an account and completed the onboarding(did not add any bank account). I logged out to a runtime error stating: "ReferenceError: zxcvbn is not defined" on the logine page.

1. Start the development server
2. Sign up a new account
3. Complete the onboarding
4. Click on logout

**Expected behavior**
Login page should have loaded.
**Screenshots**
![image](https://github.com/maybe-finance/maybe/assets/84951304/8cb348cf-6f4d-4f85-ad5d-ba3b3d36ef17)

**Desktop :**

-   OS: Arch Linux
-   Browser: Firefox
-   Version: 6.6.8-arch1-1

Console logs: 
[logs.txt](https://github.com/maybe-finance/maybe/files/13988478/logs.txt)

**Comment by tmyracle** [comment]
Is there anything on your system that might be preventing the loading of external scripts? That library for password strength estimation is being loaded in a nextjs <Script /> tag for now

**Comment by harshit148** [comment]
@Shpigford This issue is still not resolved. I simply answered the query raised by @tmyracle
