### ISSUE TITLE
Implement Storybook for client code

### ISSUE THREAD

**Issue by simonbukin** [maybe-finance/maybe#168]
Currently, we have a Storybook set up in `/libs/design-system` for individual design system components, but none for the components used in the client code (`apps/client`). Having this set up would allow us to quickly test our changes to components (such as Onboarding) without having to hunt down the page in a running version of the app.

**Describe the solution you'd like**
Ideally, we'd have a command like `yarn nx run client:storybook`, which will spin up a Storybook for client components. I think that I can adapt some of existing Storybook code for the design system and point it at the client components, but I'll need to test that out.

This will also need to be added to the docs (ideally for frontend contributions) since this will allow us to quickly test out component changes. The Storybook functionality looks like it is undocumented at the moment.

**Comment by karan0handa** [comment]
@Shpigford could this be opened again? work still remains #204 and adding more stories.

**Comment by tmyracle** [comment]
Another cool next step could be to get the storybook theme updated to the Maybe branding, hopefully that's relatively easy since we can lift from the design library setup.

**Comment by Shpigford** [comment]
Closing again as I believe #204 addressed things.

**Comment by simonbukin** [comment]
@tmyracle I can take a quick look at this; it may be as simple as just just yoinking the design library definition but I'll have to make sure babel plays nice.
