### ISSUE TITLE
Remove AWS dependencies

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#17]
There are slew of AWS-specific bits...so many that I honestly don't recall what all they were used for. But ultimately we need to make this platform-agnostic so that AWS isn't a requirement.

**Comment by tamirfyi** [comment]
First attempt at an OSS contribution - I'm going to work on this and see if I can get a PR out tonight.

**Comment by guptadeepak8** [comment]
Can i get assigned?

**Comment by Shpigford** [comment]
Hey guys, we don't pre-assign issues at the moment without a longer history of commits to the repo. Thanks for the interest!

**Comment by ssong** [comment]
What's the desired first outcome here?

Is the intention to strip out the existing AWS setup and provide guides for self-hosting or 'get it working locally' type situation?

**Comment by Shpigford** [comment]
@ssong for this specific issue, it's just "remove any code associated with deploying to aws". we'll put together a separate issue about local deployment once we get the codebase functioning properly.
