### ISSUE TITLE
Incorrect transaction inflow/outflow inference

### ISSUE THREAD

**Issue by waltershewmake** [maybe-finance/maybe#171]
**Describe the bug**
When importing my Wells Fargo bank account, every transaction seems to be inversely marked as inflow or outflow. All income was reported as an expense in Maybe, and all expenses were marked as income. 

**To Reproduce**

1. Link *Wells Fargo* account (I am in teller development mode)
2. Click on 'Net Worth'
3. Click on the new account
4. Observe that all transactions are inverted

**Expected behavior**
I expected each transaction to correctly display whether it was income or expense.

**Screenshots**
<img width="1030" alt="Screenshot 2024-01-19 at 2 47 53 PM" src="https://github.com/maybe-finance/maybe/assets/21002090/f0039b05-8a7c-470e-bf23-58ec5f15c363">

**Desktop (please complete the following information):**

-   OS: macOS Sonoma 14.0
-   Browser: Arc
-   Version: 1.15.1 (43023)

**Additional context**
The account was added during the onboarding flow after the initial setup of the repository.

**Comment by noonfyi** [comment]
I'm seeing this inversion bug with both live and sandbox data but for cash accounts only, and not with credit cards.
@waltershewmake are you seeing this bug with credit cards as well?

Screenshot of a sandbox Chase checking account:
![image](https://github.com/maybe-finance/maybe/assets/116238122/f887d567-a314-4109-80dd-352528885835)

Screenshot of a live Bank of America checking account:
![image](https://github.com/maybe-finance/maybe/assets/116238122/cfe26605-47ff-49e2-82a6-53b8f070bd5a)
This account only receives CC cash back, which should be Income, and then transfers out an account at a different bank, which should be an Expense (or Transfer if that account was added, which it is not)

**OS**: Windows 10 (WSL2/Ubuntu/Docker Desktop 4.26.1)
**Browser**: Firefox
**Version**: 121.0.1

**Comment by Shpigford** [comment]
There _may_ be some hardcoded "invert positive/negative" bits of code somewhere. I vaguely recall Plaid always giving us the incorrect symbol, so worth digging around to see if that's happening somewhere.

**Comment by waltershewmake** [comment]
It might be a good idea to have a modal popup asking the user to select which is income and which is expense. Since I assume the symbols will be at least consistent across the same source, we can safely invert the polarity on command. Maybe there should be an option to update this polarity at any time from a settings menu for each account

**Comment by waltershewmake** [comment]
> > It might be a good idea to have a modal popup asking the user to select which is income and which is expense. Since I assume the symbols will be at least consistent across the same source, we can safely invert the polarity on command. Maybe there should be an option to update this polarity at any time from a settings menu for each account
> 
> 
> 
> Oh Walter. Wouldn't that be nice. 🙂 (This is the kind of stuff we spent actual _months_ of engineering time trying to consistently solve...it's such a nightmare.)
> 
> 
> 
> I'd suggest digging in to the raw response from Teller's API first to see if that gives more clarity on what's happening. And compare responses from different banks to see how consistent things are/aren't.

Okay, I will look into this. Did you guys spend any time with the Stripe Financial Connections beta product? It may provide a better experience than teller and seems to support a wider range of banks but I don't know for sure

**Comment by Shpigford** [comment]
> Did you guys spend any time with the Stripe Financial Connections beta product?

Not viable for individual use. You need a business to open a Stripe account.

**Comment by tmyracle** [comment]
Fixed, yeah Plaid's API is the opposite of what you'd expect and I think the app was set up for that convention so for both Teller and Finicity you gotta do some sign wrangling 😄 . Each connections provider will have to sort this out in their ETL pipeline if we continue to add more / create a framework for others to write their own.

**Comment by Shpigford** [comment]
Fixed with #184
