### ISSUE TITLE
Login page and design system improvements

### ISSUE THREAD

**Issue by aditya-67** [maybe-finance/maybe#173]
### Improvements to the login page

- Password complexity bar and requirements text pop-up can be removed from the Login page
<img width="612" alt="Screenshot 2024-01-20 at 3 18 01 AM" src="https://github.com/maybe-finance/maybe/assets/9695866/890e82dd-3b01-4543-b05b-74ba6e7a59dd">
 
<img width="612" alt="Screenshot 2024-01-20 at 3 17 45 AM" src="https://github.com/maybe-finance/maybe/assets/9695866/12c91295-b38b-400d-9039-eee49ca1b1e2">

- Button does not have any loader/spinner on click. UX can be improved by adding a spinner to the Button.

<img width="612" alt="Screenshot 2024-01-20 at 3 29 07 AM" src="https://github.com/maybe-finance/maybe/assets/9695866/16686e8a-8c09-4460-b5db-fe091533d5d5">

**Comment by Shpigford** [comment]
Implemented with #174
