### ISSUE TITLE
Menu is not accessible upon clicking the user profile button on the home page.

### ISSUE THREAD

**Issue by mrkirthi-24** [maybe-finance/maybe#179]
**Describe the bug**
When the user clicks on the profile button on the home page, the menu opens on the left side rather than the right.

**Expected behavior**
Menu should open the right side.

**Screenshots**

https://github.com/maybe-finance/maybe/assets/53830546/5244df64-554f-423b-bf91-e88858c86901

**Desktop (please complete the following information):**

-   macOS
-   Chrome

**Comment by Shpigford** [comment]
Fixed with #179
