### ISSUE TITLE
Remove LaunchDarkly/feature flags

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#18]
We originally used LaunchDarkly for feature flag management. We need to remove that dependency as well as any feature-flagging functionality.

**Comment by tmyracle** [comment]
Hey Josh, working on ripping this stuff out. Prefer I fork or just push the branch up here? Thanks.

**Comment by Shpigford** [comment]
PR, please!

**Comment by tmyracle** [comment]
Will do, can you add me as a contributor so I can push and open a PR? Thanks!

**Comment by Shpigford** [comment]
you should be able to fork and do a PR without that.

**Comment by MelvinJCB** [comment]
Closed by #23
