### ISSUE TITLE
Incorrect Credentials

### ISSUE THREAD

**Issue by cmosguy** [maybe-finance/maybe#186]
**Describe the bug**
When I am **onboarding**  and enter my Wells Fargo credentials it fails.  Since, Teller is the middle man I would think this is working.  I did actually test this out directly in the Teller app and it was able to retrieve my WFB information.  However, when I attempt to repeat the same process in the maybe app then it fails.

![image](https://github.com/maybe-finance/maybe/assets/1676382/230570b7-8c34-4946-8c8c-0aa5a677da5c)

I know I am entering my WFB credential information correctly.  Where could the error be possibly failing at?

**Comment by tmyracle** [comment]
what's your teller environment set to?

**Comment by Shpigford** [comment]
@cmosguy Just to knock out the big things...do you have these variables set in `.env`?

```
NX_TELLER_SIGNING_SECRET=
NEXT_PUBLIC_TELLER_APP_ID=
NEXT_PUBLIC_TELLER_ENV=
NX_TELLER_ENV=
```

And, specifically, what are `NEXT_PUBLIC_TELLER_ENV` and `NX_TELLER_ENV` set to?

**Comment by cmosguy** [comment]
Thanks @Shpigford  I think so, here is the entries: 

![image](https://github.com/maybe-finance/maybe/assets/1676382/b86ad34d-b03f-4c39-8e26-a7d684cd56f5)

**Comment by Shpigford** [comment]
Got it! So you need to set those `sandbox` items to `development` if you want to use live credentials.

Also, be sure you've got those cert files set up.

![CleanShot 2024-01-20 at 15 29 11@2x](https://github.com/maybe-finance/maybe/assets/35243/e3edcc6f-eadc-4155-b24a-074976e159c1)

**Comment by cmosguy** [comment]
@Shpigford wow, I missed the `development` part to change in the `.env` file.  I think the confusion is that when you login to teller, you cannot see a `sandbox` or a `development` setting.  Like you mentioned, you have to read the [Teller Docs configuration options](https://teller.io/docs/guides/connect#configuration-options).
