### ISSUE TITLE
Render email templates

### ISSUE THREAD

**Issue by eneskaya** [maybe-finance/maybe#187]
**Is your request related to a problem? Please describe.**

Emails were sent using templates in Postmark, which ties the sending of emails to that specific provider. 

**Describe the solution you'd like**

As discussed in #54, it would be better if the emails are actually rendered in the app, having them checked in to source control and ultimately make emails provider agnostic. Since this is a React codebase, we could leverage [React Email](https://react.email/docs/introduction) to create the templates. The sending itself could still be done with Postmark for now, until further support for other providers or simply SMTP.

**Comment by DestroyerXyz** [comment]
@Shpigford @eneskaya I've worked with React Email before so I could work on this.

**Comment by rishi-raj-jain** [comment]
@Shpigford 

Can I work on this? Wondering if you're doing a  bounty on this one?

**Comment by Shpigford** [comment]
@rishi-raj-jain you're certainly welcome to! just open a Draft PR when you start

https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md

No bounty on this one.

**Comment by choeqq** [comment]
@rishi-raj-jain @DestroyerXyz did you guys already started doing some work on this issue?

**Comment by DestroyerXyz** [comment]
I haven't @choeqq
