### ISSUE TITLE
Message: `column "asset_class" does not exist` 

### ISSUE THREAD

**Issue by sldless** [maybe-finance/maybe#191]
**Describe the bug**
Fails to load metrics

**To Reproduce**

1. Add more cash to the existing cash
2. Click on one of the timelines (1M, 3M, 1Y) on the Net Worth page

**Expected behavior**
To load the metrics successfully under the graph.

**Screenshots**
![image](https://github.com/maybe-finance/maybe/assets/67599596/3b59c288-f0e2-444e-84c1-57b62dc6f46a)

![image](https://github.com/maybe-finance/maybe/assets/67599596/bb4d4ce9-d87e-4a7a-8af7-97285f408dd5)
![image](https://github.com/maybe-finance/maybe/assets/67599596/95822bd1-ce3f-497e-9836-d3d8ef1cd2c9)

**Desktop (please complete the following information):**

-   OS: Windows 11
-   Browser: Firefox Nightly
-   Version: 123.0a1

**Additional context**

**Comment by Shpigford** [comment]
@MichaelDeBoey @tmyracle Does this possibly have relation to the cleanup work you guys were doing?

**Comment by tmyracle** [comment]
I think that was just added to the Security table. @sldless have you run migrations since your last pull, I wonder if its calling it in the code, but the DB hasn't been updated yet.

**Comment by sldless** [comment]
> I think that was just added to the Security table. @sldless have you run migrations since your last pull, I wonder if its calling it in the code, but the DB hasn't been updated yet.

When running `yarn prisma:migrate:dev`, I get an error.
![image](https://github.com/maybe-finance/maybe/assets/67599596/f618b570-4c71-4385-a47c-a762cdb4f8de)

**Comment by tmyracle** [comment]
> > I think that was just added to the Security table. @sldless have you run migrations since your last pull, I wonder if its calling it in the code, but the DB hasn't been updated yet.
> 
> When running `yarn prisma:migrate:dev`, I get an error. ![image](https://private-user-images.githubusercontent.com/67599596/298318232-f618b570-4c71-4385-a47c-a762cdb4f8de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDQ5MTgsIm5iZiI6MTcwNTgwNDYxOCwicGF0aCI6Ii82NzU5OTU5Ni8yOTgzMTgyMzItZjYxOGI1NzAtNGM3MS00Mzg1LWE0N2MtYTc2MmNkYjRmOGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAyMzY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZWE0YTA0NmM3ZTViYjgxNDUwOTkyNzRkMTRhODA5Y2RiMjk1ZjhkOGIzNGRhNGRhZjE2MmZmMDc1NjQ3NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f67r5K-ZmEcU9oO3t9LK41k34HQJDd_aESSdlo8UBqY)

Hmmm 🤔  hard to tell except we know what migration is causing the issue. Assuming thats the full error message? For what its worth I've been able to migrate successfully with that change in, might have to try resetting the database and starting fresh.

**Comment by sldless** [comment]
After syncing my db with the recent changes, it can't find my account. Is this normal?
![image](https://github.com/maybe-finance/maybe/assets/67599596/805c3f73-847d-4c35-aa17-a5ddff4b0cf5)

**Comment by sldless** [comment]
Nevermind I reset because of conflicts, thanks!
