### ISSUE TITLE
Remove Intercom

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#22]
As you won't need Intercom to support yourself, we don't need those bits in the app.

**Comment by JaumeGelabert** [comment]
Hello, I'm quite new to contributing to Open Source. Do you think this is a good first issue?

**Comment by Shpigford** [comment]
@JaumeGelabert Yep! It's probably the most straightforward of the current issues.

**Comment by JaumeGelabert** [comment]
@Shpigford Great
