### ISSUE TITLE
 add quick login for developers 

### ISSUE THREAD

**Issue by choeqq** [maybe-finance/maybe#240]
**Is your request related to a problem? Please describe.**
It would be nice to have some predefined users already in app, and just click to login for dev purposes 

**Describe the solution you'd like**
Few predefined users on login page

**Comment by Maxwell011** [comment]
Good Day @choeqq I would to contribute, what is the issue ?

**Comment by choeqq** [comment]
hi @Maxwell011 the PR is already submitted [here](https://github.com/maybe-finance/maybe/pull/241), I just need some more mocked data to get the user through onboarding process etc.

**Comment by Maxwell011** [comment]
Okay @choeqq I know you might be busy please let us make time to talk

**Comment by karan0handa** [comment]
Hey @choeqq. Thanks for raising this issue. This was already discussed in #196. Earlier we had pre-seeded users, but we removed them.

When signing up a user, you can click on the "Onboard user" option to skip onboarding for the user.
