### ISSUE TITLE
Rework Accounts model to use Delegated Types

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#254]
We currently use STI for Accounts and their types, but given each type can have their own subset of attributes, going the Delegated Types route likely makes more sense.

These are the specific types we need:

* Depository
* Credit
* Investment
* Loan
* Property
* Vehicle
* OtherAsset
* OtherLiability

We'll go in and add the additional type-specific attributes in the future.

The only "STI-specific" bits that likely need addressing:
* The `type` column on Accounts
* Credit model
* Depository model

**Comment by robzolkos** [comment]
What are the attributes common to all types?

(I believe Rails delegated types is the best fit for this problem, especially if there may be specific business logic tied to the various types later)

**Comment by Shpigford** [comment]
> What are the attributes common to all types?

Currently...
* name
* balance

**Comment by robzolkos** [comment]
Began on this [here](https://github.com/maybe-finance/maybe/pull/255)
