### ISSUE TITLE
Start I18n Internationalization setup

### ISSUE THREAD

**Issue by ricsdeol** [maybe-finance/maybe#256]
Hello, please start using I18n to facilitate the app to be multi-lang.

I could start this weekend if you approve.

Short Guide about this.
https://guides.rubyonrails.org/i18n.html

**Comment by Shpigford** [comment]
Yes! That was on our shortlist. 100% would love that.

**Comment by Shpigford** [comment]
@ricsdeol If you do start on it, please submit a Draft PR associated with this issue so others can track progress. Helps us make sure issue work doesn't get stale.

**Comment by ricsdeol** [comment]
> @ricsdeol If you do start on it, please submit a Draft PR associated with this issue so others can track progress. Helps us make sure issue work doesn't get stale.

Cool, I'm going to start this weekend :smile:

**Comment by ricsdeol** [comment]
Start at #276

**Comment by Shpigford** [comment]
@ricsdeol Does the I18n stuff that @josefarias has in #269 conflict with what you're doing at all?

**Comment by jclusso** [comment]
Might want to consider using [i18n-tasks](https://github.com/glebm/i18n-tasks) paired with Google Translate or DeepL so translations don't slow down development and so you can lint them in the CI for missing ones.

**Comment by ricsdeol** [comment]
> @ricsdeol Does the I18n stuff that @josefarias has in #269 conflict with what you're doing at all?

I solved the conflicts and use i18-tasks, I didn't know it, very interesting.

**Comment by josefarias** [comment]
> I solved the conflicts and use i18-tasks, I didn't know it, very interesting.

Yeah i18n-tasks can sometimes slow you down a bit which isn't ideal.

But i18n can be a pain to manage when the files get super large. And the tasks + tests force you to be disciplined about keeping it tidy.

It's a pick your poison scenario in my mind 😅.
