### ISSUE TITLE
Tailwind not configured

### ISSUE THREAD

**Issue by pmareke** [maybe-finance/maybe#257]
I had to execute `rake assets:precompile` after the `bundle install` in order to have Tailwind configured.

I can do a PR if you think this is a bug.

**Comment by Shpigford** [comment]
You shouldn't ever need to execute that. What OS/environment are you using?

**Comment by pmareke** [comment]
MacOS Somona, here it's the error:

<img width="1050" alt="image" src="https://github.com/maybe-finance/maybe/assets/3502075/81e97793-5338-4891-946e-b6c683b05abb">

**Comment by Shpigford** [comment]
How did you start the server?

**Comment by pmareke** [comment]
My fault then, I used `rails server` instead of `bin/dev.

Do you think this should be explicit in the README?

PD: Great job btw!

**Comment by Shpigford** [comment]
I mean maybe we could bold it or something? 🙃

![CleanShot 2024-02-02 at 15 34 55@2x](https://github.com/maybe-finance/maybe/assets/35243/e6987822-3d17-4502-baa6-8975f970175c)

**Comment by pmareke** [comment]
Oh god 🤦🏼
