### ISSUE TITLE
Centralize auth errors/notices/alerts

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#264]
This is specific to authorization messages/errors.

We've got messages sprinkled throughout various places in the app and we need to centralize them so they can consistently be styled.

There's this in the auth layout: https://github.com/maybe-finance/maybe/blob/main/app/views/layouts/auth.html.erb#L21-L25

And then form-specific validation errors: https://github.com/maybe-finance/maybe/blob/main/app/views/passwords/edit.html.erb#L4-L8

Auth-specific view directories to look through to find these...
* views/password_resets
* views/passwords
* views/registrations
* views/sessions

Ideally all messaging would be displayed above the first form field on any give form.

![CleanShot 2024-02-02 at 21 04 09@2x](https://github.com/maybe-finance/maybe/assets/35243/c1718bd0-7ec6-404a-a285-20059fb07075)

If you're interested in tackling this, don't overthink the styling itself. We can customize that. The main thing is getting it all in one place and then at least passing in the type of message (success/error/info/etc) and we can do more customized styling based on that.

**Comment by josefarias** [comment]
I can tackle this tonight

**Comment by jclusso** [comment]
What are your thoughts on errors being handled in one of two ways? When they are attached to a field, you put them with the field, but when they are generic, you throw them into a floating message. I've found this to work really well.

<img width="1288" alt="image" src="https://github.com/maybe-finance/maybe/assets/622516/e8cc3e1c-b435-44b7-ac87-6187dc9829c6"> (ignore phone being blank here... it typically would appear like below, but I didn't want my number public)
<img width="1050" alt="image" src="https://github.com/maybe-finance/maybe/assets/622516/06a74531-c9e6-466c-9da1-9832282bd8ce">

**Comment by Shpigford** [comment]
@jclusso Long term I like that, but will be a much bigger project to tackle and we'll likely have a LOT of UI changes in the coming weeks. So just trying to keep them really straightforward for now.

**Comment by jclusso** [comment]
@Shpigford, makes sense! When more things are fleshed out, feel free to tag me and I'd be happy to bring over some stuff I have for doing this nicely.
