### ISSUE TITLE
Docker file bundler version

### ISSUE THREAD

**Issue by huseyinulas** [maybe-finance/maybe#277]
Bundle version mismatch with Gemfile. 
Docker build gives an error below

There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /rails/.ruby-version. Bundler cannot continue.

**Comment by Shpigford** [comment]
Can you give more information about terminal commands you used when you got the error along with what OS you're using?

**Comment by jkostolansky** [comment]
Probably because of this: https://github.com/maybe-finance/maybe/blob/e771735c68be6487c884c0acab96d19b6e6ac5de/Dockerfile#L25

There's missing COPY for `.ruby-version` file before `bundle instal`, only `Gemfile`.

**Comment by Shpigford** [comment]
@huseyinulas can you confirm if what @jkostolansky mentioned fixes it for you? if so we can get that merged in.

**Comment by robzolkos** [comment]
This may be related to [this](https://github.com/maybe-finance/maybe/pull/253/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55fR3) change.

I thought it may have been an older version of Bundler that caused this (the ability to specify a file was introduced in bundler 2.4.19), but running

`docker run --rm ruby:3.3.0-slim bundler --version` reports `Bundler version 2.5.3`

So the reason this breaks is like @jkostolansky said - we don't actually move the `.ruby-version` over prior to bundling at this step.

So there are two options:

1/ Revert that commit and specify the Ruby version in the Gemfile
2/ Modify the docker file to copy over the .ruby-version file before bundler is run.

I'm in favor of less re-configuring of the default Dockerfile.   There are a number of places that need to be changed when a new ruby version is released anyway (Dockerfile, .ruby-version, dev container config etc).  It happens so infrequently that a simple find and replace of `3.3.0` to `3.3.1` is normally sufficient and easy.  I don't think we are saving much by not just putting the ruby version at the top of the Gemfile (which is the default place anyway, and somewhere devs expect to find it).

**Comment by Shpigford** [comment]
I generally agree. I honestly hadn't even seen the `ruby file: ".ruby-version"` syntax before.

Fine with me to revert that line.

**Comment by zackgilbert** [comment]
For what it's worth, I've run into issues with using the `ruby file: ".ruby-version"` method when deploying to some hosts like fly.io. I've had to override projects that use it by commenting this out, write the hardcoded Ruby version in, and deal with the conflicts when merging upstream.

So all for reverting this until a better solution is determined.
