### ISSUE TITLE
Use SQLite as default database in production.

### ISSUE THREAD

**Issue by pmareke** [maybe-finance/maybe#280]
What do you think about use SQLite as the main database, both in local and production? This solution will let the users to run their own Maybe server without the need of having a Postgres database running.

Thanks for your time and congratulations for this amazing work!!!

**Comment by shobhitic** [comment]
I don't think this is needed with docker-compose. You can run PG as well with docker compose with a single command.

**Comment by Shpigford** [comment]
We've explored that a bit but the reality is that some of the long-date-range financial calculations we have to do for certain stats will likely end up making use of Postgres-specific tools like Timescale.

We could _probably_ make it work for single-user, self-hosted, but definitely not an option for Maybe's hosted option. And maintaining separate databases and queries is just too much overhead.

**Comment by pmareke** [comment]
Thanks @Shpigford, it sounds quite reasonable.
