### ISSUE TITLE
Rework delegated type styling to helpers

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#282]
Helpers may not be the right place for this, but I feel pretty certain models definitely aren't. 🙃

@robzolkos I believe you'd mentioned this was a temp solution anyways, but wanted to go ahead and get them moved out of the models sooner than later if possible.

```
class Account::OtherAsset < ApplicationRecord
  include Accountable

  def icon
    "icon-add-alt.svg"
  end

  def type_name
    "Other Asset"
  end

  def color
    {
      background: "bg-[#EDF7F4]",
      text: "text-[#1BD5A1]"
    }
  end
end
```

This is in every `/models/account/*.rb` file

**Comment by robzolkos** [comment]
Yep pls assign mw

**Comment by robzolkos** [comment]
@Shpigford are the colors defined per _account type_ in a styleguide somewhere (seeing if this in-fact configuration related).

**Comment by Shpigford** [comment]
> @Shpigford are the colors defined per _account type_ in a styleguide somewhere (seeing if this is in-fact configuration related).

Negative. Not that far into the solidified design yet.

**Comment by robzolkos** [comment]
ok - I'll rip the styling out of the models and put back in the view for now.  My goals really were to have a single place to go to for configuration of a type (and also to showcase some of the benefits of the delegated type) - We shouldn't need to go hunting for config for this and config for that.  But we can revisit that when things start get more intense (particularly once colors are well defined in the tailwind config).  PR incoming.
