### ISSUE TITLE
Convert colors to Tailwind

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#3]
We need to convert the color palette to Tailwind color syntax (for use in tailwind.config.js).

Here's the Figma file with the colors: https://www.figma.com/file/rAn2k5U86nXZmBixAEsjdN/Shell?type=design&node-id=8%3A3495&mode=design&t=0q11JqWuYDnEcFDH-1

Tailwind color customization docs: https://tailwindcss.com/docs/customizing-colors

Tailwind config file: https://github.com/maybe-finance/maybe/blob/main/config/tailwind.config.js

<img width="2332" alt="Colors" src="https://github.com/maybe-finance/maybe/assets/35243/077148ba-2adb-413a-8cd3-e86afd5ae3b3">

**Comment by faqndo97** [comment]
@Shpigford The list of colors from tailwind should be overwritten and reduced to only those colors? That means no other colors will be used, am I right?

**Comment by Shpigford** [comment]
> @Shpigford The list of colors from tailwind should be overwritten and reduced to only those colors? That means no other colors will be used, am I right?

That's correct. This is the exclusive color palette.
