### ISSUE TITLE
Windows develop support

### ISSUE THREAD

**Issue by yeskiy** [maybe-finance/maybe#306]
# Summary
Hey! It looks here are no Windows develop support. I am using Windows for developing stuff and I personally don't really like `devcontainers` (probably due to low JetBrains support of that)
## Task
Bring some documentation and do other fixes for supporting Windows as development platform.

**Comment by bschrag620** [comment]
Having worked on several rails projects on Windows machine, I always recommend setting up WSL on utilizing Ubuntu to run a Linux console and developing through it rather than through Windows directly.

**Comment by zachgoll** [comment]
Closing out as we now have a Windows local dev setup guide: 

https://github.com/maybe-finance/maybe/wiki/Windows-Dev-Setup-Guide

If any additions need to be made to this to get up and running, let me know in a comment and I'll get it updated!
