### ISSUE TITLE
Some Windows error stopping me from running the app

### ISSUE THREAD

**Issue by hyoretsu** [maybe-finance/maybe#315]
/usr/lib/ruby/3.0.0/bundler/dsl.rb:360:in `block in normalize_options': `windows` is not a valid platform. The available options are: [:ruby, :ruby_18, :ruby_19, :ruby_20, :ruby_21, :ruby_22, :ruby_23, :ruby_24, :ruby_25, :ruby_26, :mri, :mri_18, :mri_19, :mri_20, :mri_21, :mri_22, :mri_23, :mri_24, :mri_25, :mri_26, :rbx, :truffleruby, :jruby, :jruby_18, :jruby_19, :mswin, :mswin_18, :mswin_19, :mswin_20, :mswin_21, :mswin_22, :mswin_23, :mswin_24, :mswin_25, :mswin_26, :mswin64, :mswin64_19, :mswin64_20, :mswin64_21, :mswin64_22, :mswin64_23, :mswin64_24, :mswin64_25, :mswin64_26, :mingw, :mingw_18, :mingw_19, :mingw_20, :mingw_21, :mingw_22, :mingw_23, :mingw_24, :mingw_25, :mingw_26, :x64_mingw, :x64_mingw_20, :x64_mingw_21, :x64_mingw_22, :x64_mingw_23, :x64_mingw_24, :x64_mingw_25, :x64_mingw_26] (Bundler::GemfileError)

**Comment by robzolkos** [comment]
Does it work if you run `bundle lock --add-platform x64-mingw-ucrt` ?

**Comment by robzolkos** [comment]
Ah gotcha.  The error message threw me off.   Do you get an error building the docker image?

**Comment by hyoretsu** [comment]
I ended up being able to build the docker image with `sudo docker build -t maybe .` but when I ran the image I couldn't start it as it was perma exitted. Another time I got something about a secretkey I think, which was invalid.

**Comment by bschrag620** [comment]
In general I've always stepped devs away from running rails apps in Windows. Instead I recommend using WSL to run Ubuntu on the Windows machine and run the rails app through it. It's generally a simple setup, though I haven't tried with this particular app.
