### ISSUE TITLE
README Recommendations

### ISSUE THREAD

**Issue by hyoretsu** [maybe-finance/maybe#316]
I struggled quite a lot to get it working. I know it's meant to be a WIP, developer-focused, but early adoption would be good.
- I had to install Ruby using RVM to successfully do `bundle install`, using Snap or Apt didn't work
- People have to install Ruby on Rails (and maybe bundler) first.
- Mention about the `RAILS_ENV` variable
- I don't know if it's an error of mine but I needed to remove config/credentials.yml.enc
- My rails isn't picking up .env variables, so I need to set DB password and RAILS_ENV manually in the db:setup command
- Mention that you need to either create a maybe username in Postgres or change it in `config/database.yml`

**Comment by Shpigford** [comment]
What OS are you on?

**Comment by hyoretsu** [comment]
Full-on Ubuntu through EC2

**Comment by pgroyal22** [comment]
Even Arch ships with 3.0.6, I think a RVM shoutout would be great for the easy of installation

**Comment by zachgoll** [comment]
Hey @hyoretsu I'm working on some updates to the README to clarify some of these things.  Are you trying to get this started to develop?  Or are you primarily trying to self-host?

**Comment by zachgoll** [comment]
@hyoretsu sounds good.  We are still pretty early with development, so haven't spent the time to optimize for self hosting yet.

I'm going to go ahead and close this issue, but keep an eye on this guide:

https://github.com/maybe-finance/maybe/wiki/Self-Hosting-Setup-Guide

We will update this as we get closer to a first release and will make sure and add detailed instructions for making this work smoothly!

Also, regarding the environment variables, I think PR #334 will fix that.
