### ISSUE TITLE
Add new "Investment" (balance) account form

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#331]
We're working on adding each new account type as they've got slightly different "field" needs.

All accounts have "Name" and "Balance" by default.

This specific "investment" form is for tracking account _balance_ (not tracking individual holdings).

Additional fields:
* Type — Select 

Types to add...
* Brokerage
* Pension
* Retirement
* 401(k)
* 529 plan
* Health Savings Account
* Mutual Fund
* Roth IRA
* Roth 401k

View is in `/views/accounts/account/_investment.html.erb`

**Comment by jespr** [comment]
I can take a stab at this

**Comment by Shpigford** [comment]
Implemented with #343
