### ISSUE TITLE
The setup fails

### ISSUE THREAD

**Issue by pmareke** [maybe-finance/maybe#335]
Something has changed in the last commits (this morning it workings as expected) and right now the setup fails (the devcontainers are up and running):

<img width="1431" alt="image" src="https://github.com/maybe-finance/maybe/assets/3502075/21c0d0e2-6c94-4539-a887-55b6e4b418aa">

Related with this another [PR](https://github.com/maybe-finance/maybe/pull/334/files)

**Comment by SiboVG** [comment]
Don't know if this is helpful, but I fixed this by starting the PostgreSQL service with brew:
```bash
brew services start postgresql
```

**Comment by pmareke** [comment]
> Don't know if this is helpful, but I fixed this by starting the PostgreSQL service with brew:
> 
> ```shell
> brew services start postgresql
> ```

Thanks @SiboVG, but I don't want to have Postgres install on my machine, this is why ww use Devcontainers.

**Comment by ItsRyanWu** [comment]
> Don't know if this is helpful, but I fixed this by starting the PostgreSQL service with brew:
> 
> ```shell
> brew services start postgresql
> ```

I tried but didn't work
![image](https://github.com/maybe-finance/maybe/assets/17338101/2580a69d-90a8-4f4f-a077-85cb746a3db5)

**Comment by pmareke** [comment]
The problem is fixed now with the PR, thanks!.
