### ISSUE TITLE
Dev container frontend not working

### ISSUE THREAD

**Issue by LosBagros** [maybe-finance/maybe#340]
I have a problem with accessing frontend

Curl inside container worked somehow...

Steps to reproduce:
1. Clone repo
2. Open dev container
3. `bin/dev`
4. Cannot access frontend

![image](https://github.com/maybe-finance/maybe/assets/45005533/256edce3-ae29-445c-a10a-489d6e31e250)
![image](https://github.com/maybe-finance/maybe/assets/45005533/80dc1d93-7014-4296-a9e2-bc737f9e5909)

**Comment by robzolkos** [comment]
Try updating the line in `Procfile.dev` to `web: bin/rails server -b 0.0.0.0` and see if that makes a difference before running `bin/dev` again

**Comment by zachgoll** [comment]
As we resolve this one, can we add the solution in a comment on #339 just so I can add it to the Dev Container section?

**Comment by LosBagros** [comment]
Thx

**Comment by caioluis** [comment]
@robzolkos I'm having the same issue, but as I already have the latest version of `Procfile.dev`, I wonder what could cause this.
