### ISSUE TITLE
ruby-build installation step is missing in Linux Dev Setup Guide

### ISSUE THREAD

**Issue by Digital-inspiration** [maybe-finance/maybe#347]
In the [Linux Dev Setup Guide ](https://github.com/maybe-finance/maybe/wiki/Linux-Dev-Setup-Guide)it mentions installing ruby version 3.3.0 using the rbenv command. However the `rbenv install --list` shows only a list upto version 2.8.0-dev as the last version. Hence installation of version 3.3.0 is not possible. 
Please note I am using Ubuntu 22.04.3 LTS in  WSL2

**Comment by kiliczsh** [comment]
Rehash to make sure everything is set up correctly:

```sh
rbenv rehash
```

@zachgoll can you please add this step into wiki

**Comment by rodmarkun** [comment]
Same problem here, also using Ubuntu 22.04.3.  `rbenv rehash` does not seem to solve the issue.

**Comment by bschrag620** [comment]
I did a fresh install of `rbenv` and my list already had it so I can't confirm this works, but does `git -C ~/.rbenv/plugins/ruby-build pull` update the version lists to have 3.3? A quick search for what `rehash` makes it seem that it is a deprecated feature.

**Comment by zachgoll** [comment]
I think @bschrag620s suggestion is correct based on these docs - https://github.com/rbenv/ruby-build?tab=readme-ov-file#clone-as-rbenv-plugin-using-git

Can someone run this and confirm it works?

```
git -C "$(rbenv root)"/plugins/ruby-build pull
```

If so, I'll add it to the Wiki!

**Comment by rodmarkun** [comment]
> I think @bschrag620 suggestion is correct based on these docs - https://github.com/rbenv/ruby-build?tab=readme-ov-file#clone-as-rbenv-plugin-using-git
> 
> Can someone run this and confirm it works?
> 
> ```
> git -C "$(rbenv root)"/plugins/ruby-build pull
> ```
> 
> If so, I'll add it to the Wiki!

Solved, the problem was that there was no "plugins/" folder inside .rbenv (seems like `sudo apt install rbenv ` didn't create it). 

Just run:

`git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build`

And version 3.3.0 should show up.

**Comment by munhozzlucas** [comment]
Worked for me after following rbenv repo install guide.
Adding a little note here that while the tutorial says to use `rails db:setup`, it only worked as `bin/rails db:setup`

Am now having problems with .env credentials not being passed to rails.

**Comment by zachgoll** [comment]
Awesome, thanks everyone!  Have updated the Wiki with a solution for Linux!

https://github.com/maybe-finance/maybe/wiki/Linux-Dev-Setup-Guide
