### ISSUE TITLE
Some ideas to improve `dotenv-rails` behavior :)

### ISSUE THREAD

**Issue by anthony-robin** [maybe-finance/maybe#351]
Hi guys ! Congratulation on rewriting the project from scratch, Rails is a strong framework to develop with !

Looking at the codebase, I found some points that could be improved about `env` vars. Here are my remarks:

- `dotenv-rails` should be outside of the `development` and `test` group or you won't be able to access it later in production. According to the way you load these envs in others environments you might prefer to make it available for all of them.
- `dotenv` is already a dependency of `dotenv-rails` so there is no need to keep it listed in the `Gemfile`.
- `dotenv-rails` comes with a [built in template](https://github.com/bkeepers/dotenv?tab=readme-ov-file#templates) support by command line that take the content of a `.env` and copy it into `.env.template`, replacing values by the key name (eg: `dotenv -t .env`). That might be easier to maintain instead of copy/pasting it manually.

Happy to submit a PR to update these points if you agree with it :)

**Comment by Shpigford** [comment]
The points about loading both `dotenv` and `dotenv-rails` gems are valid and need a PR.

But I'm not totally sure on the utility of having it in production.

I guess it depends on your production environment, but the gem is specifically for loading environment variables from `.env`, which shouldn't be deployed anyways.

Maybe I'm just not understanding the scenario though?

**Comment by elithecho** [comment]
Just checking out the open issues. You should not be loading any env file outside develoment/test.
Rather, use an env manager in production.

**Comment by anthony-robin** [comment]
Thank for your feedbacks :)

I understand your point on not exposing `dotenv-rails` to other environments than `development` or `test` if you have a manager that inject directly into the production release, it is indeed not necessary.
However, this is not an antipattern: as stated in [this dotenv README section](https://github.com/bkeepers/dotenv?tab=readme-ov-file#can-i-use-dotenv-in-production) some developers choose to have a `.env.staging` or `.env.production` to manage their env in other environments.

> The points about loading both dotenv and dotenv-rails gems are valid and need a PR.
I will submit a PR to remove the duplicated `dotenv` reference 👍 

Do you prefer to manage the `.env.example` manually or prefer the built in template feature ?

Thank you :)

**Comment by Shpigford** [comment]
Thanks for the PR. We'll manage .env.example manually for now.
