### ISSUE TITLE
MAC OS postgre error

### ISSUE THREAD

**Issue by Matteosco** [maybe-finance/maybe#356]
Hi I'm trying to use maybe-finance but I only get an error in terminal and it is this: 
PG::ConnectionBad: connection to server at "::1", port 5432 failed: FATAL:  role "postgres" does not exist (PG::ConnectionBad)
I can't fix it, please help

**Comment by Kieran-Dunch** [comment]
This worked for me just a few minutes ago (assuming postgresql is installed)
`createuser -s -r postgres`
`rails db:create`
`rails db:setup`

**Comment by pmareke** [comment]
As it's explained in the README, you have two options:

- Have a prostgres running on your machine.
- Use devcontainers.

**Comment by Shpigford** [comment]
Here's a walkthrough of setting it up locally on a Mac: https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide

**Comment by Matteosco** [comment]
> This worked for me just a few minutes ago (assuming postgresql is installed) `createuser -s -r postgres` `rails db:create` `rails db:setup`

thank you so much, it worked

**Comment by Matteosco** [comment]
how can I do it?

**Comment by pmareke** [comment]
> how can I do it?

You should have a button at the bottom of this page to do it.
