### ISSUE TITLE
Add Lucide icon gem

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#363]
Going forward we'll be use [Lucide](https://lucide.dev/) icons in the app.

This issue is about getting the `lucide-rails` gem installed

https://github.com/heyvito/lucide-rails

The PR should be added to the `feature/add-account` branch.

We'll be using this for most/all icons going forward.

**Comment by pmareke** [comment]
I think I can do it!

**Comment by Shpigford** [comment]
Closed with #364
