### ISSUE TITLE
Adding Additional Info to the Wiki

### ISSUE THREAD

**Issue by cmhhelgeson** [maybe-finance/maybe#367]
I've added remedies for potential issues when might encounter when going through the setup guide to a fork of the wiki hosted here: https://github.com/cmhhelgeson/maybe_wiki_fork/blob/master/Linux-Dev-Setup-Guide.md

I was wondering how I could to "pull request" or "merge" these changes into the current version of the wiki.

**Comment by zachgoll** [comment]
This is great, really appreciate the help!  Just updated the Wiki with the changes!

https://github.com/maybe-finance/maybe/wiki/Linux-Dev-Setup-Guide

**Comment by cmhhelgeson** [comment]
> This is great, really appreciate the help! Just updated the Wiki with the changes!
> 
> https://github.com/maybe-finance/maybe/wiki/Linux-Dev-Setup-Guide

I'm glad my changes were added, but this doesn't really answer my question of how I can contribute additional changes to the wiki via a pull request or a more formal contribution mechanism.

**Comment by zachgoll** [comment]
@cmhhelgeson I don't think there is a formal way to accept PRs to a Github wiki (unless I'm missing something).  I think the best way for now is opening an issue and we can get them added.
