### ISSUE TITLE
Currency drop-down addition

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#380]
We need some help creating this currency dropdown.

![CleanShot 2024-02-08 at 10 55 08@2x](https://github.com/maybe-finance/maybe/assets/35243/f84ad047-e412-4fa8-9435-8569bef3dab0)

Should use Stimulus + Tailwind to pull it off.

The view for this is `/views/accounts/new.html.erb` and is around that "balance" input field.

**Comment by varkum** [comment]
Can I take this?

**Comment by Shpigford** [comment]
> Can I take this?

Sure! We don't assign issues so our recommendation is that if you plan on working on it, create a Draft PR and regularly commit to it as you make progress.

**Comment by guillaumebriday** [comment]
You might take a look at this composant: https://www.stimulus-components.com/docs/stimulus-dropdown 

it might be helpful for what you need to do 👍

**Comment by varkum** [comment]
Thanks for the suggestion @guillaumebriday! @Shpigford thoughts on adding that or something like slim-select for a nicer looking dropdown select? Or keeping selects native?

**Comment by robzolkos** [comment]
If we're on the hunt for dropdowns it would be good to evaluate this one https://hotwirecombobox.com/  It is written by a 37signals team member, seems very well thought out.

**Comment by sarvaiyanidhi** [comment]
Some tailwind currency field reference if needed https://flowbite.com/docs/forms/number-input/#currency-input

**Comment by G2Avalon** [comment]
Lacks .tmp ?

**Comment by crolla97** [comment]
> I didn't have enough time today to implement the solution for the screen cutoff issue, so I'm open to someone else taking over this task.
> 
> To address the overflow issue, I chose to set the dropdown's position to fixed. This allows it to bypass the modal's overflow cutoff. An alternative approach involves setting the dialog element's overflow to visible. However, this method can cause problems if the modal content exceeds the modal's height, leading to overflow at the bottom. Suggestions are welcome for this solution also!
>
>Current
> <img width="1470" alt="Screenshot 2024-02-10 at 00 15 29" src="https://github.com/maybe-finance/maybe/assets/36827816/f654d949-c783-4497-9838-4046434c1b6b">
