### ISSUE TITLE
Add account form should output the type of account

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#382]
In the flow of adding an account, by the time you get to the form it should say which account type you're adding.

So if you clicked "Bank account" it should say "Add bank account", for example.

This is located in `views/accounts/new.html.erb`

![CleanShot 2024-02-08 at 12 17 07@2x](https://github.com/maybe-finance/maybe/assets/35243/64e8277f-ff5f-4734-8b8f-0f71ebac8371)

**Comment by 2000rosser** [comment]
Would I be able to give this issue a try?

**Comment by Shpigford** [comment]
> Would I be able to give this issue a try?

Anyone is welcome to submit a PR!

**Comment by Shpigford** [comment]
Closed with #395
