### ISSUE TITLE
Add hooks to ensure code quality besides Ruby Checks

### ISSUE THREAD

**Issue by tebayoso** [maybe-finance/maybe#388]
## We need GitHooks and Code Consistency rules

[This comment](https://github.com/maybe-finance/maybe/commit/4761619870d88d4366c8b5a213217a720a7b2473#r138442335) is pointing to a solution for code consistency and good practices.

a .editorconfig and some good checks on the git commit hooks should keep the code clean.

Contributors:
- @kotp

# Request
- Create a git hook to ensure git standards and good practices are followed [[Ref]](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)
- Create a .editorconfig with basic rules to ensure all editors respect the format and avoid dirty commits. [[Ref]](https://editorconfig.org/)

**Comment by MadeInPierre** [comment]
Not sure if this would be desirable (I use it in small repos), but FIY there's a [Pre-Commit GitHub Action](https://github.com/pre-commit/action) that automatically fixes PR styling and commits to the PR immediately.

Helps fix styling issues even if a contributor forgot enabled pre-commit locally.
