### ISSUE TITLE
Internationalization (i18n) Enhancement

### ISSUE THREAD

**Issue by tebayoso** [maybe-finance/maybe#389]
# Internationalization (i18n) Enhancement: Cross-State and Cross-Country Compliance

## Overview

We are at a pivotal point in the project where internationalization (i18n) is no longer a nice-to-have feature, but an absolute necessity. Our aim is to extend i18n beyond mere language translation, addressing the intricate variations in financial regulations and standards across different states and countries.

## Key Elements

- **Beyond Borders and States**: Recognizing that places like Texas and Nevada follow distinct rules, our i18n efforts must encompass not just cross-country differences but also inter-state variances within countries.

- **Comprehensive Scope**: Our focus extends to handling different currencies, types of banking institutions, and varied bank account types. More critically, we must adapt to diverse compliance regulations, including banking norms specific to each region.

- **Database Design and Rule Management**: We propose significant changes to our database architecture. This will allow for the dynamic management of region-specific rules, including the ability for users to define custom rules. For instance, setting up tax discounts applicable to specific use cases in their city.

- **Multi-Currency and Multi-Account Handling**: In the era of global bank ramps like Wise and Payoneer, users often hold multiple accounts in various currencies. Our system must seamlessly support these complexities.

- **Enforcement of i18n from the Start**: Given that Rails provides built-in helpers for many i18n aspects, we should integrate and enforce i18n standards right from the beginning of our development cycle.

## Goals

1. **Expand i18n Implementation**: Ensure that internationalization encompasses not just linguistic translations but also adapts to regional financial and compliance differences.
   
2. **Adaptive Database Structure**: Redesign our database to support dynamic rule management and regional customization.

3. **User-Defined Rule Customization**: Develop a user-friendly interface for custom rule definition, catering to localized needs.

4. **Support for Multiple Currencies and Accounts**: Integrate functionalities to handle transactions in multiple currencies and across various banking platforms.

## Call to Action

We invite contributions to this critical aspect of our project. Expertise in Rails, database management, and a deep understanding of financial compliance across different regions would be highly valuable. Let's work together to make our application truly global and compliant with diverse financial norms.

---

**Note**: This issue is open for discussions, suggestions, and contributions. Your expertise and insights can help shape a truly internationalized financial application.

**Comment by Shpigford** [comment]
Thanks! We've got i18n tooling already implemented and quite a bit of coverage already. If you see any missed text, feel free to submit a PR!
