### ISSUE TITLE
Default credentials not working

### ISSUE THREAD

**Issue by AminAlam** [maybe-finance/maybe#393]
Hi,

I can't login into the program using default provided password `(user@maybe.local - password)`. I checked the users table in the database, bit the password for the user is hashed. 

email       |                       password_digest                              
--------------------------------------+--------------------------------------+------------+-----------
user@maybe.local | $2a$12$c./n/O8q/0GmClInyWV9x.zUmyBFmxdBDm6vS8Stcv/U8/.7F4pk. 

I appreciate any help on this.

**Comment by Shpigford** [comment]
does registering for a new account work?

**Comment by AminAlam** [comment]
No, registering for a new account doesn't work neither. It also doesn't add any new rows to users table when making a new account.

**Comment by Shpigford** [comment]
Any errors in the console?

**Comment by AminAlam** [comment]
I found the fix. It's not a problem with maybe.

Error: ActionController::InvalidAuthenticityToken (HTTP Origin header (https://subdomain.domain.com) didn't match request.base_url (http://localhost:3000)):

So I have setup an nginx server to forward all the traffic for port 3000 to a subdomain, and this setup was raising an error as http traffic is being forwarded to https. 

One can solve the issue by adding the following settings to nginx config:

```nginx
location / {
                proxy_pass http://localhost:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
            }
```
