### ISSUE TITLE
Can't setup db.

### ISSUE THREAD

**Issue by HawtinZeng** [maybe-finance/maybe#410]
I am setup develop enviornment in my windows, can't excute db setup correctly, raised error as below:
![image](https://github.com/maybe-finance/maybe/assets/73981739/d5957ce8-e982-41cf-b7f2-53916dd3bfe9)

**Comment by Shpigford** [comment]
Hi! Did you happen to go through the steps mentioned in the Windows setup guide? https://github.com/maybe-finance/maybe/wiki/Windows-Dev-Setup-Guide

**Comment by HawtinZeng** [comment]
Yes, I followed this guide, but stucked in there.
![image](https://github.com/maybe-finance/maybe/assets/73981739/25bfec80-4a18-4ba3-b360-5e0a056af565)

**Comment by danielveloso09** [comment]
can you execute `rails --version`?

**Comment by JuanVqz** [comment]
Could you please try to run the `bin/setup` command? if that fixes the issue comment it in #434, thanks

**Comment by HawtinZeng** [comment]
> Could you please try to run the `bin/setup` command? if that fixes the issue comment it in #434, thanks

It works, after I three or four days' struggling, I have ran the project successfully finally, the biggest problem is bypassing GFW in WSL, BTW, I am from China.

**Comment by JuanVqz** [comment]
> > Could you please try to run the `bin/setup` command? if that fixes the issue comment it in #434, thanks
> 
> It works, after I three or four days' struggling, I have ran the project successfully finally, the biggest problem is bypassing GFW in WSL, BTW, I am from China.

I'm glad it works for you
