### ISSUE TITLE
Introduce Docker for easy deployment?

### ISSUE THREAD

**Issue by Ahacad** [maybe-finance/maybe#411]
Hi, nice project! However, I am less familiar with the ruby programming language and not so sure about how to install the dependencies. Is it possible for you to add a guide section on deployment with Docker so people can use it more easily? Thanks for the effort!

**Comment by JinnaBalu** [comment]
Created the configuration for running the application a s container https://github.com/maybe-finance/maybe/pull/416

**Comment by zachgoll** [comment]
Docker is definitely a future priority for us, but as mentioned in the [self-hosting guide](https://www.theknot.com/us/rachel-tainter-and-sam-brown-mar-2024/rsvp), we're primarily focused on getting the core of the app built out right now.

We can use #295 to track the status on this, so I'll go ahead and close this out to consolidate.
