### ISSUE TITLE
In Safari, blank modal is shown after clicking create new account button

### ISSUE THREAD

**Issue by andrisetiawan** [maybe-finance/maybe#419]
Only happens in Safari. Working fine in Chrome & Arc.

**Steps to reproduce the behavior:**
1. Use Safari browser
2. Login as `user@maybe.local` user
3. Click `+ New account` 

**Expected behavior:**
When user click `+ New account` button, it should show modal with account type options.

**Screenshot:**

<img width="887" alt="image" src="https://github.com/maybe-finance/maybe/assets/150636/ffc6e201-f667-455c-b908-bfde0e29568a">

<img width="490" alt="image" src="https://github.com/maybe-finance/maybe/assets/150636/0b009112-579d-494c-99c6-c009a637ea5f">

**Desktop:**
- Macbook Air M2
- OS Sonoma (14.2.1)
- Safari  17.2.1 
- Ruby 3.2.2

**Logs**
No error shown in console log
[gemfile.lock.txt](https://github.com/maybe-finance/maybe/files/14227644/gemfile.lock.txt)

**Comment by lynxgian** [comment]
try pulling and then running bundle install

**Comment by andrisetiawan** [comment]
#420 looks fixed this.
