### ISSUE TITLE
Add Account form Balance- field validation behaviour

### ISSUE THREAD

**Issue by Georgy5** [maybe-finance/maybe#427]
My Browsers (Firefox and Chrome) have built in validation in the Add Account form number_field that prevents me from saving a balance containing cents.
![maybe_accounts_balance](https://github.com/maybe-finance/maybe/assets/2192560/df81ce1e-8ba9-4a3c-bd12-5b0e74e71a98)

**Comment by Felipedelima123** [comment]
It is really strange a software for managing currency doesn't accept decimals. There is a PR open, that is really more complete to multi currency, but in mean time you can do just like me:

![image](https://github.com/maybe-finance/maybe/assets/20612175/9e312ec3-5cee-4661-80f0-62e58f179abe)

Added an Any step in the form field and will work properly.

**Comment by Shpigford** [comment]
Good catch! Will get that merged in to the currency stuff (which should end up in main in the next 24 hours).
