### ISSUE TITLE
Save "collapse" state of account sidebar

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#429]
The account groupings in the sidebar can be expanded/collapsed.

We need to save the "collapse" state.

What's up for discussion here is _where_ to save it.

* Database column associated with the user?
* Local storage?
* Something else?

![CleanShot 2024-02-10 at 19 40 49@2x](https://github.com/maybe-finance/maybe/assets/35243/da4c21b3-d64b-4b38-824b-35b6f25e6e88)

## Bounty
There is a $25 bounty on this. We award bounties based on first to successfully meet the scope requirements. In the event that multiple PRs are made from different people, we generally go with ones with cleanest code and test coverage (when appropriate).

We suggest submitting a draft PR as soon as you begin work on it.

**Comment by ashleypean** [comment]
@Shpigford I'm not familiar with this repo's rules around bountied issues. Can I claim this or just put up a PR for the task?

**Comment by Shpigford** [comment]
@ashleypean It's available to everyone! We generally award the bounty to the first person to complete the task. In the event of multiple submissions, we generally go to the most succinct solution.

**Comment by Shpigford** [comment]
@sergey-tyan I've awarded you the bounty!

Thank you to both @sergey-tyan and @ashleypean for working on this!

Went with #432 due to passing code brevity and passing CI.

**Comment by sergey-tyan** [comment]
thank you!
