### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by LokiWager** [maybe-finance/maybe#436]
The selected box does not contain any data and is unselectable. 

- OS: MacOS M2
- Browser: Chrome \ Safari
- Ruby version: `ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]`
- Postgresql: `psql (PostgreSQL) 14.11 (Homebrew)`
- maybe: checkout from master

<img width="573" alt="截屏2024-02-11 18 07 21" src="https://github.com/maybe-finance/maybe/assets/32408858/1df275c0-4fd8-4118-b58d-b307188b1f08">

**Comment by xiaolianggit** [comment]
running `rake currencies:seed` fixed this problem for me.

i have this in my `.env` file:
`CURRENCIES=USD`

**Comment by Shpigford** [comment]
Just pushed a fix for this. Running `rails db:seed` should fix.
