### ISSUE TITLE
Error: lucide_icon

### ISSUE THREAD

**Issue by ysw2968** [maybe-finance/maybe#437]
Hi guys, after deploying my local and typing the username and password generated by DB seed, I am facing the below error after deploying the whole repository.
Any suggestions will be appreciated.
![image](https://github.com/maybe-finance/maybe/assets/44224596/cf922340-05cf-4369-97af-a981d62370ee)

**Comment by ysw2968** [comment]
another one as well
![image](https://github.com/maybe-finance/maybe/assets/44224596/8c78ee98-a5f5-4c58-8b90-39bdba9df099)

**Comment by pmareke** [comment]
Hi @ysw2968 did you follow the setup guide and run the `bundle install` ?

**Comment by ysw2968** [comment]
Hi @pmareke , thanks for your message. 
Yes, I did run the `bundle install`.
Here are the steps  I did:
- Clone repo
- Run below commands:
   - cd/maybe  
   - cp .env.example .env 
   - bundle install
   - rails db:setup 
   - rails server 
- Open localhost:3000

Perhaps I missed some steps, very new to Ruby project.

**Comment by pmareke** [comment]
> Hi @pmareke , thanks for your message. Yes, I did run the `bundle install`. Here are the steps I did:
> 
> * Clone repo
> * Run below commands:
>   
>   * cd/maybe
>   * cp .env.example .env
>   * bundle install
>   * rails db:setup
>   * rails server
> * Open localhost:3000
> 
> Perhaps I missed some steps, very new to Ruby project. Env: Windows 11

You're not using the devcontainers, right? Would you mind to run the app with `bin/dev` instead of `rails server`?

**Comment by zachgoll** [comment]
@ysw2968 I created a guide for getting the project setup on a Windows machine:

https://github.com/maybe-finance/maybe/wiki/Windows-Dev-Setup-Guide

Would you mind re-cloning the repo into a fresh directory and following this guide?  Also, make sure your Git utility has the following setting:

```
git config --global core.autocrlf false
```

Let me know if you run into problems.

**Comment by ysw2968** [comment]
@zachgoll @pmareke thanks for your help.
I setup the project successfully by following the windows dev setup guide. Much appreciate it.
