### ISSUE TITLE
Add Section About Line Endings to Linux Troubleshooting Guide

### ISSUE THREAD

**Issue by cmhhelgeson** [maybe-finance/maybe#439]
In troubleshooting section (edit to make less verbose if you please)

**My Linux console cannot find or will not execute my shell scripts:**

Within Unix and Linux systems such as Ubuntu, shell scripts must have LF (Line Feed) line endings in order to properly execute with the terminal/console. However, if you are using Windows, depending on your development environment and Git settings, these line endings may have been converted to CRLF (Carriage Return Line Feed) line endings, which prevent your shell files from being properly executed within a Linux context.

Within the immediate, there are two options to remedy this issue:
1. Manually change the line endings of the file from CRLF to LF within your IDE of choice.
2. Install and run the dos2unix package on your troublesome file by running these commands:

```sh
sudo apt install dos2unix
dos2unix <name_of_shell_file>
```

To convert each file within your directory to LF line endings, simply run this command instead:
```sh
find . -type f -exec dos2unix {} +
```

To prevent Git from changing file line endings during the cloning or forking process, simply type in the command below. This command will prevent Git from performing any contextual conversions on the line endings of cloned files, thus preserving the files' original line endings. 

```sh
git config --global core.autocrlf false
```

Alternatively, you could run the following command instead, which simply converts any CRLF files to LF line ending files, while maintaining files which already have LF line endings.

```sh
git config --global core.autocrlf input
```

**Comment by zachgoll** [comment]
This is a great explanation of the problem at hand but would like to keep the guides as concise as possible.  So I'll go ahead and link back to this issue for those who need some additional context!

**Comment by zachgoll** [comment]
This is a great explanation of the problem at hand but would like to keep the guides as concise as possible. So I'll go ahead and link back to this issue for those who need some additional context!
