### ISSUE TITLE
Add Simple Section to Linux Guide Explaining How to Setup Postgres Password

### ISSUE THREAD

**Issue by cmhhelgeson** [maybe-finance/maybe#440]
To set the password for your postgres installation, run these commands:

```sh
sudo -i -u postgres
psql
\password postgres
<follow instructions to set password for 'postgres' user
exit
exit
```

Once these values are set, make sure these lines are present within your .env file

```
# Database Configuration
DB_HOST=localhost
POSTGRES_PASSWORD=<new password>
POSTGRES_USER=postgres
```

**Comment by cmhhelgeson** [comment]
This should help users who have installed postgres per the Linux instructions by making the connection between the postgres server and the .env file more explicit.

**Comment by zachgoll** [comment]
Awesome, added!
