### ISSUE TITLE
Build "notification" UI

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#447]
This issue is for the creation of a system-wide "notification" UI. It replaces the typical "flash" messages in Rails.

These are temporary notifications that show and disappear after 5 seconds.

## Scope

1. "Success" notification
2. "Error" notification
3. 5 second delay before disappearing (uses the "loading" icon in the Figma file)
4. Dismissible by clicking on the notification

## Design
Figma file: https://link.maybe.co/figma-notification

![CleanShot 2024-02-12 at 10 44 13@2x](https://github.com/maybe-finance/maybe/assets/35243/e0199bb9-3225-4511-aa72-87e950071c7d)

![CleanShot 2024-02-12 at 10 44 28@2x](https://github.com/maybe-finance/maybe/assets/35243/3dde6d11-c626-472e-b148-e1a082fd64d2)

## Bounty
There is a $50 bounty on this. To participate in the bounty:

1. Comment `/attempt #447` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #447` along with your general gameplan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by ibishal** [comment]
Can i get assigned @Shpigford

**Comment by adelinaenache** [comment]
Hey, new here here! Nice to meet you all:) Would like to attempt this. I can start this in 2-3 hours so that's that. /attempt #447

**Comment by crolla97** [comment]
/attempt #447

@Shpigford No access to the Figma file fyi

**Comment by Shpigford** [comment]
Sorry about the Figma file, folks! It should work now.

**Comment by Shpigford** [comment]
Thanks everyone for the work on this! Went with #449 as it was the right balance of "thorough" and "simple".
