### ISSUE TITLE
The web cannot be ran normally

### ISSUE THREAD

**Issue by QWERT1984** [maybe-finance/maybe#454]
I follow the steps to git clone the project and install it on my MacBook Pro 2014.

It has been installed successfully (I think) and I can access it on my Firefox & Chrome by localhost path.

<img width="1276" alt="image" src="https://github.com/maybe-finance/maybe/assets/30690140/0e9f9b93-856b-4165-a112-799366014e7c">

But there is no graph on the Dashboard site and the Bank account cannot be deleted.

**Comment by zachgoll** [comment]
Hey @QWERT1984!  This is expected at the moment.  We're in the middle of a big rebuild in Rails.  I wrote up an explainer of where things stand in the Wiki that is a great resource to get started:

https://github.com/maybe-finance/maybe/wiki
