### ISSUE TITLE
Are there no working versions of the softwere?

### ISSUE THREAD

**Issue by Eforen** [maybe-finance/maybe#460]
I tried getting this repo and the archive repo to work this one will not spinup and the Archive repo does not build and the old built versions of it seem to have been deleted by the way that this transition was executed...

**Comment by claudey** [comment]
@Eforen what issues are you facing? Are you able to post your logs, at least for this rails version? That can help.

**Comment by zachgoll** [comment]
@Eforen this version (Rails) should work!  The archived version also works, but requires quite a bit of setup that we're no longer supporting.  We're still very early in the build though.

I'd recommend checking out the wiki which has setup guides and an overview of where we're at with this:

https://github.com/maybe-finance/maybe/wiki

**Comment by Eforen** [comment]
@zachgoll The archived version does not work.
```
~ $ sudo docker image pull ghcr.io/maybe/maybe:main
Error response from daemon: Head "https://ghcr.io/v2/maybe/maybe/manifests/main": denied
~ $ sudo docker image pull ghcr.io/maybe/maybe-archive:main
Error response from daemon: Head "https://ghcr.io/v2/maybe/maybe-archive/manifests/main": denied
```
