### ISSUE TITLE
"You must use Bundler 2 or greater with this lockfile."

### ISSUE THREAD

**Issue by xiaoming-w** [maybe-finance/maybe#473]
hi

I had this problem in the termial when I executed "bundle update --bundler "

<img width="570" alt="image" src="https://github.com/maybe-finance/maybe/assets/43328230/18e3967c-fca7-4600-9db1-de68e7ae5868">

**Comment by zachgoll** [comment]
@xiaoming-w I think you may have a typo in your command?  Shouldn't it be:

```
bundler update --bundler
```

**Comment by zachgoll** [comment]
@xiaoming-w what version of Ruby are you using?

Check out this Mac installation guide to get the project running:

https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide

**Comment by xiaoming-w** [comment]
@zachgoll thanks
I was already following that guide for the first time installation, but it didn't work, and I tried it again, it gives me the same error, please see below:

<img width="605" alt="image" src="https://github.com/maybe-finance/maybe/assets/43328230/871002fa-8704-4a49-a696-5bb05f96e54b">

**Comment by zachgoll** [comment]
@xiaoming-w you'll need to install a Ruby version >3 to run this project.

You'll need to go back to this step - https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide#install-ruby

And when you're done, `ruby -v` should output `ruby 3.3.0`
