### ISSUE TITLE
Wiki for mac is missing key steps

### ISSUE THREAD

**Issue by lukewowo** [maybe-finance/maybe#489]
The [Mac Dev guide](https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide) is missing some key steps (this may be different on intel macOS).

OS: macOS Sonoma 14.3

macOS comes default with Ruby 2, after installing Ruby 3 you need to add the following to ~/.zshrc (or your chosen shell, but this is the default).

```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

```

After installing postgres, a user needs to be created, otherwise you see the following error when running `bin/rails db:setup`

```
connection to server at "::1", port 5432 failed: FATAL:  role "postgres" does not exist
Couldn't create 'maybe_development' database. Please check your configuration.
bin/rails aborted!
ActiveRecord::ConnectionNotEstablished: connection to server at "::1", port 5432 failed: FATAL:  role "postgres" does not exist (ActiveRecord::ConnectionNotEstablished)


Caused by:
PG::ConnectionBad: connection to server at "::1", port 5432 failed: FATAL:  role "postgres" does not exist (PG::ConnectionBad)

Tasks: TOP => db:setup => db:create
(See full trace by running task with --trace)
```

on Apple Silicon macs:  `/opt/homebrew/bin/createuser -s postgres`
I believe Intel macs are: `/usr/local/opt/postgres/bin/createuser -s postgres`

**Comment by swayamg20** [comment]
yes, I found the same issue.

***Was not able to create the db even after installing postgreSQL.***
		Soln: [Stackoverflow](https://stackoverflow.com/questions/7863770/rails-and-postgresql-role-postgres-does-not-exist) 
		command: bin/rails db:setup
		error: `PG::ConnectionBad: connection to server at "::1", port 5432 failed: FATAL:  role "postgres" does not exist`
		
		
		`createuser -s -r postgres` this worked for me.

**Comment by zachgoll** [comment]
Thanks!  Have updated the guide with a note about creating the user via the `createuser` command.

In regards to the `$PATH` variable, I believe if you install via Homebrew as suggested in the guide, the formulae should automatically be loaded to your path.  Did you install `rbenv` through Homebrew?

**Comment by swayamg20** [comment]
Yes I installed `rbenv` via homebrew. 

Yes, it was already loaded to my path so I didn't put the path.

**Comment by zachgoll** [comment]
Great!  Closing this out—guide has been updated.

**Comment by karanj** [comment]
For what it's worth, doesn't look like wiki got updated to me. The key part was about updating the shell path - without that the rbenv global setting has no effect no default Ruby.
