### ISSUE TITLE
Is Ngrok required to develop?

### ISSUE THREAD

**Issue by coltonehrman** [maybe-finance/maybe#51]
I am seeing these errors when running locally without any Ngrok setup (I never set an auth token for ngrok).

Errors:
```
[ ready ] on http://localhost:4200
error: server: unhandled promise rejection: [object Promise]: Error: connect ECONNREFUSED ::1:4551
error: server: unhandled promise rejection: [object Promise]: Error: connect ECONNREFUSED ::1:4551
error: server: unhandled promise rejection: [object Promise]: Error: connect ECONNREFUSED ::1:4551

error: [default-express-handler] connect ECONNREFUSED ::1:4551 {"request":{"method":"POST","url":"/v1/plaid/sandbox/quick-add"},"stackTrace":"Error: connect ECONNREFUSED ::1:4551\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)","user":"clrdtjey40000wizwzyb7hdxo"}
```

**Comment by Shpigford** [comment]
It depends on the service. We used Ngrok because a lot of services required having an HTTPS webhook endpoint to work with.

Ultimately we will need to come up with _some_ sort of SSL solution as most webhooks from 3rd-parties will require it for sending banking data.

**Comment by tmyracle** [comment]
I believe it'll be required for various webhook related things (Stripe,etc) as they typically require https. Shouldn't be a blocker until we start digging into those things. 

EDIT: what he said ☝️

**Comment by coltonehrman** [comment]
> It depends on the service. We used Ngrok because a lot of services required having an HTTPS webhook endpoint to work with.
> 
> Ultimately we will need to come up with _some_ sort of SSL solution as most webhooks from 3rd-parties will require it for sending banking data.

Makes sense. I suggest a reverse proxy (ie: nginx) or something simple to get setup in front of the app to resolve SSL connections. I assume that is in parity with how it is deployed in non-dev environments.

**Comment by coltonehrman** [comment]
Is it suppose to startup with docker-compose when the AUTH_TOKEN is added? I can't seem to get it to start.

**Comment by coltonehrman** [comment]
Ah wait, nvm. I see it's not apart of the services profile. I got it to run with `COMPOSE_PROFILES=services,ngrok docker-compose up -d`

**Comment by mohammed90** [comment]
> something simple to get setup in front of the app to resolve SSL connections

If I may, I suggest you use https://github.com/caddyserver/caddy, which can provide [automagic HTTPS](https://caddyserver.com/docs/automatic-https) for all environments, including localhost.

Disclaimer: I'm a member of the Caddy team and personally eyeing this project for personal use.

**Comment by zevisert** [comment]
Something else I've seen done that could be helpful with this is registering an A record on a subdomain (in this case something like local-loopback.maybe.co) that resolves to 127.0.0.1. You'd then obtain a valid TLS cert (from eg letsencrypt via dehydrated) and  commit both the public cert and private (I know!) keys. Afaik it's not a vuln to have a private key that verifies a domain that is local routable only. 

That way, a simple nginx server can start up and you'd be able to access the dev server with HTTPS (and use service-worker, navigator.clipboard, etc) without asking people to add certs to their computer's trusted certificate store.

**Comment by anthonyshew** [comment]
Possibly helpful: Next.js currently has an `--experimental-https` flag for the development server. If the webhooks could be brought into the Next.js application, they would end up available at `https://localhost:3000/api/webhooks/...` (or wherever you'd like to locate them) alongside the rest of the application.

**Comment by Shpigford** [comment]
We're going with ngrok and will have instructions on that via #85 soon.
