### ISSUE TITLE
Add inline category selection

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#526]
This issue will allow a user to select or change the category of a transaction, inline.

![CleanShot 2024-03-10 at 17 44 07](https://github.com/maybe-finance/maybe/assets/16676157/2da3117e-7775-43ac-9fed-9131f0527fae)

## Scope

- User should see category in transactions view
- User should be able to click on a category to open a dropdown
- Selected category should have checkmark
- If transaction category is `nil`, should show "Uncategorized" 

### Not in scope

We can add a `cursor-not-allowed` for each of these:

- Search bar is a placeholder
- "Add new" is a placeholder
- "Edit" ellipses is a placeholder

Each of these will likely warrant an entire PR that I'll open up when this issue is completed.

### Design file

Here is the relevant frame for this issue:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-Design-(Community)?type=design&node-id=2003-697&mode=design&t=NUcLxlwf8nbQWWgh-0

**Comment by jakubkottnauer** [comment]
Working on this now
