### ISSUE TITLE
Add basic transaction pagination

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#527]
This issue is for implementation of basic pagination for the transactions page.

## Requirements

- Pages should be 50 transactions
- Use `pagy` gem for pagination

## Designs

![CleanShot 2024-03-07 at 15 07 55](https://github.com/maybe-finance/maybe/assets/16676157/b01e6f5b-8584-481f-bfea-0e841a2ad671)

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-Design-(Community)?type=design&node-id=2029-351&mode=design&t=6PQ6Z4g5zUQuwZSu-0

**Comment by moreaujean** [comment]
I'd like to pick this up.
