### ISSUE TITLE
Implement basic transaction search filtering

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#528]
This issue is for allowing the user to search for transactions.

## Requirements

- Configure `ransack` (we will use this for additional filtering and sorting)
- Search should be automatic (form submits as user types)
- Search should use debouncing 
- Search should do basic full text search against `Transaction.name` (future issues will expand this to searching _across_ fields)
- If nothing found, empty state should show

## Designs

![CleanShot 2024-03-07 at 15 24 33](https://github.com/maybe-finance/maybe/assets/16676157/b099e0f8-1d8e-40f1-8e6b-6b4e694aa8fb)

See the Figma file here:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-Design-(Community)?type=design&node-id=2030-1200&mode=design&t=6PQ6Z4g5zUQuwZSu-0

**Comment by Chocksy** [comment]
I will take this one. Will have a PR in a few.
