### ISSUE TITLE
Add a port to x86 architecture

### ISSUE THREAD

**Issue by MaitreGEEK** [maybe-finance/maybe#535]
tailwindcss is not ported on x86 architectures so we can't run it on older CPUs
![image](https://github.com/maybe-finance/maybe/assets/90345438/dde069fd-4b20-49b5-bcb4-267eeaffed94)

**Comment by henrikbjorn** [comment]
@MaitreGEEK I think this should be opened on the tailwindcss repository and then the tailwindcss-rails repository to get it included for rails also

**Comment by MaitreGEEK** [comment]
Ok, no problem I will ask them

**Comment by zachgoll** [comment]
Closing as I think @henrikbjorn's suggestion is the best next step here.
