### ISSUE TITLE
Add forgot password flow

### ISSUE THREAD

**Issue by tmyracle** [maybe-finance/maybe#54]
Auth0 previously provided this functionality. We'll need to do a few things to replace that, off the top of my head:

- Update sign in page with "Forgot password?" link
- Add forgot password UI to capture email and show confirmation once forgot password email is sent
- UI for specifying new password after clicking link in forgot password email
- Generate token and handle token validation for sending email and when user clicks on the link in the forgot password email
- Update server for handling sending the emails

This is low priority for right now.

**Comment by sy425191** [comment]
I would like to work on this

**Comment by Neumand** [comment]
Same, I'd love to help on this

**Comment by Shpigford** [comment]
Whoever would like to work on, go for it. Generally speaking, if you start working on, create a draft PR to show your progress.

That can help reduce multiple people working on the same issue.

**Comment by eneskaya** [comment]
I'm still on it, please see #117 . Having a hard time testing with Postmark, though. Can't send an email to my private address 😅 Probably need to set up an own domain so I can test this. 

What's missing now is:

- UI for actually resetting the email + hooking it up with the BE to do the reset

<img width="589" alt="Bildschirmfoto 2024-01-20 um 16 41 33" src="https://github.com/maybe-finance/maybe/assets/964419/1dfd6a41-e988-4d4b-b1f0-54b2791ea3a4">

<img width="536" alt="Bildschirmfoto 2024-01-20 um 16 41 46" src="https://github.com/maybe-finance/maybe/assets/964419/adf88fc0-9a8c-42b8-aaea-4534db6a0ff9">

**Comment by tmyracle** [comment]
@eneskaya are the email templates managed in Postmark itself? I can't seem to find any in the repo and looks like its just referencing them by id. Might make sense to move to something like [React Email](https://react.email/docs/introduction) so that the templates are in source control and you can style them with React and Tailwind. They also play nice with Postmark, Resend, Nodemailer, SendGrid, Plunk, and AWS SES

**Comment by Shpigford** [comment]
There were indeed templates managed in Postmark, but we closed that account so lost access to them. :(

**Comment by eneskaya** [comment]
> @eneskaya are the email templates managed in Postmark itself? I can't seem to find any in the repo and looks like its just referencing them by id. Might make sense to move to something like [React Email](https://react.email/docs/introduction) so that the templates are in source control and you can style them with React and Tailwind. They also play nice with Postmark, Resend, Nodemailer, SendGrid, Plunk, and AWS SES

That is a very good point. Right now I'm setting a raw text body, but wanted to bring up whether having the templates in the code base wouldn't make more sense. React Email would be a perfect candidate here, I agree! I will add it. 

The issue still remains though with local testing, but we could wait with that until we have SMTP support, which would make testing easier.

**Comment by tmyracle** [comment]
@Shpigford do you happen to have screenshots/examples?

![rebuild](https://github.com/maybe-finance/maybe/assets/1218724/1b862bc4-12c6-4351-9871-7b5833e4ee8e)

**Comment by Shpigford** [comment]
@tmyracle Been digging a bunch and can't find anything. :( Will keep looking, but not looking great.

**Comment by eneskaya** [comment]
@tmyracle Where exactly would you put the email templates?

**Comment by tmyracle** [comment]
@eneskaya depends on what we decide to use for templating moving forward, my vote would be for React Email mentioned above since you can write emails as react components and it takes care of cross-client support and generating the html for you. Might have to put this on pause until we get a templating solution in place.

**Comment by eneskaya** [comment]
> @eneskaya depends on what we decide to use for templating moving forward, my vote would be for React Email mentioned above since you can write emails as react components and it takes care of cross-client support and generating the html for you. Might have to put this on pause until we get a templating solution in place. 

I was talking about where to put them in the monorepo 😁 But let me create a new issue for the email templates, and we can discuss there

**Comment by tmyracle** [comment]
Not relevant anymore
