### ISSUE TITLE
Accounts `by_group` should omit empty groups, render empty UI

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#558]
Currently, if user has not created any accounts, they see this dashboard screen:

![CleanShot 2024-03-20 at 13 04 41](https://github.com/maybe-finance/maybe/assets/16676157/17170744-5a3e-4708-ae8e-d46dce41b249)

### Empty State

If there are no accounts, dashboard should probably show something like what we have for accounts page:

![CleanShot 2024-03-20 at 13 06 18](https://github.com/maybe-finance/maybe/assets/16676157/5083e3ba-791c-4a7d-ac5f-3832224edc4e)

### Partial Empty State

If the user has a few accounts, but doesn't have an account for each `Accountable` type, we should show a "No accounts" message:

![CleanShot 2024-03-20 at 13 07 53](https://github.com/maybe-finance/maybe/assets/16676157/c5a43f04-85e0-44d9-af0e-4fb4deb5a4d8)

And finally, if the entire group (i.e. "liabilities") has no accounts, we should probably show a "No [group] yet" message:

![CleanShot 2024-03-20 at 13 09 52](https://github.com/maybe-finance/maybe/assets/16676157/56bef039-e5a1-449f-9fa7-beac536a2bb3)

**Comment by zachgoll** [comment]
Here's where everything is being grouped:

https://github.com/maybe-finance/maybe/blob/c7b336de45dede880e540720642ed67ce45ede9a/app/models/account.rb#L46-L61

And to fix this, we could probably add an `empty?` method on the `ValueGroup` class:

https://github.com/maybe-finance/maybe/blob/c7b336de45dede880e540720642ed67ce45ede9a/app/models/value_group.rb#L37-L40

Something like:

```
def empty?
  value_nodes.empty?
end
```

**Comment by claudey** [comment]
@zachgoll I think #707 fixes the first part of this issue, the Empty State problem to address.

**Comment by zachgoll** [comment]
@claudey you are correct, I'll go ahead and close this issue out.

This was for a prior version of the UI, so I think #707 actually addresses all of it!
