### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by gregmolnar** [maybe-finance/maybe#560]
Since this app holds financial information, it should take security seriously and based on quick glance I found a bunch of things you could improve:

- Checking for vulnerable dependencies twice a day. There is a weekly dependabot, but I recommend a `bundle audit` check twice a day, or a more frequent dependabot check maybe for security issues only if it let's you configure that. Also, there are javascript dependencies via importmap, it has an auditing tool built in: https://github.com/rails/importmap-rails?tab=readme-ov-file#checking-for-outdated-or-vulnerable-packages
- Mandatory 2FA
- Rate limiting on the authentication endpoints. Currently passwords could be brute-forced, sprayed.
- Increase password complexity from the default
- Validate leaked passwords
- Encrypting some of the sensitive fields in the database. Active Record makes that easy, although if you need to search the data, it might introduce challenges.
- A security policy describing what channels you want security issues to be reported on, how do you handle them, how do you notify the users of the app, etc

There are probably others since I just had a quick glance.

**Comment by zachgoll** [comment]
Agree, security is definitely a high priority due to the nature of this app.  We're still a few weeks/months away from a hosted version, but definitely will want to implement at least some portion of these suggestions before go-live.

I think these could probably be split into individual issues, which I can circle back to when we get closer to go-live or you're more than welcome to open up and work on now!

**Comment by gregmolnar** [comment]
> definitely will want to implement at least some portion of these suggestions before go-live

If you want that SOC compliance that was mentioned somewhere, you will need a lot more than these.

> you're more than welcome to open up and work on now!

I won't use this app myself, so don't see a reason to contribute.

**Comment by Shpigford** [comment]
Closing as too broad. Can be re-opened as a discussion (instead of an issue).
