### ISSUE TITLE
Request: make the app port part of env config

### ISSUE THREAD

**Issue by karanj** [maybe-finance/maybe#565]
Since the default port 3000 clashes with Grafana's default port, and I don't particularly want to mess with my existing Grafana setup, I had to change the config and code in a few places to allow me to start up the dev container without clashing with Grafana occupying port 3000.

Suggestion is to make the app port a config item in the .env file to enable easy changing of this attribute for those running with complex setups.

**Comment by claudey** [comment]
@zachgoll Are you able to close this since #726 has been merged?

**Comment by zachgoll** [comment]
@claudey yep, closing it out!

In the future, you can [reference an issue in the PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and it will automatically close on merge.

**Comment by claudey** [comment]
Thanks, noted.
