### ISSUE TITLE
Allow user to search transaction categories list

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#573]
## Overview

Currently, there is a disabled UI placeholder for transaction category searching.

This issue will allow the user to type to search for a category:

![CleanShot 2024-03-26 at 14 46 05](https://github.com/maybe-finance/maybe/assets/16676157/16f835e5-ceea-46b2-b7a4-fdfc83a23490)

## Requirements

- Search should be debounced (see [this file](https://github.com/maybe-finance/maybe/blob/main/app/javascript/controllers/transactions_search_controller.js) for a good reference)
- Search should perform a full text search on the category name (we have `ransack` Gem setup, but may not be needed for this due to simplicity)
- Search can be cleared with browser native search controls
- When no results found, add a "No categories found" message in the UI

### Out of Scope

This issue will NOT cover:

- Category create/edit/delete actions (this is covered in #572)

## Designs

The designs are already implemented for this.  You can reference [this Figma file](https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2410-1384&mode=design&t=U1FgrK5nHhTYyk1W-0) for additional context.

**Comment by mattia-malnis** [comment]
I'm working on this!
