### ISSUE TITLE
Unable to create account

### ISSUE THREAD

**Issue by kartikay-agarwal** [maybe-finance/maybe#58]
I have cloned the latest repository, set the NEXTAUTH_SECRET, and followed the commands given on https://github.com/maybe-finance/maybe?tab=readme-ov-file#building-the-app

these are the following errors i have encountered

![image](https://github.com/maybe-finance/maybe/assets/73934694/f7e11344-cbf4-4df2-96b2-95e06f69f0ad)
![image](https://github.com/maybe-finance/maybe/assets/73934694/1e27b692-27d3-4629-bf40-faaf8ad161c0)

along with that, i am also unable to make account on it, it works till sign up, takes in all the details and then gives out this error

<img width="484" alt="image" src="https://github.com/maybe-finance/maybe/assets/73934694/3d7e3dbf-6e27-45a9-835b-d7b934e97d8c">

these are my server specifications

AWS server
ubuntu 20.04
intel cpu

all ports are open but still was inaccessible directly through the ip so used ssh tunneling to access it using localhost

**Comment by Shpigford** [comment]
The JWT_SESSION_ERROR is basically exactly the error you get if `NEXTAUTH_SECRET` is missing.

Feels like something may be breaking down with how it's getting deployed or run on the server?

**Comment by kartikay-agarwal** [comment]
Ok so i just tried to open it will port 4200 and 3333 using ssh tunnelling and it is working fine. The only country allowed is United States and not other countries so changed it and used with model data.

**Comment by Shpigford** [comment]
> The only country allowed is United States and not other countries so changed it and used with model data.

@kartikay-agarwal That was addressed in a merged PR a few hours ago. Grabbing latest codebase should address this.
