### ISSUE TITLE
Implement "Partial Account Sync" Logic

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#584]
## Overview 

Currently, the app can call `@account.sync_later` ([see this file](https://github.com/maybe-finance/maybe/blob/7fa77b4fd7ecf9b51f16f335ee7c67dd7f2b0282/app/models/account/syncable.rb#L8-L21)), which will do the following:

1. Fetch and save exchange rates needed to sync the account
2. Search through the account's valuations and transactions and _accumulate_ daily balances
3. Save balances in both the account and family currency (if needed)

This sync process is triggered on every Create/Update/Delete of both `Transaction` and `Valuation` right now, which means even if a `Valuation` dated _yesterday_ is updated, the job will sync _all_ historical balances.

The goal of this issue is to implement "partial" syncs given a `start_date` so we can only calculate and update balances that were affected by the change (i.e. if I change the balance of a `Transaction` yesterday, we only need to sync the last 2 days balances)

## Requirements

- [Sync](https://github.com/maybe-finance/maybe/blob/7fa77b4fd7ecf9b51f16f335ee7c67dd7f2b0282/app/models/account/syncable.rb#L8-L21) should take a `start_date` param
- On `CREATE` and `UPDATE` of both `Valuation` and `Transaction`, the `start_date` is equal to the date of the `Valuation` or `Transaction`
- On `DELETE` of `Valuation`/`Transaction`, the `start_date` will be equal to the _prior_ record's date

**Comment by jakubkottnauer** [comment]
on it!
