### ISSUE TITLE
Extend `shared/notification` partial to allow persistent notifications with action buttons

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#597]
As part of #596, we will need to create notifications that are _persistent_ until the account sync completes:
![CleanShot 2024-04-02 at 21 15 52](https://github.com/maybe-finance/maybe/assets/16676157/eacee004-7249-4280-985c-92b5a2d33444)

## Requirements

- `shared/notification` should accept `options[:auto_dismiss]`, which should default to true.  When false, notification is persistent until explicitly removed or a page refresh.
- `shared/notification` should be able to accept arbitrary content that provides a "dismiss" or custom action button:

![CleanShot 2024-04-03 at 10 10 27](https://github.com/maybe-finance/maybe/assets/16676157/6a4019b2-5dc3-4f50-a17c-67c40f67174b)

## Designs

See the link below:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2568-2224&mode=design&t=XdQIQAEd4nZtUHfU-0

**Comment by ThibautGrx** [comment]
I'm working on this!

**Comment by ThibautGrx** [comment]
We keep the spinner ? When we click on it, it closes the notification. Do we keep this behavior ?
![image](https://github.com/maybe-finance/maybe/assets/35230028/5f090e1a-dbed-41a3-af9a-015eeef8cf29)

**Comment by zachgoll** [comment]
@ThibautGrx I think we can remove that behavior and replace with explicit "dismiss" buttons.
