### ISSUE TITLE
Build sidebar portfolio listing

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#6]
![CleanShot 2024-01-02 at 13 44 32@2x](https://github.com/maybe-finance/maybe/assets/35243/18c4470b-c122-4802-93a6-1f136a493ce5)

Note: You do *not* have to build the actual account outputs. This is primarily about stubbing out the frontend visuals.

Scope:
1. "Total portfolio" block
2. Portfolio listing
3. "New portfolio" link (link_to is `new_portfolio_path`)

Figma file: https://www.figma.com/file/rAn2k5U86nXZmBixAEsjdN/Shell?type=design&node-id=0%3A1&mode=design&t=0q11JqWuYDnEcFDH-1

**Comment by jespr** [comment]
PR on it's way!
