### ISSUE TITLE
Log out flow is broken

### ISSUE THREAD

**Issue by portovep** [maybe-finance/maybe#604]
Hey folks,

I was playing with the project over the weekend and I noticed that the log out functionality is broken. I get the following error:

<img width="1044" alt="image" src="https://github.com/maybe-finance/maybe/assets/2892293/2a23d966-18af-49ae-b6e2-fde93c515cc7">

I try to provide a fix in #603. Let me know if it makes sense.

Thanks, an keep the great work! I really like the project.

**Comment by zachgoll** [comment]
#603 merged, thanks for the report!  Closing out.
