### ISSUE TITLE
Update broken bank/institution image location

### ISSUE THREAD

**Issue by montogeek** [maybe-finance/maybe#61]
Right after successful registration the First Account page is missing bank icons:
![image](https://github.com/maybe-finance/maybe/assets/1002461/3c64d01d-2c4b-4bcc-bd68-6451ec2219b1)

Because they point to dead URLs.

Do you still have them? I can add them.

**Comment by Shpigford** [comment]
Yes, I have them. Will have them available soon via our Synth API (https://docs.synthfinance.com). Aiming for this week.

**Comment by Shpigford** [comment]
Revisiting this...all of these broken icons are pointing to a now-defunct `assets.maybe.co` URL (which is S3-hosted assets).

We should host them as part of the app instead.

I've attached a zip of all the necessary image files.

[financial-institutions.zip](https://github.com/maybe-finance/maybe/files/13942291/financial-institutions.zip)

Also, the images in `InstitutionGrid.tsx` will need to be accounted for as well (they're also in the zip).

**Comment by pablo-kitz** [comment]
Willing to handle this!

**Comment by Shpigford** [comment]
@pablo-kitz You're welcome to! We don't assign issues. Simply submit a PR with your work. It's fine if it's a Draft PR that you update as you make progress.
