### ISSUE TITLE
Feature: Add transaction modal flow

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#629]
## Overview

This feature enables a user to add new transactions to an account, individually:

![CleanShot 2024-04-15 at 13 41 51](https://github.com/maybe-finance/maybe/assets/16676157/8fe25663-7f5d-4998-8e07-8bb1522096cd)

## Requirements

- [ ] User can click button on transaction page to open a modal
- [ ] User can click on button on account page
  - [ ] Account dropdown is pre-filled in this scenario
- [ ] Modal has a radio group of `Expense`, `Income`, `Transfer`
  - [ ] Transfers are NOT part of this issue.  A `cursor-not-allowed` class should be applied to the "Transfer" button and implementation should be _skipped_
- [ ] If "Expense", amount value is saved as a _positive_ value in the DB.  If "Income", amount is saved as _negative_ value in DB.
- [ ] Form uses native HTML input elements (no custom select or datepickers needed here)
- [ ] Form submit should be handled correctly (all fields should be required):
  - [ ] If missing fields or validation errors, modal stays open, no alerts
  - [ ] If successful submit, app shows success notification
  - [ ] If error, app shows error notification
- [ ] I18n translations are provided

## Design

You can find all the design specs below:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2664-225&mode=design&t=p9lOop61MfLabHUV-0

## Bounty
There is a $250 bounty on this. To participate in the bounty:

1. Comment `/attempt #629` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #629` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by mehulmathur16** [comment]
Hi @zachgoll, can I be assigned ?

**Comment by Shpigford** [comment]
> Hi @zachgoll, can I be assigned ?

Hi @mehulmathur16! Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone at the moment.

**Comment by Ekep-Obasi** [comment]
I'd like to attempt this
 /attempt #629

**Comment by JoshAntBrown** [comment]
Hey @zachgoll is there a reason why the Expense, Income and Transfer buttons should use the tabs controller? 

I don't know what the intention is for Transfer, but Income and Expense look like they might be better suited as a pair of radio buttons which then manipulate the value in the controller action. Both appear to have the exact same set of fields and UI elements.

**Comment by zachgoll** [comment]
@JoshAntBrown yep, I think you're right on this one, will get the description updated!

Essentially the choice of income/expense/transfer (when implemented) is to determine the _signage_ of the transaction amount, so probably easiest with a radio input

**Comment by josefarias** [comment]
Will make an attempt later tonight. Glad these are back! They're fun /attempt #629

**Comment by therealtimex** [comment]
Can user attach receipt files in a transaction?

**Comment by zachgoll** [comment]
@therealtimex not right now, but yes, this will be supported in the future.
