### ISSUE TITLE
Add custom template when `allow_browser` blocks a browser

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#637]
Currently, we're showing a generic error message when a browser is blocked, making it hard to debug self-hosted apps:
![image](https://github.com/maybe-finance/maybe/assets/16676157/b5a8c6a9-02cb-43bb-93cf-7f8c860aa66b)

We should add a custom `public/406-unsupported-browser.html` file to give the user more feedback.

This recently went into Rails `main` and used to be `public/426.html` - https://github.com/rails/rails/pull/51545

**Comment by adrienpoly** [comment]
The current setting is

```
allow_browser versions: :modern
```
I wonder if this is something you want to keep like that? 

The main limitation is for Safari which is not evergreen and the current requirement is 17.2 with `:modern`, [source](https://github.com/rails/rails/pull/50505#issuecomment-1894692819) 

Here are the real world usage for Baseamp 

https://x.com/dhh/status/1783888747769250255

**Comment by zachgoll** [comment]
@adrienpoly I don't have a super strong opinion on this one.  As long as we're not spending significant dev hours trying to research and support differences across browsers, I'd be open to making this less restrictive.

What setting would you recommend?

**Comment by adrienpoly** [comment]
@zachgoll I don't have a strong opinion either. I wouldn't be worried about Chome/Firefox version as they are evergreen but more about Safari. Looking at Basecamp data it feels like only 56% of their Safari users would be able to access the site with the current configuration.

I am unsure what is the typical user of your solution when it is live but as it is personal finances I believe lots of users won't be as techy as we (developers) are and could easily run an older version on their mac at home.

Also it depends when the release date is scheduled for. As explained in the PR this is a proposed setting for Rails 8 that is not released right now. By the time it is released maybe the usage stats will be much different.

**Comment by zachgoll** [comment]
@adrienpoly yeah I think Safari >= 16 would be reasonable, and then keep the "modern" version requirements for the remaining browsers.
