### ISSUE TITLE
Remove location limitation

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#64]
As referenced in #60, we need to remove the blocker for folks outside the US.

> When we built Maybe we offered financial advice and as such had a LOT more regulatory stuff to account for. So, that just meant we couldn't support non-US folks.
> ...
> The problem will still be that we have to add data sources for folks outside North America, but otherwise you should still be able to actually create an account and manually add stuff.

There are some checks during signup/onboarding where it asks for location and then if you don't select United States it shows you a message about not being supported.

We need to remove that so there's no "location" limitation.

**Comment by TomerMelnik** [comment]
Would love to help. assign to me if you'd like.

**Comment by tmyracle** [comment]
> Would love to help. assign to me if you'd like.

Not really any assigning here. Just fork, make the changes, and submit a PR mentioning this issue 👍

**Comment by sy425191** [comment]
@Shpigford have a look to recent PR where I removed the location checks, so guys from outside US can also access the app

**Comment by Neumand** [comment]
> Should i need to comply the code with selected country states also? I mean there are only US states available, what about the others country states?

I wonder if we should remove the state selector altogether for now.
