### ISSUE TITLE
Improvement: D3 Line Chart Styles and Formatting

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#643]
![CleanShot 2024-04-18 at 11 18 01](https://github.com/maybe-finance/maybe/assets/16676157/7c8c2196-5a19-4660-ac79-7282a43a2dbc)

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2770-226&mode=design&t=Y0hF2UeUXaOhxGL4-0

## Overview

The current D3 line chart (`line_chart_controller.js`) we are using is lacking several design aspects and features.  This issue is dedicated to getting this chart to a near-"final" state.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

### Functional Requirements

- [ ] Currently, we have a `trendline_controller.js` and a `line_chart_controller.js`.  We should consolidate these into a single `line_chart_controller` that is configurable.  Options will include:
  - [ ] Hide or display x-axis labels ("trendlines" have no axis) - show by default
  - [ ] Enable or disable tooltips ("trendlines" have no tooltip) - enable by default
- [ ] The chart controller will always receive a `TimeSeries.new([]).to_json` value, which can be an instance of `Money` or a regular integer (this is already implemented).  As part of this issue, we need to make sure the chart can handle both `Money` values and regular integers (including percentages) in the tooltip.
- [ ] When the chart is supplied with a **single value** or an "empty" Time Series (i.e. `TimeSeries.new([])`), it should display the "empty" state design.

### Design Requirements

- [ ] Implement gradient underneath the line (very subtle, see designs)
- [ ] Ensure padding and spacing matches designs
- [ ] When the _overall_ trend of the series that is passed to the line chart is "bad" (decreasing for an asset, increasing for a liability), the chart should go from a green color to a red color.
- [ ] When hovering over a data point in the chart, the line should highlight for dates prior to it, and the line after it should be grayed out

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- Be sure to read through [time series code](https://github.com/maybe-finance/maybe/tree/main/app/models/time_series) as it will help conceptualize things for this issue
- In Maybe 1.0, we had the gradients implemented using a "Zero Point Gradient" trick with D3.  The code linked below is written in React/Visx (a wrapper around D3), but it may help give some ideas on how to achieve the gradient.
  - https://github.com/maybe-finance/maybe-archive/blob/04bf3d135bdbb1fdaa2dd669dca4738c797cc382/libs/client/shared/src/components/charts/time-series/Line.tsx#L67-L104

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $250 bounty on this. To participate in the bounty:

1. Comment `/attempt #643` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #643` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by ezhil56x** [comment]
Can I get assigned?
/attempt #643

**Comment by Shpigford** [comment]
> Can I get assigned? /attempt #643

Hi @ezhil56x! Due to the speed at which we're moving at the moment, we don't assign issues.

**Comment by syedbarimanjan** [comment]
@ezhil56x are you working on it?

**Comment by ezhil56x** [comment]
> @ezhil56x are you working on it?

Feel free to take up!

**Comment by josefarias** [comment]
I'll make a time-boxed attempt tonight. /attempt #643

**Comment by syedbarimanjan** [comment]
> I'll make a time-boxed attempt tonight. /attempt #643
> 
> [Algora profile](https://console.algora.io/@/josefarias)	Completed bounties	Tech	Active attempts	Options
> @josefarias	2 maybe-finance bounties	
> Ruby, CoffeeScript,
> TypeScript & more
> [Cancel attempt](https://console.algora.io/api/bounties/clv5g8d030004jt0cwmpbq7ja/cancel-attempt)

I am also working on it.

**Comment by josefarias** [comment]
Couldn't get to this tonight. Maybe tomorrow, if still open 😄

**Comment by syedbarimanjan** [comment]
@zachgoll @Shpigford is there some dummy database or data which I can use to test adding it manually will take alot of time.

**Comment by zachgoll** [comment]
@syedbarimanjan yes, you can use the `rake demo_data:reset` task to generate some sample accounts with time series data locally.

**Comment by zachgoll** [comment]
Just an FYI for those working on this bounty—I'll be out today but will be available to review bounty submissions either late tomorrow or first thing Monday morning.

**Comment by zachgoll** [comment]
Done via #657
