### ISSUE TITLE
Feature: Build D3 pie chart for asset/debt allocation in dashboard view

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#644]
![CleanShot 2024-04-18 at 11 19 00](https://github.com/maybe-finance/maybe/assets/16676157/2127c376-4ccf-485a-8a83-15d1842be2fc)

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2770-305&mode=design&t=Y0hF2UeUXaOhxGL4-0

## Feature Overview

Create a `pie_chart_controller.js` that can be used on the dashboard to show asset and debt allocation.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] Create a `pie_chart_controller.js` that can accept a value which includes a `value`, `color`, `percent_of_total`, and `label`.
- [ ] Implement the [_allocation_chart.html.erb](https://github.com/maybe-finance/maybe/blob/main/app/views/pages/dashboard/_allocation_chart.html.erb) partial with live account data
- [ ] When not hovering chart, overall value should show
- [ ] When hovering over chart, the closest segment to the mouse should be highlighted and the rest grayed out
  - [ ] Value in middle of circle should show currently highlighted segment details

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- For now, this will be used in the dashboard, but ideally we make it reusable anywhere
- We already have the concept of account "groups" in the app, which does a lot of the heavy lifting around allocation %, grouping, etc.  Here is some good code to read through:
  - [Where accounts are grouped](https://github.com/maybe-finance/maybe/blob/f5f624881f3b8900fa56d655ec040b5ee5d8a0af/app/models/account.rb#L68-L85)
  - [ValueGroup](https://github.com/maybe-finance/maybe/blob/main/app/models/value_group.rb)

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $100 bounty on this. To participate in the bounty:

1. Comment `/attempt #644` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #644` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by webbdays** [comment]
@syedbarimanjan 
are you still on this?

**Comment by syedbarimanjan** [comment]
@webbdays if you want to give it a shot go on I am working on another one for the moment.

**Comment by webbdays** [comment]
ok. Thank you. I will try.

**Comment by syedbarimanjan** [comment]
I will be working on this.

**Comment by webbdays** [comment]
ok.

**Comment by syedbarimanjan** [comment]
I have implemented half of the features will create the draft pr and add a video.
