### ISSUE TITLE
Feature: Implement income and spending insight cards for dashboard

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#645]
![CleanShot 2024-04-18 at 11 37 41](https://github.com/maybe-finance/maybe/assets/16676157/978a0e60-41da-4aa4-aeb7-9b624d8f569e)

## Feature Overview

This issue is for completing the "income" and "spending" insight cards that are located on the dashboard.

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2770-1101&mode=design&t=Y0hF2UeUXaOhxGL4-0

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] Should generate a time series of income and spending for a `Family`, scoped to `Period.last_30_days` (see "suggestions" section below for more detail)
  - [ ] Each data point in the series represents a "Trailing 30 day sum" of income (negative transaction values)
  - [ ] The "headline" number shows the last value in the series
  - [ ] The "trend" value is the overall time series trend
- [ ] Should find the top 3 accounts with the _most_ income or spending within the last 30 days and display the sum
  - [ ] Each account is an anchor that goes to that account page
  - [ ] Bank icons are not in-scope (just use a generic letter as shown in designs)
  - [ ] A "more" counter should show if there are more than 3 accounts
- [ ] Display a trendline of series.  No tooltips, no axes.
- [ ] These insights should be included in the dashboard - https://github.com/maybe-finance/maybe/blob/f5f624881f3b8900fa56d655ec040b5ee5d8a0af/app/views/pages/dashboard.html.erb#L35-L68

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- Be sure to read through [time series code](https://github.com/maybe-finance/maybe/tree/main/app/models/time_series) as it will help conceptualize things for this issue
- **Trailing 30 day calculation** - to further expand on this calculation, here are two examples of what this represents.  For these examples, assume the current date is `Apr 18 2024` and we are calculating the "Income" card:
  - Last value in graph (and "headline" number) represents the total income earned from `Mar 19 2024` to `Apr 19 2024` 
  - First value in graph (e.g. the "vs last month" trend comparison) represents total income earned from `Feb 18 2024` to `Mar 19 2024`

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $100 bounty on this. To participate in the bounty:

1. Comment `/attempt #645` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #645` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by webbdays** [comment]
@Samuelodan 
are you still on this?

**Comment by Samuelodan** [comment]
Hi @webbdays , apologies for the silence. I'm familiarizing myself with the codebase, preparing to draft my implementation plan. Do you plan to take up the issue as well?

**Comment by webbdays** [comment]
if you are on it carry on.
Thank you.

**Comment by Samuelodan** [comment]
Alright then. Thank you.

**Comment by adelinaenache** [comment]
Hey, I see that this issue is stalled. I'd like to work on it. 
/attempt #645

**Comment by adelinaenache** [comment]
@zachgoll Question: The period for the income/spending graph is always 30 days or is changeable (like in the net worth card)?

**Comment by zachgoll** [comment]
@adelinaenache for this issue you can assume that these cards will _always_ have a period of "last 30 days".

**Comment by zachgoll** [comment]
@JoshAntBrown would you mind commenting your attempt here just for visibility?

**Comment by JoshAntBrown** [comment]
Ah, of course, sorry! I started investigating it and ended up getting carried away with building it.

/attempt #645
