### ISSUE TITLE
Feature: Calculate "savings rate" insight for dashboard

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#646]
![CleanShot 2024-04-18 at 12 25 20](https://github.com/maybe-finance/maybe/assets/16676157/058edb25-b917-4e30-a6b2-56e2accf3f5d)

## Feature Overview

This issue is for calculating a "savings rate" over time to display as an insight on the dashboard.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] Should calculate a time series of "savings rate" calculations over the last 30 days (`Period.last_30_days`)
- [ ] For now, the calculation will be `(income - expense) / income` where `income` and `expense` are calculated on a "trailing 30 day basis".  The calculation for income/expense is implemented in #645, so that will either need to be completed or we can stub some placeholder values for them in this issue.
  - [ ] In the future, this calculation will likely incorporate other filters and parameters, so we'll need to make this easily extendable
  - [ ] Tests should be written for this calculation
- [ ] Should find the top 2 accounts with the highest savings rate within the last 30 days and display the rate 
  - [ ] Each account is an anchor that goes to that account page
  - [ ] Bank icons are not in-scope (just use a generic letter as shown in designs)
  - [ ] A "more" counter should show if there are more than 2 accounts
- [ ] Display a trendline of series. No tooltips, no axes.
- [ ] Should be incorporated into the dashboard: https://github.com/maybe-finance/maybe/blob/f5f624881f3b8900fa56d655ec040b5ee5d8a0af/app/views/pages/dashboard.html.erb#L69-L86

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- Be sure to read through [time series code](https://github.com/maybe-finance/maybe/tree/main/app/models/time_series) as it will help conceptualize things for this issue
- Trailing 30 day calculation - to further expand on this calculation, here are two examples of what this represents. For these examples, assume the current date is Apr 18 2024:
  - Last value in graph (and "headline" number) represents the savings rate from Mar 19 2024 to Apr 19 2024
  - First value in graph (e.g. the "vs last month" trend comparison) represents the savings rate from Feb 18 2024 to Mar 19 2024

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2779-1970&mode=design&t=Y0hF2UeUXaOhxGL4-0

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $150 bounty on this. To participate in the bounty:

1. Comment `/attempt #646` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #646` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

**Comment by Rutik7066** [comment]
@Shpigford Could you please assign this issue to me.

**Comment by Shpigford** [comment]
> @Shpigford Could you please assign this issue to me.

Hi @Rutik7066, thanks for your interest! Due to the speed that we're moving at, we don't currently assign issues. It's first-come, first-served on rewarding bounties.

**Comment by Rutik7066** [comment]
Ok then I will raise pr soon

**Comment by JoshAntBrown** [comment]
/attempt #646

I may pick this up as a follow up to #645, definitely a lot of cross over there
