### ISSUE TITLE
Improvement: review categories dropdown on transactions

### ISSUE THREAD

**Issue by mattia-malnis** [maybe-finance/maybe#659]
There are a few improvements and bugs that should be addressed in the categories dropdown:

- [ ] Bug: When a category is edited, an error occurs on save (see video below);
- [ ] Bug: If you try to create a category and leave the first color selected by default, nothing happens;
- [ ] Improvement: Every action inside the [controller](https://github.com/maybe-finance/maybe/blob/fe2a2ac3f9c2df8632dc90c6cf3ffc3a50d06013/app/controllers/transactions/categories_controller.rb#L4) that handles categories performs a redirect to `transactions_path`, which could be misleading for a user who is on the dashboard or the account details page.

https://github.com/maybe-finance/maybe/assets/15941778/ca08a18e-0bcb-4360-948c-ff10d675769a

A potential solution could be to remove the categories dropdown from every transaction line and load the categories asynchronously every time the dropdown is opened (this action should be infrequent as the category is assigned during transaction creation). By doing so, it should be easier to update the categories dropdown frame during the creation/edit process because there would be only one instance of it.

**Comment by zachgoll** [comment]
Should all be addressed by #679
