### ISSUE TITLE
History value unable to have cents

### ISSUE THREAD

**Issue by ahatzz11** [maybe-finance/maybe#669]
**Describe the bug**
This is a very similar issue to #613, but I found another place that is unable to have cents in the value, specifically a new entry in the history of an account.

**To Reproduce**
1. Go to an account
2. Click on "History"
3. Click on "New entry"
4. Attempt to put in cents in the "Value" field

**Expected behavior**
I should be able to record cents.

**Screenshots / Recordings**
<img width="1309" alt="image" src="https://github.com/maybe-finance/maybe/assets/6256032/7169dff3-f8a7-4af6-817b-5c60490c02b4">

**Comment by zachgoll** [comment]
@ahatzz11 thanks for the report, will scan through the codebase and get this and any others remaining fixed :+1:
