### ISSUE TITLE
Can you get a tag for the pre open source version of the repository?

### ISSUE THREAD

**Issue by alex-ald** [maybe-finance/maybe#67]
I'd like to see a tag added to the `b500040` commit to represent the repository before any open source changes were added.

It's nice to come visit the repository at this point in the history to view the code as it was in production and to learn from what a SAAS codebase can look like. 

Thanks!

**Comment by Shpigford** [comment]
Love that idea! I haven't personally done that before...any guidance on how I'd set that up?

**Comment by alex-ald** [comment]
Yep! So you should basically just have to do:
`git tag pre-open-source b500040` (pre-open-source is the name of the tag, feel free to name it something else)
then `git push --tags`.

That should be All! This also assumes you have write access to main.

**Comment by Shpigford** [comment]
Done! https://github.com/maybe-finance/maybe/releases/tag/original
