### ISSUE TITLE
Feature: Configure ActiveStorage and implement profile picture uploads

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#674]
![CleanShot 2024-04-25 at 10 55 04](https://github.com/maybe-finance/maybe/assets/16676157/332cb5c7-0ef3-4cfa-823f-3223fb588341)

## Feature Overview

We currently have a _placeholder_ in the profile settings for profile picture uploads.  This issue will enable a user to upload their own profile picture to Maybe and will enable ActiveStorage.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

### ActiveStorage Setup

Since the Maybe app will be self-hosted, we should allow a user to choose their preferred object storage and configure it 100% with environment variables (credentials helper may still be used, but we cannot _rely_ on it as some self-hosted setups like Render need to be configured 100% by environment variables).

- [ ] Default storage will be Disk storage (to allow self-hosters to remain "zero config")
- [ ] Other storage options will be AWS, GCP, and Azure and can be specified via `ACTIVE_STORAGE_SERVICE=`
- [ ] Platform specific storage should have a prefix `SERVICE_` for each required config.  For example, `S3_ACCESS_KEY_ID` for AWS S3 or `GCP_ACCESS_KEY_ID` for Google Cloud
- [ ] Can be configured 100% through environment variables

### Profile picture uploads

- [ ] User can upload a new profile picture
  - Suggested constraints (use your best judgment): 5MB max, JPG/PNG/GIF format?
- [ ] User can remove an existing profile picture
- [ ] Tests where appropriate

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=3176-87&mode=design&t=4eaJRTzT6AYU5CNv-0

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $200 bounty on this. To participate in the bounty:

1. Comment `/attempt #674` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #674` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by crobbo** [comment]
/attempt #674

* Introduce active storage
* Include required active storage gems (S3, Azure, GCP)
* Create active storage config file
* Amend user model to store profile image
* Create stimulus controller for profile image previewing / removal
* Front-end amendments as per designs

Things to note:
* The recommended gem for using Azure will be [deprecated](https://github.com/Azure/azure-storage-ruby) in September 2024
* GCP uses a keyfile for auth rather than an access key and secret
