### ISSUE TITLE
Feature: Allow user to delete their Maybe account and all data

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#675]
![CleanShot 2024-04-25 at 11 20 40](https://github.com/maybe-finance/maybe/assets/16676157/c7062136-f90d-4276-bea2-07ac4a3b2ff2)

## Feature Overview

In an effort to give users full control over their data, this issue allows them to delete their entire Maybe account and associated data.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] User can delete their user account
  - [ ] If user is `admin` and there are no other users in the family, delete the user, family, and all associated data
  - [ ] If user is `member`, only delete the user and the associated _user_ data 
  - [ ] In all other scenarios, trigger a failure
    - For example: An `admin` tries to delete their account while the family has other members.  In a scenario like this, we should error and say something like, "Admin cannot delete account while other users are present.  Please delete all members first."
- [ ] User must confirm deletion via a dialog
- [ ] After deletion, user is redirected to the sign up page with success notification
- [ ] Deletions should be atomic.  A delete action should _never_ result in invalid states or partially deleted data.
- [ ] Appropriate tests written
- [ ] i18n translations provided for `en.yml`

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- Be sure to familiarize yourself with the `Family` and `User` models.  Currently, the app stores quite a bit of data on `Family`, hence some of the conditional deletion requirements listed above.
- Use your best judgment on this issue.  There are likely edge cases not covered here.  The overall goal at this stage is to get a _basic_ and _simple_ version of this working that can be improved upon in the future
- We _may_ want to put the deletion process in a background job, but only if it has a clear benefit

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=3176-910&mode=design&t=4eaJRTzT6AYU5CNv-0

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $150 bounty on this. To participate in the bounty:

1. Comment `/attempt #675` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #675` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by sirkyven** [comment]
I wanna work on it.

**Comment by zachgoll** [comment]
FYI for anyone working on this right now:

Please re-review the requirements around deletion logic.  After reviewing them, I realized they may have been more complex than needed.
