### ISSUE TITLE
Feature: Add Transaction Merchant management

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#681]
![CleanShot 2024-04-25 at 16 42 27](https://github.com/maybe-finance/maybe/assets/16676157/8b2602fe-ed81-44d9-96b1-2acb52f92918)

## Feature Overview

The goal of this feature is to introduce a "Merchant" model that a user can manage.  A user will be able to set a merchant for a transaction and will be able to manage all of their family-owned merchants in settings.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] Should be implemented at the route `/transactions/merchants` (in settings)
- [ ] User can create a new merchant (choose a color and name)
- [ ] User can edit existing merchant
- [ ] User can delete merchant
- [ ] When user deletes merchant, app asks them to confirm before deleting
- [ ] i18n translations provided
- [ ] Tests written where appropriate

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=3194-441&mode=design&t=gI2CS4JU0eghOMVN-0

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $100 bounty on this. To participate in the bounty:

1. Comment `/attempt #681` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #681` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

NOTE: Given the speed at which we're moving on the codebase, we don't assign issues or "give" issues to anyone.

**Comment by jakubkottnauer** [comment]
@zachgoll ready for review 😄
