### ISSUE TITLE
Bug:  System setting tests fail randomly

### ISSUE THREAD

**Issue by ThibautGrx** [maybe-finance/maybe#696]
**Describe the bug**
In the test action of the CI , system setting tests fail randomly. 

**Screenshots / Recordings**

![image](https://github.com/maybe-finance/maybe/assets/35230028/999caccc-c260-4517-8df7-4672921c948e)

**Comment by zachgoll** [comment]
Can confirm, this test is flaky.  I'll take a look shortly.

**Comment by zachgoll** [comment]
I'm going to close this as I've removed system tests from CI for the time being.

These will be re-introduced (and prioritized) before any go-live, but right now, they're simply causing headaches in CI.  So I think we can continue to develop and run system tests locally to check work, but not enforce them _yet_.
