### ISSUE TITLE
Feature: Add Test Coverage Generation

### ISSUE THREAD

**Issue by jemiluv8** [maybe-finance/maybe#699]
## Feature Overview
The current `rake test` command doesn't generate test coverage report.
This can be useful especially for new features that require testing.

## Requirements
- [ ] Support generation of test coverage report when running tests

## Implementation Suggestions
Probably integrate simplecov-ruby or similar compatible library for test coverage report generation

## Designs
Not Applicable

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

**Comment by jemiluv8** [comment]
@garhuku, FYI, I'm not a maintainer on this project and this issue doesn't have a bounty on it at the moment.
Also, you might want to ping the maintainers just in case they have something to add or even if they truly want test coverage on their project.

**Comment by zachgoll** [comment]
@jemiluv8 @gathuku I think we could add the `simplecov` gem to generate a coverage report, but given how early we are with this project, this should be for _convenience only_ at the moment (i.e. a dev writing tests locally can easily see coverage to help them identify important areas that they missed)

In other words, we can set this up, but let's not enforce anything in CI for now.

**Comment by gathuku** [comment]
Nice! @jemiluv8 can I help you with this?
