### ISSUE TITLE
Will exe can be release?

### ISSUE THREAD

**Issue by Nikeguo** [maybe-finance/maybe#72]
I am not familiar with docker, will exe be released in the future?

**Comment by Jesse0502** [comment]
I'm not a contributor for the project but it is currently designed for web only, you can run it locally by cloning it on your pc.

**Comment by Shpigford** [comment]
@Nikeguo No .exe plans in the near future. At the moment, web/internet access is required to run the product so no real benefit to releasing a packaged Windows download.
