### ISSUE TITLE
Bug: Creating new account doesn't default currency to selected currency in preferences

### ISSUE THREAD

**Issue by sumnerboy12** [maybe-finance/maybe#723]
**Describe the bug**
I have set the base currency to NZD in preferences. When I create a new account I would expect the currency to be set to NZD by default.

**To Reproduce**
1. Set a currency in preferences, other than USD
2. Create a new "Bank Account"
3. Click "Enter account balance manually..."
4. Balance currency selector is USD

**Expected behavior**
I would expect the balance currency selector to default to my chosen base currency, in this case NZD

**Comment by zachgoll** [comment]
Fixed by #722
