### ISSUE TITLE
New bank accounts should use the default currency

### ISSUE THREAD

**Issue by RJMurg** [maybe-finance/maybe#733]
**Is your feature request related to a problem? Please describe.**
New user to Maybe, and really enjoying transitioning over to it, but I've got a small issue bugging me.

When I add a new item to my portfolio, the default selected currency is USD, though I have my currency set to EUR in my preferences. 

This has caused some cases where I add an item and set the value, but forget to change the currency, and have to delete the entire item to recreate it with the correct currency.,

**Describe the solution you'd like**
- Have all new items being added in portfolio to default to the currency that has been selected in the users' preferences
- Possibly allow currency conversion after creating a portfolio item, maybe asking if the user wishes to change the amount as well as the currency, or just the currency.

**Additional context**
![image](https://github.com/maybe-finance/maybe/assets/115182656/5d616e8e-f578-453b-bcdd-c5aab194b7e8)
![image](https://github.com/maybe-finance/maybe/assets/115182656/2a8b2106-5ac4-4ac2-9c77-f25ee5e62130)

**Comment by zachgoll** [comment]
@RJMurg thanks for the description here, I think this is definitely worth adding.
