### ISSUE TITLE
Add pagination for account history + transactions to improve performance

### ISSUE THREAD

**Issue by jakobskrym** [maybe-finance/maybe#739]
**Where did this bug occur?**

- [x] Local development
- [ ] Self hosted app (i.e. Docker)

**Describe the bug**

There is currently no pagination on the account page which means that it becomes very slow to load when you have a higher number of transactions. Wrote a script to import some transactions from my bank (~1.4k) and it made it so slow that I had to restart the app to get to another page.

**To Reproduce**
1. Ensure >1k transactions or history for given account
2. Go to account page
3. Wait

**Expected behavior**
Use pagination to prevent long loading times.

**Screenshots / Recordings**
If applicable, add screenshots or short video recordings to help show the bug in more detail.

**Additional context**
Realize this is in between a bug and a feature request.

**Comment by jakubkottnauer** [comment]
@zachgoll I've tracked down the performance problems to the category dropdown (more specifically the `transactions/categories/dropdown/row` partial). If I comment out the partial [here](https://github.com/maybe-finance/maybe/blob/5fa34b4111a24a0df939bbdca9e73638c5bcd9fb/app/views/transactions/categories/_menu.html.erb#L21), account with 1k transactions loads without any problems.

**Comment by zachgoll** [comment]
@jakubkottnauer got it, thanks for looking into this.  I'm thinking we'll eventually need some pagination since many credit card accounts will have thousands of transactions in a short time-span, but this could be a good temporary fix if we want to make these rows more of a "read only" row for now.

**Comment by zachgoll** [comment]
I think we can close this since #782 drastically improves the performance of large transaction lists.

We can re-introduce pagination as a dedicated feature once we have some designs for it.

**Comment by jakobskrym** [comment]
Can confirm it's now much better 👍 Nice work @jakubkottnauer
