### ISSUE TITLE
Maybe Card download returns an empty file

### ISSUE THREAD

**Issue by lorenzopalaia** [maybe-finance/maybe#74]
When you try to download the Maybe Card for your profile, an empty .png with size 0 kb file is downloaded. This happens both when it is shown for the first time after creating the profile and when you try to download it from the settings page.

**Comment by Shpigford** [comment]
@lorenzopalaia What browser/OS are you using and any browser console errors?

**Comment by lorenzopalaia** [comment]
Sidekick, a Chrome-based browser, on Mac OS Ventura 13.6.3. Still not working on Firefox and Safari too.

**Comment by lorenzopalaia** [comment]
Hey, I've just found the issue!

Basically in line 52 of /apps/client/pages/api/card.tsx you reference `src="https://assets.maybe.co/images/maybe-card.png"` which is no longer available, that's why downloaded image is empty. Just tried with a placeholder image and works fine.

Can't provide you a pull request with a fix as I wasn't able to find the card background image locally but I think it should be an easy one.

**Comment by Shpigford** [comment]
Doh! Good catch. I'll get this fixed today as I've got the files. 😬
