### ISSUE TITLE
Bug: Reset Password

### ISSUE THREAD

**Issue by Marco77577** [maybe-finance/maybe#747]
**Where did this bug occur?**

- [ ] Local development
- [x] Self hosted app (i.e. Docker)

**Describe the bug**
When resetting a password, the link is sent via email. When opening the link and entering a new password, the user is forwarded to the same screen as when entering the email address to reset the password, i.e., the login page with a message that says "If an account with that email exists, we have sent a link to reset your password."

**To Reproduce**
1. Create an account and log out.
2. On the login page, click on 'Reset it [password]'.
3. Enter your email address, receive the email, and click the link.
4. Enter new password, confirm it, hit "Update Password".
5. Try to log in with new password, resulting in "Invalid email or password.".

**Expected behavior**
The password should have been reset.

**Screenshots / Recordings**
If applicable, add screenshots or short video recordings to help show the bug in more detail.

**Additional context**

**Comment by zachgoll** [comment]
This should be fixed via #741
