### ISSUE TITLE
Incongruent Server Responses: 204 on Client vs. 500 on Direct Access (Possible Axios Issue)

### ISSUE THREAD

**Issue by Jesse0502** [maybe-finance/maybe#79]
## **Issue Summary**

API request from client returns 204 (No Content) status with undefined data, but the same request directly to the server URL results in a 500 status and an error message.

## **Environment**

Operating System: Windows 10
Node.js Version: v20.9.0

## **Steps to Reproduce**

1. Start Development Server:

Execute yarn run dev to initiate the project's development server.

2. Log in to the Application:

Successfully log in to the application using the provided credentials.

3. Observe Error Message:

Upon entering the app after login, note the error message "Unable to load onboarding."

![response](https://github.com/maybe-finance/maybe/assets/85474982/9f4fc61d-51bd-4b02-912d-68d9886fd707)

4. Inspect Network Response:

Utilize browser developer tools to examine the network tab.
Locate the API request associated with the onboarding data.
Verify that the response status is 204 (No Content) and the data is undefined.

## **Client-side request:**
Status: 204 No Content
Data: Undefined
![client](https://github.com/maybe-finance/maybe/assets/85474982/59b44f83-e68c-44a7-9767-81c31b329709)

## **Server-side request (direct):**
Status: 500 Internal Server Error
![server](https://github.com/maybe-finance/maybe/assets/85474982/b82c88ec-7e9b-4f3b-a927-7a413e15c0af)

## **Potential Causes**

Axios configuration: Suspecting potential issue with Axios instance configuration.

**Comment by Jesse0502** [comment]
Update: I was able to get rid of this issue by pulling the latest commit from the branch

**Comment by tmyracle** [comment]
Glad you were able to get this resolved @Jesse0502 
The difference in direct server response vs client is expected since the server authenticates the request via HTTPOnly cookie which is automatically sent with browser requests via withCredentials: true in the axios config.

**Comment by cmosguy** [comment]
I just got the same message when I tried to create an account.  It created a user in the database and then routed me to login screen and I still cannot login.

**Comment by Jesse0502** [comment]
yes also make sure docker is running
