### ISSUE TITLE
Bug:  Unable to upload png file to profile image

### ISSUE THREAD

**Issue by pea-sys** [maybe-finance/maybe#808]
**Where did this bug occur?**

- [ ] Local development
- [x] Self hosted app (i.e. Docker)

**Describe the bug**

Unable to upload png file to profile image

**To Reproduce**
1. Select Account in the sidebar
2. Press the Choose button on the profile panel

**Expected behavior**
PNG files can be uploaded as explained

**Screenshots / Recordings**
![1](https://github.com/maybe-finance/maybe/assets/49807271/a2b0fa7e-9bc4-40c9-ac28-45643e4ab94c)

**Additional context**

**Comment by Shpigford** [comment]
Fixed with #809

**Comment by thelooter** [comment]
I still experience this issue as of alpha.7

**Comment by zachgoll** [comment]
@thelooter can you provide some details about the image you're trying to upload?

PNGs are working fine for me—is the image you're uploading >5MB by chance?

**Comment by pea-sys** [comment]
@thelooter 
Additional modules were required when running on localhost
#818

**Comment by thelooter** [comment]
> @thelooter can you provide some details about the image you're trying to upload?
> 
> PNGs are working fine for me—is the image you're uploading >5MB by chance?

I wanted to upload my Avatar
https://avatars.githubusercontent.com/u/24987877?v=4
Its around 150kB big

It fails with a POST to http://192.168.178.193:3000/settings/profile

Its a 500 Error Code

**Comment by thelooter** [comment]
Environment is docker compose with the suggested docker compose

**Comment by ntlv1** [comment]
It may be a permissions issue?
I don't use docker volume like example compose file. I mount local dir.
I run the container as `root`, and the owner of directory `/rails/storage` is `root`.
`uid` of the app is 1000. After `chown`, I can upload image.
