### ISSUE TITLE
Bug: Raspberrypi support on Docker

### ISSUE THREAD

**Issue by DavidMarinCalleja** [maybe-finance/maybe#816]
**Where did this bug occur?**

- [ ] Local development
- [X] Self hosted app (i.e. Docker)

**Describe the bug**
When trying to install it on a raspberrypi docker does not find a version for the correct architecture. The error is this:

```
sudo docker-compose up -d
Creating network "maybe-finance_default" with the default driver
Creating volume "maybe-finance_postgres-data" with default driver
Pulling postgres (postgres:16)...
16: Pulling from library/postgres
3b9aff019fd4: Pull complete
e82f99b716fc: Pull complete
9591a3170f7b: Pull complete
b87817ead93f: Pull complete
c27645fe8f04: Pull complete
5a5a1c3ebdf0: Pull complete
ab3d498843c8: Pull complete
22f366fb3f74: Pull complete
159c0adbe623: Pull complete
50004be56e7a: Pull complete
fc1e7ddea7f5: Pull complete
5b2022547691: Pull complete
5645a1ebb391: Pull complete
300b98b9b61a: Pull complete
Digest: sha256:1bf73ccae25238fa555100080042f0b2f9be08eb757e200fe6afc1fc413a1b3c
Status: Downloaded newer image for postgres:16
Pulling app (ghcr.io/maybe-finance/maybe:latest)...
latest: Pulling from maybe-finance/maybe
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

**To Reproduce**
1. create the docker-compose.yml file
2. run `docker-compose up -d`
3. See error

**Expected behavior**
Since the project is Ruby I was hoping it could be installed on this architecture. 

**Screenshots / Recordings**
NA

**Additional context**
```
sudo docker version
Client:
 Version:           20.10.24+dfsg1
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        297e128
 Built:             Wed Apr  5 15:19:59 2023
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.24+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       5d6db84
  Built:            Wed Apr  5 15:19:59 2023
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.20~ds1
  GitCommit:        1.6.20~ds1-1
 runc:
  Version:          1.1.5+ds1
  GitCommit:        1.1.5+ds1-1
 docker-init:
  Version:          0.19.0
  GitCommit:
```

**Comment by zachgoll** [comment]
Unless I'm mistaken here, looks like we'll need to add `linux/arm/v7` on the line below to target both old and new Raspberry Pi devices:

https://github.com/maybe-finance/maybe/blob/df391e0a145af07c5ef989275d138231f7b8c317/.github/workflows/publish.yml#L112

**Comment by MrTob** [comment]
having a Raspberry Pi 5 - when im running `docker compose up` it fails with `no matching manifest for linux/arm/v8 in the manifest list entries`

**Comment by zachgoll** [comment]
We've removed 32 bit Raspberry pi support from our "official" list of platforms, but 64bit pi instances (i.e. all "modern" Pi's) will work.

Detail outlined here:

https://github.com/maybe-finance/maybe/commit/fd95f8d2bd46505f77e6ef34b73d3fd3b4191655
