### ISSUE TITLE
Bug: Profile picture not showing

### ISSUE THREAD

**Issue by pea-sys** [maybe-finance/maybe#818]
**Where did this bug occur?**

- [ ] Local development
- [x] Self hosted app (i.e. Docker)

**Describe the bug**
Profile picture not showing

**To Reproduce**
1. Upload a profile picture
2. Click the Save button

**Expected behavior**
Profile picture  showing

**Screenshots / Recordings**
![1](https://github.com/maybe-finance/maybe/assets/49807271/435f64fb-cec7-45be-9fc8-9b31ff1ed26f)

**Comment by pea-sys** [comment]
I solved it with the following command
```
apt-get update -qq && apt-get install -y --no-install-recommends libvips42
```

**Comment by zachgoll** [comment]
@pea-sys you are running this with Docker correct?  Our Dockerfile has `libvips` already so I'm wondering why this was not working correctly.
