### ISSUE TITLE
Add the ability for a user to skip certain columns in a CSV import

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#829]
Currently we allow the following fields for a CSV import:

- date (required)
- name (optional)
- category (optional)
- tags (optional)
- amount (required)

When setting up column mappings, a user should be required to provide a mapping for required fields, but should be able to "remove" / "disable" other fields that they don't care about.

For example, a user may not want to deal with tags at all, which in that case, they shouldn't need to provide any mapping for tags.

**Comment by flacnut** [comment]
Maybe a separate issue/request, but the ability to add default category and tags to all transactions would be great.

Default category would substitute category column. Default tags would be additive to any provided tags.
