### ISSUE TITLE
Bug: docker-compose up -d fails during first install

### ISSUE THREAD

**Issue by naz** [maybe-finance/maybe#841]
**Where did this bug occur?**

- [ ] Local development
- [x] Self hosted app (i.e. Docker)

**Describe the bug**
When setting up Maybe on a self-hosted machine following [setup instructions](https://github.com/maybe-finance/maybe/blob/e4ac5c87e40c9383824717a337abc6339b5c113d/docs/hosting/docker.md), the [Run app with Docker Compose](https://github.com/maybe-finance/maybe/blob/e4ac5c87e40c9383824717a337abc6339b5c113d/docs/hosting/docker.md#run-app-with-docker-compose) step fails with following error:

```
:~/docker/maybe$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.app.environment.SELF_HOSTING_ENABLED contains true, which is an invalid type, it should be a string, number, or a null
```

**To Reproduce**
1. ssh into the server
2. follow the steps from [self-hosting guide](https://github.com/maybe-finance/maybe/blob/e4ac5c87e40c9383824717a337abc6339b5c113d/docs/hosting/docker.md#run-app-with-docker-compose)
3. see the failure on the `Run app with Docker Compose` step

**Expected behavior**
The `docker-compose up -d` should create and run a fresh Maybe instance

**Additional context**
Might be an issue with the docker environment? My server is running on `Docker version 20.10.12, build e91ed57`

**Comment by MohamedEHJ** [comment]
I have the same problem
docker-compose version 1.29.2, build unknown
Docker version 26.0.2, build 3c863ff

**Comment by zachgoll** [comment]
@naz can you try modifying your docker compose file like this and let me know if it fixes the problem?

```
environment:
  SELF_HOSTING_ENABLED: "true"
```

**Comment by zachgoll** [comment]
I believe the solution I've outline above should work for everyone.  Closing this out for now and can re-open if needed.
