### ISSUE TITLE
Bug: pie chart on dashboard does not support multi-currency formatting 

### ISSUE THREAD

**Issue by AurelienConte** [maybe-finance/maybe#842]
**Where did this bug occur?**

- [x] Local development
- [x] Self hosted app (i.e. Docker)

**Describe the bug**

On the dashboard after adding my first checking account the assets graph is showing my checking account value with an "undefined" value.

**To Reproduce**

- Follow the self hosted docker installation and open the dashboard.
- Create your first account
- Add a bank account with a positive amount
- Refresh the dashboard
- You should see undefined in the upper right part of the dashboard ( Above total assets )

**Expected behavior**

I expect to show my account value but without the undefined keyword

**Screenshots / Recordings**

![image](https://github.com/maybe-finance/maybe/assets/39769262/840467d7-383f-4579-8aeb-aad680f40dec)

**Comment by AurelienConte** [comment]
By the way i'm looking for some "Good first issue" to start working on the project and i think this can be a good one !

**Comment by zachgoll** [comment]
@AurelienConte yeah this would be a great first issue, you're welcome to take it!

**Comment by AurelienConte** [comment]
Okay ! 
Thanks i take it !

**Comment by AurelienConte** [comment]
I created a PR about this #844
