### ISSUE TITLE
Bug: after editing an account history value, it requires 2 clicks to close the menu

### ISSUE THREAD

**Issue by pea-sys** [maybe-finance/maybe#843]
**Where did this bug occur?**

- [x] Local development
- [ ] Self hosted app (i.e. Docker)

**Describe the bug**
Bug: When multiple data are in edit mode, data editing cannot be canceled.

**To Reproduce**

1. Click ①

![1](https://github.com/maybe-finance/maybe/assets/49807271/73f2d456-f18d-4edd-bc5c-3a0704e2d303)

2.Start editing the first row of data 
3.Start editing the second row of data
![2](https://github.com/maybe-finance/maybe/assets/49807271/f788a837-fcb9-4104-8a04-f82c7a9703da)

**Expected behavior**
Edit mode can be cancelled

**Comment by zachgoll** [comment]
@pea-sys I'm not able to reproduce this on `main`.  Any chance your `main` branch was not updated when testing this?


https://github.com/maybe-finance/maybe/assets/16676157/3feed0a0-6222-4610-bbff-3327dbf17df7

**Comment by pea-sys** [comment]
It has been confirmed that my report was incorrect and that you can exit edit mode.
The confusion is that the "Edit Entry/Delete Entry" label remains visible even after you exit edit mode.
Before entering edit mode, you could delete it by clicking "・・・" once, but after exiting edit mode it takes two clicks.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by zachgoll** [comment]
@pea-sys got it.  That makes sense, will fix.
