### ISSUE TITLE
Bug: Invalid email or password.

### ISSUE THREAD

**Issue by Joly0** [maybe-finance/maybe#847]
**Where did this bug occur?**

- [ ] Local development
- [X] Self hosted app (i.e. Docker)

**Describe the bug**
Created the docker-compose file aswell as the env file, started the containers, tried to login from local network, no proxy or anything yet.
Tried to login and see this:
![grafik](https://github.com/maybe-finance/maybe/assets/13993216/fcdfd723-2592-42f1-8f9b-de203786b229)

**To Reproduce**
1. Setup docker-compose and env file
2. Startup docker-compose
3. Try to login

**Expected behavior**
Lets me login

**Screenshots / Recordings**
See above for screenshots

**Additional context**

**Comment by zachgoll** [comment]
@Joly0 did you create an account prior to logging in?  For a self hosted instance, you will need to do this.

The "sample" credentials are for _development only_ and should not be used for self hosting.  We've got a project item in place to make this more clear here:

https://github.com/orgs/maybe-finance/projects/15?pane=issue&itemId=63765523

**Comment by zachgoll** [comment]
@Joly0 as of right now, all you'll need to do is hit the "create an account" button on the login screen.  This will become clearer in the future as we add more fine-grained controls around managing access to your self hosted instance.
