### ISSUE TITLE
Add instructions for Ngrok usage

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#85]
For development and for local self-hosting, we're defaulting to using Ngrok for HTTPS URLs (needed for basically any external data source).

We need to add instructions on how to set up an Ngrok account with a static domain and how to set the key + domain in .env.

Relevant discussion: #66

**Comment by Neumand** [comment]
@Shpigford PR is up.

Let me know if I missed anything.

**Comment by Shpigford** [comment]
@Neumand Something ngrok now offers is static domains for free accounts: https://ngrok.com/blog-post/free-static-domains-ngrok-users

That'll be necessary for users when it comes to setting webhooks at the various data sources.

We should include that in the instructions.

**Comment by jaitjacob** [comment]
@Shpigford there is an Ngrok npm package we could use to open a connection and grab URL programmatically. This can avoid the copy pasting into .env step completely. Would you like to consider it?

**Comment by Shpigford** [comment]
@jaitjacob Not opposed to it, though probably outside the scope of this and instead would go in to a future "Improve Setup Process" PR.

**Comment by Neumand** [comment]
I assume so. PR updated!
