### ISSUE TITLE
Migrate from Webpack to Vite

### ISSUE THREAD

**Issue by Neumand** [maybe-finance/maybe#86]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Update NX to use `vite` instead of `webpack`

**Describe alternatives you've considered**
I guess an alternative would be `esbuild`? I have less direct experience with other bundlers. Open to suggestions.

**Additional context**
Migrating here should improve the build time considerably. We made the shift at work and it saved us tons of time. This could be a good early improvement.

**Comment by Shpigford** [comment]
Can you provide a high-level overview of what may be required here? Basically trying to gauge effort + impact.

**Comment by Neumand** [comment]
Sure.

I _think_ this is the extent of the changes. If someone else has experience with this, I would love their opinion.

- Update `workspace.json` to use `@nx/vite` as the executor instead of `@nrwl/webpack:webpack`
- Upgrade Storybook to use `vite`
- Remove packages that leverage `webpack` (i.e. `@svgr/webpack`). It looks like most of them are not used.

I'd be happy to experiment with this myself to dig deeper into the complexity.

**Comment by Shpigford** [comment]
Yeah, I'd suggest doing some work locally on it to quantify any potential improvements, then you can open a PR with that and have other folks try out the solution as well.
