### ISSUE TITLE
Improvement: Allow user to configure date and amount format during transaction imports

### ISSUE THREAD

**Issue by zachgoll** [maybe-finance/maybe#863]
**Is this issue related to a problem?  Please describe.**

Currently, the transaction imports feature _requires_ users to input their data with the following convention: 

- **Dates**: must be in ISO8601 format (i.e. `YYYY-MM-DD`)
- **Amounts**: incomes must be _positive_ values, expenses must be _negative_ values

Many users will be using the following flow to import data:

1. Go to bank login 
2. Export transactions from bank
3. Import file to Maybe

_Most_ bank exports will include a "date" and "amount" field, but they will all be in different formats.

The user should be able to tell Maybe what those formats are **to prevent an extra step of cleaning their exported bank data prior to importing it to Maybe**

**Describe the work that needs to be done to address this issue**

- Add fields next to "date" and "amount" fields on the "Configure" step that allow a user to select from a list of predefined formats and signage conventions

## Designs for this issue

https://www.figma.com/design/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?node-id=4199-214&t=dtAjwPnms0o6BmNx-0

**Comment by MagnusHJensen** [comment]
Is this relevant if the user can set their date preference in the config issue: #909 , or should it still be provided here, but just set to the default of the user selected value, in case the format is different from the user's preferred option?

Could you also elaborate a bit on the amount field?

_Note: Just stumbled upon this app and repo, and it looks cool. Hoping to engage with it over the coming weeks, cheers_

**Comment by zachgoll** [comment]
@MagnusHJensen yep, I think defaulting this select option to the user's preferred date format as specified in #909 is a good approach.

In regards to the amount field, in _most_ cases, a CSV will display "incomes" as a positive value and "expenses" as a negative value, but we cannot guarantee that.  Since this app relies on the signage of the `amount` to calculate various metrics, we need to ensure that we know exactly what convention the user is using while importing.

**Comment by MagnusHJensen** [comment]
@zachgoll Alright, that makes sense. So amount would technically be only two options.
One for (-) = positive amounts and (+) = negative amounts.
And One for (+) = positive amounts and (-) = negative amounts?

**Comment by mamarguerat** [comment]
@MagnusHJensen I would add an option. I had once a csv table with all amounts in negative (don't ask why not positive) and another column with the label "income" and "expense".
I don't know if any bank does the same, this csv export was from Firefly-III.

**Comment by MagnusHJensen** [comment]
> @MagnusHJensen I would add an option. I had once a csv table with all amounts in negative (don't ask why not positive) and another column with the label "income" and "expense". I don't know if any bank does the same, this csv export was from Firefly-III.

Interesting setup haha.

Then it comes down to how many _custom/third-party_ solutions should be supported, and I can't advocate for anything there, since it's out of my scope/knowledge.

**Comment by zachgoll** [comment]
@mamarguerat that's a great point, I've seen this format for a couple of my FIs too.

To support that, I'm guessing we'd need an _additional_ select where we ask the user the _name_ of the column that designates the signage the transaction.  For example, Mint data exports are in the following format:

<img width="356" alt="image" src="https://github.com/maybe-finance/maybe/assets/16676157/eef18cd3-ce3b-45bc-8629-7884ec1754a8">

So in this case, we'd need the user to select "Transaction Type" from the column list.

@justinfar this might affect the existing designs a little bit, but probably would be worth throwing in?

**Comment by mamarguerat** [comment]
Thinking of UX, if there is a transaction type column, it would be great to have some other selects, which are populated with uniques values of the column, to choose what is an income or an outcome.
The transaction type column could be "debit/credit", "income/outcome", "deposit/withdrawal", (maybe some other, I don't have enough English vocabulary for that) and in multiple languages. So letting the user choose the value is, by my point of view, a must-have.

Thinking of something like that (done in html with dev tools), where the two last select are only shown when something is selected in "Transaction type"
![image](https://github.com/maybe-finance/maybe/assets/49449909/7184a03c-8c4f-4210-a048-56b57fcf9652)

**Comment by zachgoll** [comment]
@mamarguerat here are some updated designs from @justinfar that I think will work for this issue!

![CleanShot 2024-07-08 at 09 30 45@2x](https://github.com/maybe-finance/maybe/assets/16676157/44df05c8-73f5-460a-b9fa-78d45e4b16e6)

https://www.figma.com/design/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?node-id=4199-214&t=dtAjwPnms0o6BmNx-0

**Comment by jestinjoshi** [comment]
My bank gives me a CSV in the following format

![Image](https://github.com/user-attachments/assets/cdff23e5-b3e6-43fb-a5b4-aca1f5e0f18f)

If you could take this into consideration then that would be great

**Comment by janKaje** [comment]
Another option that I don't think was discussed earlier is having smart recognition of date formats. I have accounts under two banks and they use different formats, one following the ISO8601 format and the other `mm/dd/yyyy`. Having a default date format that automatically applies to all imported transactions wouldn't be very helpful if I have to change it often.

However, all countries either use YMD, DMY, or MDY order for numerical dates. Banks always seem to use four-digit years, allowing easy automatic distinction between YMD and the other two. A simple consistency test could then almost always tell if a list of ordered dates is DMY or MDY, and any ambiguous entries could induce a user prompt. Does this seem like it would be straightforward to integrate?

**Comment by vanhalt** [comment]
> Another option that I don't think was discussed earlier is having smart recognition of date formats. I have accounts under two banks and they use different formats...

In this case would it be useful to configure an import rule set per institution?

**Comment by zachgoll** [comment]
This has been completed via #1209
