### ISSUE TITLE
Migrate from Yarn 1.x to pnpm

### ISSUE THREAD

**Issue by Greek** [maybe-finance/maybe#87]
**Is your feature request related to a problem? Please describe.**
Yes. This repo is currently using an outdated package manager.

**Describe the solution you'd like**
Yarn Classic (1.x) is ~4ish years old and needs an upgrade. The purpose of this issue is to upgrade the workspace to explore using the pnpm package manager rather than Yarn 1.x

**Describe alternatives you've considered**
As of now, it's best to use Yarn 1.x. We can configure `package.json` to explicitly use the classic version of Yarn and add some documentation as to how developers can configure Yarn to use 1.x.

**Additional context**
[pnpm home page](https://pnpm.io/)

**Comment by douglasg14b** [comment]
Or switch to `pnpm` and not fight with yarn v(insert here) issues!

We switched to yarn v3 on many projects and it was an absolute headache for contributers due to yarn idiosyncrasies with global installs. We've since dropped it in favor of `pnpm` with much happier devs.

**Comment by Greek** [comment]
> Or switch to `pnpm` and not fight with yarn v(insert here) issues!
> 
> We switched to yarn v3 on many projects and it was an absolute headache for contributers due to yarn idiosyncrasies with global installs. We've since dropped it in favor of `pnpm` with much happier devs.

I agree, I've changed the issue to reflect that

**Comment by Shpigford** [comment]
Can you write up an overview of...

1. What would be required to migrate
2. What the problems are with the current solution
3. What the tangible benefits would be to migrating (i.e. what's the upside here)

**Comment by Greek** [comment]
1. Migrate Yarn lockfile to pnpm (`pnpm import`) and [remove any yarn-related files/scripts](https://dev.to/andreychernykh/yarn-npm-to-pnpm-migration-guide-2n04), and create any additional workspace files if needed.
2. Yarn 1.x is old and slower than the alternatives and users are more likely to be using PNPM or Yarn Berry than Yarn 1.x
3. [Faster download speeds (+ even faster w/ past cached installs)](https://pnpm.io/benchmarks), and hopefully a much better experience using pnpm

I've used pnpm for a bit and speed is a big thing, at least for me. The speed up on pnpm compared to Yarn 1.x is amazing especially with pnpm's caching functionality.

**Comment by BoscoDomingo** [comment]
I can vouch for pnpm's awesomeness. The main painpoint with monorepos is getting Dockerfiles working in a decent state as pulling in all the dependencies _should_ be a simple thing with `pnpm deploy` but it proved a bit iffy for me at work. Happy to lend a hand with this if we break it down into smaller tasks and I find the time here and there ;)

**Comment by DestroyerXyz** [comment]
I can work on this if no one else already is.

**Comment by Greek** [comment]
> I can work on this if no one else already is.

Go for it!
