### ISSUE TITLE
Unable to add new entry for any types of accounts

### ISSUE THREAD

**Issue by tequilamooon** [maybe-finance/maybe#872]
**Where did this bug occur?**

- [x] Local development
- [ ] Self hosted app (i.e. Docker)

**Describe the bug**
The adding new entries under History, the button "Add" doesn't work.

**To Reproduce**
1. Go to any account 
2. Scroll down to 'History'
3. Click on 'New Entry'
4. Edit entry and click on 'Add'
5. See error

**Expected behavior**
A new history record should be showing up

**Additional context**
Macbook M2 system

**Comment by zachgoll** [comment]
@tequilamooon I'm not able to reproduce this following the instructions.

Can you provide a screencast / screenshots?
