### ISSUE TITLE
Safari 16.6 (18615.3.12.11.2) not supported.

### ISSUE THREAD

**Issue by poudenes** [maybe-finance/maybe#886]
Hi All,

Did a self hosting install and tried to access the site. Get the error that my Safari is not supported (MacOS Ventura 13.6.5)
I know there is a new MacOS version. 

Greets,

**Comment by zachgoll** [comment]
I'm going to close this out for now as it is not a bug.

While we intend to support a wider array of browsers in the future, we are currently only supporting a limited, modern set of browsers to simplify and speed up development.  Here are the versions supported:

Safari 17.2+, Chrome 120+, Firefox 121+, Opera 106+

Our current recommendation is to update Safari.  You can keep an eye on this code to see when we enable support for more browser versions:

https://github.com/maybe-finance/maybe/blob/0593d8fb7e586ddd9bfe396c000a48bfd6451304/app/controllers/application_controller.rb#L8

**Comment by poudenes** [comment]
The safari that come with the MacOS I use is 17.5.... Then it is a bug.

But focus on the application itself and then support browsers better is a idea
