### ISSUE TITLE
Should update project to use something like this - https://www.npmjs.com/package/cross-env to set env variables inside scripts.

### ISSUE THREAD

**Issue by coltonehrman** [maybe-finance/maybe#91]
Should update project to use something like this - https://www.npmjs.com/package/cross-env to set env variables inside scripts.

_Originally posted by @coltonehrman in https://github.com/maybe-finance/maybe/issues/90#issuecomment-1892777156_

**Comment by karan0handa** [comment]
Do any contributors / developers actually use Windows?

**Comment by karan0handa** [comment]
Do any contributors / developers actually use Windows?

**Comment by jbolda** [comment]
There are people that use Windows for development, yes. Also I would recommend using NX to help with en vars instead of pulling in a new dependency.

**Comment by tmyracle** [comment]
I believe this was resolved with changes to the scripts a little while ago. Closing for now, but feel free to open another if this is still an issue
