### ISSUE TITLE
Suppress issues from missing NX_POSTMARK_API_TOKEN

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#92]
When `NX_POSTMARK_API_TOKEN` is empty, an error is thrown:

```
error: uncaughtException: A valid API token must be provided.
PostmarkError: A valid API token must be provided.
```

We shouldn't _require_ `NX_POSTMARK_API_TOKEN` and instead should just ignore any email sending when that token is missing.

**Comment by tmyracle** [comment]
working on a fix for this now
