### ISSUE TITLE
Bug: Unable to edit transaction

### ISSUE THREAD

**Issue by mamarguerat** [maybe-finance/maybe#921]
**Describe the bug**
When I try to edit a transaction, the edit form appears. As soon as I edit a value, the edit form disappear and the change is not saved.

**To Reproduce**
1. Go to 'Transactions' or an account transactions history
2. Click on the description of a transaction
3. Edit a value (doesn't matter which one)
4. See error, the edit form is closed without saving

**Expected behavior**
When a value is edited, the form should stay opened and the change should be saved.
*OR*
When a value is edited, the form should stay opened and the change is not saved until we click on a 'save' button (which doesn't exist at the moment)

**Additional context**
Self-hosted instance behind reverse-proxy using docker-compose file

**Comment by zachgoll** [comment]
Confirmed, will get this fixed shortly.

**Comment by mamarguerat** [comment]
Thank you, I can confirm that it's fixed
