### ISSUE TITLE
Bug: Line chart is not updating end date

### ISSUE THREAD

**Issue by scubamaggo** [maybe-finance/maybe#940]
**Describe the bug**
It appears that the line chart is not updating the end date when the application is running for longer periods. It is stuck on the date when the application was started.

**To Reproduce**
1. Go to an Account with a transaction history. The last date will be the current date.
2. Wait until the next day.
3. The end date is stuck on the date seen in step 1 and will not update unless the app is restarted(?).

**Expected behavior**
The end date should be refreshed when the server date changes.

**Additional context**
I suspect this is due to the way the Period class is initialized. The class contains this code:
```
    BUILTIN = [
        new(name: "all", date_range: nil..Date.current),
        new(name: "last_7_days", date_range: 7.days.ago.to_date..Date.current),
        new(name: "last_30_days", date_range: 30.days.ago.to_date..Date.current),
        new(name: "last_365_days", date_range: 365.days.ago.to_date..Date.current)
    ]

    INDEX = BUILTIN.index_by(&:name)
```

This is called once upon class initialization, and I suspect this class is never(?) instantiated again via the provided chart methods.

**Comment by zachgoll** [comment]
Does manually syncing the account fix the chart?

**Comment by scubamaggo** [comment]
No, it does not. The chart remains on the date the docker container was started (or the account created? not sure).

![image](https://github.com/user-attachments/assets/541df9d5-3aac-495a-8f64-5436014fd24e)

**Comment by mamarguerat** [comment]
With the last built image, on my instance, it does update the chart when syncing the account. @scubamaggo Looking at your screenshot, you don't run the last commit as you still have the bug with the EUR total value.

**Comment by scubamaggo** [comment]
Thank you, good point. I haven't confirmed latest releases after the initial occurrence. Will do.

**Comment by zachgoll** [comment]
@scubamaggo the most recent build should have fixes for this.  I'll go ahead and close this out as I'm fairly confident things will work for you on upgrade, but feel free to re-open if you find otherwise.
