### ISSUE TITLE
Bug: Transfers are not working

### ISSUE THREAD

**Issue by DarkPhoenix2704** [maybe-finance/maybe#945]
**Describe the bug**

When I enter an transfer transaction, I move the amount from one depository account to another depository account, the amount is not getting updated. 
The amount should be deducted from the fromAccount and added to the depositAccount. 

**To Reproduce**
1. Add two deposit accounts
2. Add money to one account
3. create a transfer from one account to another
4. amount is not transferred

**Comment by zachgoll** [comment]
@DarkPhoenix2704 if you go to each of these accounts and hit the "sync" icon at the top right corner of the page, do the balances update correctly?

If so, I think we just need to trigger an account sync after a transfer is created to fix this.

**Comment by DarkPhoenix2704** [comment]
Sync fixed them. Thank you
