### ISSUE TITLE
Onboarding date picker doesn't allow dates < 1994

### ISSUE THREAD

**Issue by Shpigford** [maybe-finance/maybe#95]
![CleanShot_2024-01-15_at_18 25 362x](https://github.com/maybe-finance/maybe/assets/35243/5b5e40b3-da0c-4182-9893-684bee4c9170)

Date picker should allow any year but currently doesn't allow years before 1994.

I *believe* we had some sort of year limit before due to financial regulations, but that doesn't apply anymore.

**Comment by tmyracle** [comment]
Got it, fix incoming.
