### ISSUE TITLE
Doc improvement: Local mac setup needs vips installed

### ISSUE THREAD

**Issue by MagnusHJensen** [maybe-finance/maybe#952]
**PLEASE READ before opening an issue:**

- Is this a feature request?  Please [open a feature request discussion](https://github.com/maybe-finance/maybe/discussions/new?category=feature-requests).
- Do you need help or have a question?  Please [open a discussion](https://github.com/maybe-finance/maybe/discussions/new/choose) or [join our Discord](https://link.maybe.co/discord) and post to the "help" channel.

----------------------

**Is this issue related to a problem?  Please describe.**
When interacting with elements from ActiveStorage, since rails is on 7.2, it requires vips instead of mini_magick.
I ran into this issue, and from a quick google search I'm just missing to run `brew install vips`.

Could it be a good idea to update the [Mac Dev Setup Guide](https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide), and mention running the command `brew install vips` to avoid running into problems, for other mac develops in case they don't have it installed.

**Describe the work that needs to be done to address this issue**
Just a simple `brew install vips`.

**Additional context**

**Comment by zachgoll** [comment]
Done!

**Comment by liserjrqlxue** [comment]
[Windows-Dev-Setup-Guide](https://github.com/maybe-finance/maybe/wiki/Windows-Dev-Setup-Guide) also need install libvips in wsl, to fix something like avatar display
