### ISSUE TITLE
Can't login when using Nginx HTTPS Proxy

### ISSUE THREAD

**Issue by rossedlin** [maybe-finance/maybe#979]
**Describe the bug**

I'm running a HTTPS Nginx Proxy to handle the SSL.
It fails to login due to this.

Request URL: https://****/session
Request Method: POST
Status Code: 422 Unprocessable Content

**To Reproduce**
Try to login.

**Expected behavior**
Just refreshes the page.

**Screenshots / Recordings**
<img width="489" alt="Screenshot 2024-07-13 at 18 53 39" src="https://github.com/user-attachments/assets/04103b32-e8a9-4e8d-9aca-87c22fbf7e28">

**Comment by zachgoll** [comment]
@rossedlin can you share what you're seeing in the UI when this happens?  Are you on the login page?  Have you created an account for Maybe yet?  Or is this the very first login?

**Comment by rossedlin** [comment]
On the UI side of things, it appears to just redirect back to the login page.
It happens on first login AND any login afterwards.

When connecting directly without the HTTPS Nginx Proxy, it works perfectly.
I'm convinced it's something todo with either the port mapping as I'm running it on the default 3000 and then the proxy is on 443.
OR something todo with the domain.

Also to add...

When I enable preserve logging on chrome developer tools you can see /session throws a 422, I had a look in your code to see if I could fix it myself.

I saw that on line 15 - https://github.com/maybe-finance/maybe/blob/main/app/controllers/sessions_controller.rb
You are throwing a 422 if the password is wrong, but since I can login directly without the proxy, it makes me think that maybe when POSTing through the details it's malformed?

**Comment by zachgoll** [comment]
@rossedlin yeah the 422 makes me think that this is a headers/cookies issue not being received rather than a malformed request.

Can you share your Nginx proxy settings?  Particularly, would be interested to see how you're passing headers:

```nginx
location / {
    proxy_pass http://localhost:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

**Comment by zachgoll** [comment]
I believe this bug is caused by not passing headers from the proxy to the host.  Going to close out for now, but can reopen if we can get a working reproduction of this.

**Comment by rossedlin** [comment]
Just to confirm, you are 100% correct, this was the reason!
Thank you very much!
