### ISSUE TITLE
Bug: ActiveRecord::RecordInvalid: Validation failed

### ISSUE THREAD

**Issue by noname2001** [maybe-finance/maybe#995]
**Describe the bug**

after run rake task "demo_data:reset", get error below:
ActiveRecord::RecordInvalid: Validation failed: cannot sell 4.0 shares of AAPL because you only own 0.0 shares (ActiveRecord::RecordInvalid)

maybe the method below need to improve?

![CleanShot 2024-07-17 at 23 33 09@2x](https://github.com/user-attachments/assets/17e3772d-edfd-41e6-bc04-485800e5cd67)

**Comment by zachgoll** [comment]
This should be fixed via #993 now!  And yep, that's exactly what was causing the error.
